bonding enhancements
avocado-framework-tests/avocado-misc-tests pull request #1873
Opened 2020-09-02 17:58 UTC by vaishnavibhat

1) Ping check after slave gets reinstated
2) Change MTU of bond interface

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

2020-09-03 04:55 UTC, vaishnavibhat commented
JOB ID     : 5093355eecfb65fa8a6f8378e898d7de82de5cfd
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-09-01T20.12-5093355/job.log
 (01/21) bonding.py:Bonding.test_setup;round-robin-f724:  PASS (50.12 s)
 (02/21) bonding.py:Bonding.test_run;round-robin-f724:  PASS (1232.58 s)
 (03/21) bonding.py:Bonding.test_cleanup;round-robin-f724:  PASS (38.22 s)
 (04/21) bonding.py:Bonding.test_setup;active-backup-4c4d:  PASS (50.64 s)
 (05/21) bonding.py:Bonding.test_run;active-backup-4c4d:  PASS (1232.97 s)
 (06/21) bonding.py:Bonding.test_cleanup;active-backup-4c4d:  PASS (38.20 s)
 (07/21) bonding.py:Bonding.test_setup;balance-xor-fd42:  PASS (50.68 s)
 (08/21) bonding.py:Bonding.test_run;balance-xor-fd42:  PASS (1233.98 s)
 (09/21) bonding.py:Bonding.test_cleanup;balance-xor-fd42:  PASS (38.17 s)
 (10/21) bonding.py:Bonding.test_setup;broadcast-6cba:  PASS (50.69 s)
 (11/21) bonding.py:Bonding.test_run;broadcast-6cba:  PASS (1233.02 s)
 (12/21) bonding.py:Bonding.test_cleanup;broadcast-6cba:  PASS (38.08 s)
 (13/21) bonding.py:Bonding.test_setup;802.3ad-864a:  PASS (50.66 s)
 (14/21) bonding.py:Bonding.test_run;802.3ad-864a:  PASS (1232.82 s)
 (15/21) bonding.py:Bonding.test_cleanup;802.3ad-864a:  PASS (38.22 s)
 (16/21) bonding.py:Bonding.test_setup;balance-tlb-a0b6:  PASS (51.62 s)
 (17/21) bonding.py:Bonding.test_run;balance-tlb-a0b6:  PASS (1265.23 s)
 (18/21) bonding.py:Bonding.test_cleanup;balance-tlb-a0b6:  PASS (38.27 s)
 (19/21) bonding.py:Bonding.test_setup;balance-alb-17b2:  PASS (50.66 s)
 (20/21) bonding.py:Bonding.test_run;balance-alb-17b2:  PASS (1232.87 s)
 (21/21) bonding.py:Bonding.test_cleanup;balance-alb-17b2:  PASS (38.23 s)
RESULTS    : PASS 21 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-09-01T20.12-5093355/results.html
JOB TIME   : 9286.59 s
[bonding.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5166237/bonding.log)

2020-09-03 06:14 UTC, narasimhan-v requested changes
@vaishnavibhat Can you please split the 2 items into 2 separate commits ?

2020-09-03 06:14 UTC, narasimhan-v commented on io/net/bonding.py
> +                time.sleep(self.sleep_time)
2 sleeps needed ?

2020-09-03 06:14 UTC, narasimhan-v commented on io/net/bonding.py
> +                                "interface %s reinstated" % (arg1, interface)
Please add:
```
                    self.log.debug(error_str)
                    self.err.append(error_str)
```
as per lines 257

2020-09-16 08:04 UTC, narasimhan-v approved these changes

2020-09-16 08:04 UTC, merged