Calculate nping count
avocado-framework-tests/avocado-misc-tests pull request #1876
Opened 2020-09-08 10:01 UTC by vaishnavibhat

nping count is calculated as 20% more than the count value.

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

2020-09-08 10:59 UTC, vaishnavibhat commented
JOB ID     : 05fa9bf02df091fb21cd81e93e4d9d575c853ac0
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-09-08T05.56-05fa9bf/job.log
 (01/63) tcpdump.py:TcpdumpTest.test;run-mtu-1500-options-generic-6549:  FAIL: 58 packets dropped by kernel, more than 10 percent (5.00 s)
 (02/63) tcpdump.py:TcpdumpTest.test;run-mtu-2000-options-generic-cd46:  PASS (4.65 s)
 (03/63) tcpdump.py:TcpdumpTest.test;run-mtu-3000-options-generic-d4c2:  PASS (4.76 s)
 (04/63) tcpdump.py:TcpdumpTest.test;run-mtu-4000-options-generic-e58d:  PASS (4.60 s)
 (05/63) tcpdump.py:TcpdumpTest.test;run-mtu-5000-options-generic-cb49:  FAIL: 997 packets dropped by kernel, more than 10 percent (7.86 s)
 (06/63) tcpdump.py:TcpdumpTest.test;run-mtu-6000-options-generic-9747:  PASS (4.50 s)
 (07/63) tcpdump.py:TcpdumpTest.test;run-mtu-7000-options-generic-58fb:  PASS (4.24 s)
 (08/63) tcpdump.py:TcpdumpTest.test;run-mtu-8000-options-generic-0e45:  PASS (4.58 s)
 (09/63) tcpdump.py:TcpdumpTest.test;run-mtu-9000-options-generic-5c92:  FAIL: 96 packets dropped by kernel, more than 10 percent (4.18 s)
 (10/63) tcpdump.py:TcpdumpTest.test;run-mtu-1500-options-generic_host-d7bb:  PASS (4.03 s)
 (11/63) tcpdump.py:TcpdumpTest.test;run-mtu-2000-options-generic_host-7b75:  PASS (5.27 s)
 (12/63) tcpdump.py:TcpdumpTest.test;run-mtu-3000-options-generic_host-f432:  PASS (4.34 s)
 (13/63) tcpdump.py:TcpdumpTest.test;run-mtu-4000-options-generic_host-cf3f:  PASS (5.14 s)
 (14/63) tcpdump.py:TcpdumpTest.test;run-mtu-5000-options-generic_host-996b:  PASS (5.72 s)
 (15/63) tcpdump.py:TcpdumpTest.test;run-mtu-6000-options-generic_host-d810:  PASS (6.33 s)
 (16/63) tcpdump.py:TcpdumpTest.test;run-mtu-7000-options-generic_host-1283:  PASS (4.00 s)
 (17/63) tcpdump.py:TcpdumpTest.test;run-mtu-8000-options-generic_host-373c:  PASS (5.16 s)
 (18/63) tcpdump.py:TcpdumpTest.test;run-mtu-9000-options-generic_host-e06b:  PASS (4.39 s)
 (19/63) tcpdump.py:TcpdumpTest.test;run-mtu-1500-options-generic_src-23ed:  PASS (5.65 s)
 (20/63) tcpdump.py:TcpdumpTest.test;run-mtu-2000-options-generic_src-6845:  PASS (5.06 s)
 (21/63) tcpdump.py:TcpdumpTest.test;run-mtu-3000-options-generic_src-ff6e:  PASS (3.87 s)
 (22/63) tcpdump.py:TcpdumpTest.test;run-mtu-4000-options-generic_src-cca8:  PASS (4.58 s)
 (23/63) tcpdump.py:TcpdumpTest.test;run-mtu-5000-options-generic_src-17c4:  PASS (7.97 s)
 (24/63) tcpdump.py:TcpdumpTest.test;run-mtu-6000-options-generic_src-bc27:  FAIL: 620 packets dropped by kernel, more than 10 percent (5.42 s)
 (25/63) tcpdump.py:TcpdumpTest.test;run-mtu-7000-options-generic_src-930a:  PASS (4.38 s)
 (26/63) tcpdump.py:TcpdumpTest.test;run-mtu-8000-options-generic_src-1c87:  PASS (4.32 s)
 (27/63) tcpdump.py:TcpdumpTest.test;run-mtu-9000-options-generic_src-53a6:  PASS (4.51 s)
 (28/63) tcpdump.py:TcpdumpTest.test;run-mtu-1500-options-generic_dst-652a:  PASS (4.75 s)
 (29/63) tcpdump.py:TcpdumpTest.test;run-mtu-2000-options-generic_dst-6011:  PASS (5.59 s)
 (30/63) tcpdump.py:TcpdumpTest.test;run-mtu-3000-options-generic_dst-0141:  PASS (4.31 s)
 (31/63) tcpdump.py:TcpdumpTest.test;run-mtu-4000-options-generic_dst-03f2:  FAIL: 52 packets dropped by kernel, more than 10 percent (6.94 s)
 (32/63) tcpdump.py:TcpdumpTest.test;run-mtu-5000-options-generic_dst-428c:  PASS (8.83 s)
 (33/63) tcpdump.py:TcpdumpTest.test;run-mtu-6000-options-generic_dst-da08:  PASS (4.51 s)
 (34/63) tcpdump.py:TcpdumpTest.test;run-mtu-7000-options-generic_dst-5f88:  PASS (4.23 s)
 (35/63) tcpdump.py:TcpdumpTest.test;run-mtu-8000-options-generic_dst-a42f:  PASS (4.55 s)
 (36/63) tcpdump.py:TcpdumpTest.test;run-mtu-9000-options-generic_dst-2780:  PASS (4.11 s)
 (37/63) tcpdump.py:TcpdumpTest.test;run-mtu-1500-options-protocol_tcp-a9dc:  FAIL: 618 packets dropped by kernel, more than 10 percent (55.06 s)
 (38/63) tcpdump.py:TcpdumpTest.test;run-mtu-2000-options-protocol_tcp-19dd:  FAIL: 533 packets dropped by kernel, more than 10 percent (50.94 s)
 (39/63) tcpdump.py:TcpdumpTest.test;run-mtu-3000-options-protocol_tcp-b4e7:  PASS (50.34 s)
 (40/63) tcpdump.py:TcpdumpTest.test;run-mtu-4000-options-protocol_tcp-a261:  PASS (55.97 s)
 (41/63) tcpdump.py:TcpdumpTest.test;run-mtu-5000-options-protocol_tcp-1536:  PASS (60.42 s)
 (42/63) tcpdump.py:TcpdumpTest.test;run-mtu-6000-options-protocol_tcp-9aa2:  PASS (55.44 s)
 (43/63) tcpdump.py:TcpdumpTest.test;run-mtu-7000-options-protocol_tcp-6f58:  FAIL: 88 packets dropped by kernel, more than 10 percent (55.57 s)
 (44/63) tcpdump.py:TcpdumpTest.test;run-mtu-8000-options-protocol_tcp-f5b3:  PASS (49.97 s)
 (45/63) tcpdump.py:TcpdumpTest.test;run-mtu-9000-options-protocol_tcp-f7fd:  PASS (55.50 s)
 (46/63) tcpdump.py:TcpdumpTest.test;run-mtu-1500-options-protocol_udp-3df2:  PASS (4.69 s)
 (47/63) tcpdump.py:TcpdumpTest.test;run-mtu-2000-options-protocol_udp-5373:  PASS (4.48 s)
 (48/63) tcpdump.py:TcpdumpTest.test;run-mtu-3000-options-protocol_udp-1b29:  PASS (4.83 s)
 (49/63) tcpdump.py:TcpdumpTest.test;run-mtu-4000-options-protocol_udp-5afb:  PASS (4.80 s)
 (50/63) tcpdump.py:TcpdumpTest.test;run-mtu-5000-options-protocol_udp-3f81:  FAIL: 50 packets dropped by kernel, more than 10 percent (4.79 s)
 (51/63) tcpdump.py:TcpdumpTest.test;run-mtu-6000-options-protocol_udp-f14d:  PASS (4.78 s)
 (52/63) tcpdump.py:TcpdumpTest.test;run-mtu-7000-options-protocol_udp-aade:  PASS (4.66 s)
 (53/63) tcpdump.py:TcpdumpTest.test;run-mtu-8000-options-protocol_udp-ac60:  PASS (4.58 s)
 (54/63) tcpdump.py:TcpdumpTest.test;run-mtu-9000-options-protocol_udp-bd85:  FAIL: 694 packets dropped by kernel, more than 10 percent (6.22 s)
 (55/63) tcpdump.py:TcpdumpTest.test;run-mtu-1500-options-protocol_icmp-8a38:  PASS (21.10 s)
 (56/63) tcpdump.py:TcpdumpTest.test;run-mtu-2000-options-protocol_icmp-6a0d:  PASS (22.19 s)
 (57/63) tcpdump.py:TcpdumpTest.test;run-mtu-3000-options-protocol_icmp-3100:  PASS (26.71 s)
 (58/63) tcpdump.py:TcpdumpTest.test;run-mtu-4000-options-protocol_icmp-25bf:  PASS (32.59 s)
 (59/63) tcpdump.py:TcpdumpTest.test;run-mtu-5000-options-protocol_icmp-09e0:  PASS (34.04 s)
 (60/63) tcpdump.py:TcpdumpTest.test;run-mtu-6000-options-protocol_icmp-b05a:  PASS (30.56 s)
 (61/63) tcpdump.py:TcpdumpTest.test;run-mtu-7000-options-protocol_icmp-e40d:  PASS (29.89 s)
 (62/63) tcpdump.py:TcpdumpTest.test;run-mtu-8000-options-protocol_icmp-ebe1:  PASS (30.35 s)
 (63/63) tcpdump.py:TcpdumpTest.test;run-mtu-9000-options-protocol_icmp-86b8:  

PASS (30.24 s)
RESULTS    : PASS 53 | ERROR 0 | FAIL 10 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-09-08T05.56-05fa9bf/results.html
JOB TIME   : 977.16 s

[tcpdump.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5187847/tcpdump.log)

2020-09-17 06:07 UTC, narasimhan-v requested changes

2020-09-17 06:07 UTC, narasimhan-v commented on io/net/tcpdump.py
> +        nping_count = round(self.count + ((20 * self.count) / 100))
`round((120 * self.count) / 100)`

2020-09-29 06:24 UTC, narasimhan-v approved these changes

2020-09-29 06:39 UTC, merged