adding nping check after performance test
avocado-framework-tests/avocado-misc-tests pull request #1879
Opened 2020-09-09 10:04 UTC by vaishnavibhat

doing a ping check with tcp packets after iperf test.

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

2020-09-09 10:19 UTC, vaishnavibhat commented
avocado run iperf_test.py -m iperf_test.py.data/iperf_test.yaml 
/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/plugins/run.py:285: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  FutureWarning)
JOB ID     : a304025d692a34ba6d1d6742750a4b3070d6f06f
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2020-09-09T15.20-a304025/job.log
 (1/9) iperf_test.py:Iperf.test;1500-9990: PASS (83.68 s)
 (2/9) iperf_test.py:Iperf.test;2000-df88: PASS (82.70 s)
 (3/9) iperf_test.py:Iperf.test;3000-769a: PASS (82.65 s)
 (4/9) iperf_test.py:Iperf.test;4000-548c: PASS (82.67 s)
 (5/9) iperf_test.py:Iperf.test;5000-9a06: PASS (82.70 s)
 (6/9) iperf_test.py:Iperf.test;6000-1b19: PASS (82.63 s)
 (7/9) iperf_test.py:Iperf.test;7000-c2d9: PASS (82.67 s)
 (8/9) iperf_test.py:Iperf.test;8000-73a3: PASS (82.60 s)
 (9/9) iperf_test.py:Iperf.test;9000-74f9: PASS (82.70 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2020-09-09T15.20-a304025/results.html
JOB TIME   : 745.28 s

[iperf.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5194434/iperf.log)

2020-09-14 03:39 UTC, smruti77 requested changes

2020-09-14 03:39 UTC, smruti77 commented on io/net/iperf_test.py
> +        out = self.session.get_raw_ssh_command('ls')
@vaishnavibhat why you changed this like before .? already handle this as per utils.

2020-09-14 03:41 UTC, smruti77 requested changes

2020-09-14 03:41 UTC, smruti77 commented on io/net/iperf_test.py
> +        self.networkinterface.restore_from_backup()
@vaishnavibhat this is also same, don't remove try ..except. we handle this as we are getting exception if backup file was not there.

2020-09-14 03:51 UTC, smruti77 commented on io/net/iperf_test.py
> +            cmd = "./nping/nping --tcp %s -c 10" % self.peer_ip
@vaishnavibhat nmap things need to install before for suse.

2020-09-17 06:09 UTC, narasimhan-v requested changes
@vaishnavibhat Can you please explain more in the commit message ?

2021-09-08 13:39 UTC, PraveenPenguin commented
@vaishnavibhat if you are still perusing this PR , please feel Free to open PR having elaborative commit message , as this PR also has conflict

2021-09-08 13:39 UTC, closed without merging