Adding tests of keyutils
avocado-framework-tests/avocado-misc-tests pull request #1896
Opened 2020-09-22 15:45 UTC by nasastry

security/keyutils-tests.py adds keyutils tests

Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>

2020-09-22 15:45 UTC, nasastry commented
Job log:

```
JOB ID     : 46e60fde3c54f3154e5fe67fc7c3835b6f4815d0
JOB LOG    : /home/nasastry/avocado-fvt-wrapper/results/job-2020-09-22T11.08-46e60fd/job.log
 (1/1) keyutils-tests.py:KeyUtils.test: FAIL: 5 test(s) failed, please refer to the log (194.32 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/nasastry/avocado-fvt-wrapper/results/job-2020-09-22T11.08-46e60fd/results.html
JOB TIME   : 195.15 s
```

2020-09-22 16:20 UTC, nasastry commented
Job log after fixing unused local variable:
```
JOB ID     : ef61be5a0bda845b9b7626de5a445de0efce6c0a
JOB LOG    : /home/nasastry/avocado-fvt-wrapper/results/job-2020-09-22T11.59-ef61be5/job.log
 (1/1) keyutils-tests.py:KeyUtils.test: FAIL: 5 test(s) failed, please refer to the log (193.96 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/nasastry/avocado-fvt-wrapper/results/job-2020-09-22T11.59-ef61be5/results.html
JOB TIME   : 194.65 s
```

2020-09-23 11:03 UTC, harish-24 requested changes

2020-09-23 11:03 UTC, harish-24 commented on security/keyutils-tests.py
> +        os.chdir(self.logdir + '/tests/')
better to use `os.path.join()`

2020-09-23 11:03 UTC, harish-24 commented on security/keyutils-tests.py
> +        process.run("export AUTOMATED=1", shell=True)
`os.environ()` would work?

2020-09-23 11:03 UTC, harish-24 commented on security/keyutils-tests.py
> +        output = build.run_make(self.logdir + '/tests/',
same here

2020-09-23 11:03 UTC, harish-24 commented on security/keyutils-tests.py
> +        if count > 0:
`if count:` would suffice

2020-09-24 10:12 UTC, nasastry commented
```
JOB ID     : 7095bae05eb85b82bf3713d97d85630e6056ee75
JOB LOG    : /home/nasastry/avocado-fvt-wrapper/results/job-2020-09-24T05.38-7095bae/job.log
 (1/1) keyutils-tests.py:KeyUtils.test: FAIL: 5 test(s) failed, please refer to the log (193.16 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/nasastry/avocado-fvt-wrapper/results/job-2020-09-24T05.38-7095bae/results.html
JOB TIME   : 193.98 s
```

2020-09-24 10:21 UTC, nasastry commented
@harish-24 review comments taken care. Please review. Thanks!!

2020-09-24 10:27 UTC, nasastry commented
After all changes job log
```
JOB ID     : e785991f325fe336cbffa98b70a26e2c771a0e22
JOB LOG    : /home/nasastry/avocado-fvt-wrapper/results/job-2020-09-24T06.24-e785991/job.log
 (1/1) keyutils-tests.py:KeyUtils.test: FAIL: 5 test(s) failed, please refer to the log (197.45 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/nasastry/avocado-fvt-wrapper/results/job-2020-09-24T06.24-e785991/results.html
JOB TIME   : 198.37 s
```

2020-09-28 04:23 UTC, harish-24 approved these changes
LGTM

2020-09-28 12:38 UTC, merged