adding htx rpm link
avocado-framework-tests/avocado-misc-tests pull request #1923
Opened 2020-10-09 10:34 UTC by vaishnavibhat

adding htx rmp link.
code works seamlessly till March release.

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

2020-10-09 11:05 UTC, PraveenPenguin requested changes

2020-10-09 11:05 UTC, PraveenPenguin commented on io/net/htx_nic_devices.py.data/htx_nic_devices.yaml
> +htx_rpm: "http://ausgsa.ibm.com//gsa/ausgsa/projects/h/htx/public_html/htxonly/htxrhel8-544-LE.ppc64le.rpm"
@vaishnavibhat seems me this is not accessible via public network , may be this can be target as internal patch

2020-11-02 05:01 UTC, vaishnavibhat commented
With latest htx rpm:
$avocado run htx_nic_devices.py:HtxNicTest.test_start -m htx_nic_devices.py.data/htx_nic_devices.yaml 
JOB ID     : e88596fa9bcccbad10cee91d5833c4eef7309637
JOB LOG    : /root/bond_scen/upstream/tests/results/job-2020-11-02T10.22-e88596f/job.log
 (1/1) htx_nic_devices.py:HtxNicTest.test_start;run-c424: PASS (218.49 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/bond_scen/upstream/tests/results/job-2020-11-02T10.22-e88596f/results.html
JOB TIME   : 219.50 s

[htx.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5472892/htx.log)

2020-11-03 03:15 UTC, harish-24 commented
@vaishnavibhat Can you elaborate/fix the need for change in the commit message?

2020-11-03 05:24 UTC, vaishnavibhat commented
> @vaishnavibhat Can you elaborate/fix the need for change in the commit message? Now it still states to HTX url addition

Hi Harish, 
HTX rpm till after March fails to run with the current script. That is because the command 'build_net help n' returns 43 for two-system tests. Hence the test was failing with this command. The return status is expected as mentioned in  SW510665 . 
 I have resent the patch to work on latest rpm wrt to the exit status (43) rather than including the older rpm link the yaml file.

2020-11-03 08:56 UTC, harish-24 commented
> > @vaishnavibhat Can you elaborate/fix the need for change in the commit message? Now it still states to HTX url addition
> 
> Hi Harish,
> HTX rpm till after March fails to run with the current script. That is because the command 'build_net help n' returns 43 for two-system tests. Hence the test was failing with this command. 

Please do not disclose such internal information in open forum. Expect it to be deleted as soon as possible.

> I have resent the patch to work on latest rpm wrt to the exit status (43) rather than including the older rpm link the yaml file.
> 
> Changing the title accordingly.

As requested earlier commit message must clearly justify the reason for the change. So include necessary information in commit message.

2020-11-19 04:53 UTC, narasimhan-v commented
@vaishnavibhat Can you please change the commit heading and message according to the functionality ?

2020-11-19 04:57 UTC, vaishnavibhat commented
> @vaishnavibhat Can you please change the commit heading and message according to the functionality ?

Resent patch with updated commit heading and have changed it here accordingly.

2020-11-26 09:16 UTC, narasimhan-v approved these changes

2020-11-26 09:18 UTC, narasimhan-v commented
@PraveenPenguin Waiting for your ack based on previous review.

2020-11-26 14:32 UTC, PraveenPenguin approved these changes

2020-11-26 14:58 UTC, merged