Script to test idle states using cpupower monitor - v2
avocado-framework-tests/avocado-misc-tests pull request #1941
Opened 2020-10-29 06:40 UTC by Pavithra1602

Test covers below scenarios:
1- List the allowed Idle States using "cpupower monitor" command.
2 Run cpu intensilve workload and check that CPUs are not in Idle states, verify using "cpupower monitor" command.
Kill the workload run sleep command for sometime and check if the cpus have entered the idle states.
Disable one Idle state and check if the CPUs does not enter disabled Idle state.
Repeat the tests by offlining few CPUS.
Repeat the tests in different SMT modes.

Signed-off-by: Pavithra <pavrampu@linux.vnet.ibm.com>

2020-11-02 09:47 UTC, harish-24 requested changes

2020-11-02 09:47 UTC, harish-24 commented on cpupower_monitor.py
> +        self.output = self.run_cmd_out("cpupower idle-info --silent")
this does not need to be a class variable

2020-11-02 09:47 UTC, harish-24 commented on cpupower_monitor.py
> +        self.output = self.run_cmd_out(cmd)
same here

2020-11-02 09:47 UTC, harish-24 commented on cpupower_monitor.py
> +            zero_nonzero = self.check_zero_nonzero("cpupower monitor | grep -v '[A-Z]'", i + 1)
`grep -v '[A-Z]'` can be replaced in `check_zero_nonzero` the  with removing first two lines from output before looping

2020-11-02 09:47 UTC, harish-24 commented on cpupower_monitor.py
> +        if zero_nonzero:
```
        if not zero_nonzero:
            self.fail("cpus have not entered idle states after killing ebizzy workload")
        self.log.info("cpus have entered idle states after killing work load")
```

2020-11-02 09:47 UTC, harish-24 commented on cpupower_monitor.py
> +            if zero_nonzero:
same here

2020-11-02 09:47 UTC, harish-24 commented on cpupower_monitor.py
> +        process.run('ppc64_cpu --smt=off', shell=True)
Testcases like this specific to Power arch can be skipped on other architectures.

2020-11-05 16:55 UTC, Pavithra1602 commented
Raised new PR, with above comments addressed.

2020-11-05 16:55 UTC, closed without merging