perf_24x7_hardware_counters.py: changes made to support latest processor
avocado-framework-tests/avocado-misc-tests pull request #1975
Opened 2020-12-08 11:15 UTC by debade33

changes made to the perf events to support on latest processor

Signed-off-by: Debaleena De <debade33@in.ibm.com>

2020-12-08 11:20 UTC, debade33 commented
Without Patch
(01/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.76 s)
 (02/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_phys_core_param: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.74 s)
 (03/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_domain_param: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.68 s)
 (04/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_w_domain_param: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.60 s)
 (05/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_domain_not_existing: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.78 s)
 (06/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_all_domains: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.68 s)
 (07/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_w_chip_param: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.65 s)
 (08/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_chip_param: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.62 s)
 (09/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_domain_chip_offset: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.57 s)
 (10/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_phys_core: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.60 s)
 (11/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_vcpu: ERROR: 'EliminateDomainSuffix' object has no attribute 'perf_stat' (1.65 s)

With patch:
 (01/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: PASS (2.69 s)
 (02/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_phys_core_param: PASS (2.74 s)
 (03/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_domain_param: PASS (2.69 s)
 (04/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_w_domain_param: PASS (3.75 s)
 (05/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_domain_not_existing: PASS (3.81 s)
 (06/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_all_domains: PASS (7.96 s)
 (07/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_w_chip_param: PASS (2.70 s)
 (08/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_chip_param: PASS (2.84 s)
 (09/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_domain_chip_offset: PASS (103.44 s)
 (10/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_phys_core: PASS (2.81 s)
 (11/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_vcpu: PASS (2.86 s)

2020-12-11 16:04 UTC, harish-24 requested changes

2020-12-11 16:04 UTC, harish-24 commented on perf/perf_24x7_hardware_counters.py
> +        if self.cpu_family == 'power8' or self.cpu_family == 'power9':
this can be `if self.cpu_family in ['power8', 'power9']:`

2020-12-11 16:04 UTC, harish-24 commented on perf/perf_24x7_hardware_counters.py
> +            event_out = process.run("cat %s/events/"
`genio.read_file` can be used here instead of getting file contents through cat

2020-12-11 16:04 UTC, harish-24 commented on perf/perf_24x7_hardware_counters.py
> +        if self.cpu_family == 'power8' or self.cpu_family == 'power9':
same here

2020-12-11 16:04 UTC, harish-24 commented on perf/perf_24x7_hardware_counters.py
> +        if self.cpu_family == 'power8' or self.cpu_family == 'power9':
here too

2020-12-15 10:58 UTC, debade33 commented
localhost:/home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf # avocado run perf_24x7_hardware_counters.py
JOB ID     : 3015cf7da2b4de51db36ef7b9ef7d8b315dc8f34
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2020-12-15T16.16-3015cf7/job.log
 (01/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: PASS (3.14 s)
 (02/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_phys_core_param: PASS (3.20 s)
 (03/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_domain_param: PASS (3.16 s)
 (04/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_w_domain_param: PASS (4.20 s)
 (05/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_domain_not_existing: PASS (4.14 s)
 (06/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_all_domains: PASS (8.44 s)
 (07/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_w_chip_param: PASS (3.09 s)
 (08/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_chip_param: PASS (3.24 s)
 (09/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_domain_chip_offset: PASS (103.87 s)
 (10/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_phys_core: PASS (3.22 s)
 (11/11) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_vcpu: PASS (3.20 s)
RESULTS    : PASS 11 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2020-12-15T16.16-3015cf7/results.html
JOB TIME   : 145.35 s

2020-12-15 12:47 UTC, harish-24 commented
@debade33 Once the whitespace issue is fixed we are good to go.

2021-01-04 04:11 UTC, harish-24 approved these changes

2021-01-04 04:11 UTC, merged