make single script for PowerNVEEH.py and PowerVMEEH.py
avocado-framework-tests/avocado-misc-tests pull request #1985
Opened 2020-12-23 11:18 UTC by smruti77

added EEH.py test by combined both PowerNVEEH.py and PowerVMEEH.py
and removed both the test

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

2020-12-23 11:23 UTC, smruti77 commented
[EEH_powerNV.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5734853/EEH_powerNV.log)
[EEH_powerVM.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5734854/EEH_powerVM.log)

2021-02-17 16:07 UTC, narasimhan-v requested changes

2021-02-17 16:07 UTC, narasimhan-v commented on io/pci/EEH.py
> +        return "%s %s recovery failed: %s" % (self.thing, self.dev, self.log)
A better name instead of `thing` please

2021-02-17 16:07 UTC, narasimhan-v commented on io/pci/EEH.py
> +            cmd = "(dmesg | grep 'permanently disabled'; echo $?)"
While on it, can you change this to python parsing instead of grep please ?

2021-02-17 16:07 UTC, narasimhan-v commented on io/pci/EEH.py.data/EEH.yaml
> +scenario:
`scenario` is not needed

2021-02-18 07:49 UTC, smruti77 commented
[EEH.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6001059/EEH.log)

2021-03-08 04:13 UTC, narasimhan-v requested changes
@smruti77 Since we are enhancing this code, can we clean the code to remove most of bash processing please.

2021-03-08 04:13 UTC, narasimhan-v commented on io/pci/EEH.py
> +            if 'permanently disabled' in res and int(res[-1]) == 0:
echo $? is also not needed.
We can compare it using process.exit_status

2021-03-08 04:13 UTC, narasimhan-v commented on io/pci/EEH.py
> +            cmd = "errinjct eeh -v -f %s -s %s/%s -a %s -m %s; echo $?"\
echo $? is also not needed.
We can compare it using process.exit_status

2021-03-08 06:16 UTC, smruti77 commented
[powernveeh.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6099279/powernveeh.log)
[powervmeeh.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6099281/powervmeeh.log)

2021-03-11 04:25 UTC, narasimhan-v approved these changes

2021-03-11 04:25 UTC, merged