virt-net: parsing for system name fix
avocado-framework-tests/avocado-misc-tests pull request #1991
Opened 2021-01-11 20:22 UTC by cforno12

Found a bug where I had a machine ltczep10 and another machine ltczep1. The test
would act on the latter machine because of the line `if line in self.lpar`.
This fix assumes the format of an LPAR
`<name_of_the_system>-lp<partiton_number>`.

Signed-off-by: Cristobal Forno <cforno12@linux.ibm.com>

2021-01-13 04:04 UTC, cforno12 commented
I noticed that you have some CECs in your CI with the name `ltc-zz**-lp#`. How do you propose we expect the name of the CEC? Do we just add the name of the CEC as a param instead of trying to look for it?

2021-02-03 09:06 UTC, narasimhan-v requested changes

2021-02-03 09:06 UTC, narasimhan-v commented on io/net/virt-net/network_virtualization.py
> +            self.cancel("LPAR name incorrectly formatted. Expecting: <name>-lp<#>")
@cforno12 I don't think it is right to force lpar names. <name>-lp<#> is just a common nomenclature we follow.

2021-04-15 19:44 UTC, cforno12 commented
You're right, we shouldn't enforce naming policy. What do you think of this change?

2021-09-08 13:47 UTC, PraveenPenguin approved these changes

2021-09-08 13:48 UTC, PraveenPenguin commented
@narasimhan-v  new changes looks good to me can you also please review

2021-09-29 05:34 UTC, PraveenPenguin commented
@abdhaleegit review Please

2021-10-12 12:52 UTC, merged