evmctl-tests.py Adding ima-evmctl tests
avocado-framework-tests/avocado-misc-tests pull request #2003
Opened 2021-01-29 09:26 UTC by nasastry

Adding ima-evmctl test cases

Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>

2021-01-29 09:26 UTC, nasastry commented
Job log:
```
Fetching asset from evmctl-tests.py:EvmCtl.test
JOB ID     : 1478077ca288df6ff44a34e5d43a4a57ffc5b4bc
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2021-01-29T04.23-1478077/job.log
 (1/1) evmctl-tests.py:EvmCtl.test: PASS (30.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2021-01-29T04.23-1478077/results.html
JOB TIME   : 31.84 s
```

2021-02-01 06:05 UTC, harish-24 requested changes

2021-02-01 06:05 UTC, harish-24 commented on security/evmctl-tests.py
> +                count = line.split(":")[1].strip()
masking to int here is better since the count variable is stays int throughout

2021-02-01 06:05 UTC, harish-24 commented on security/evmctl-tests.py
> +        if int(count) > 0:
in any case `if count:` is sufficient

2021-02-01 06:05 UTC, harish-24 commented on security/evmctl-tests.py
> +        for line in output.splitlines():
Suggestion: Considering `# FAIL` is usually found at the end of the log better to traverse it from reserve and break out once it is found would hardly be 20 lines as opposed to the entire build log.

2021-02-02 05:58 UTC, nasastry commented
```
Fetching asset from evmctl-tests.py:EvmCtl.test
JOB ID     : 58cee180690fc0fdc3ae8e1f93314f026bccbb49
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2021-02-02T00.55-58cee18/job.log
 (1/1) evmctl-tests.py:EvmCtl.test: PASS (30.17 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2021-02-02T00.55-58cee18/results.html
JOB TIME   : 30.88 s
```

2021-02-09 11:00 UTC, harish-24 approved these changes
LGTM

2021-02-09 11:00 UTC, merged