cpu/idle_ipi_latency: Add idle_ipi_latency test wrapper
avocado-framework-tests/avocado-misc-tests pull request #2006
Opened 2021-02-01 02:31 UTC by agoel5920

This patch adds idle_ipi_latency which is a benchmark to measure the
impact of platform idle-states latency and the IPI latency on the
scheduler wakeups.

This patch also provides idle_ipi_latency.yaml which contain sample
input points for running the benchmark.

Signed-off-by: Abhishek Goel <huntbag@linux.vnet.ibm.com>

2021-02-01 02:34 UTC, agoel5920 commented
Adding snippet from debug.log

`21:29:51 INFO | Running '/var/tmp/avocado_70hncoe0/avocado_job_xz5uemak/1-cpu_idle_ipi_latency.py_Idle_ipi_latency.test_run-setup-duration-default-limitcpu-perf-producer-adb7/idle-ipi-scheduler-latency/postprocess_data.sh -l logs -o summary'
21:29:51 DEBUG| [stdout] <= 1 %age regression : 4 instances
21:29:51 DEBUG| [stdout] (1 - 2] %age regression : 2 instances
21:29:52 DEBUG| [stdout] (2 - 3] %age regression : 0 instances
21:29:52 DEBUG| [stdout] (3 - 5] %age regression : 0 instances
21:29:52 DEBUG| [stdout] (5 - 10] %age regression : 0 instances
21:29:52 DEBUG| [stdout] (10 - 20] %age regression : 0 instances
21:29:52 DEBUG| [stdout] (20 - 50] %age regression : 0 instances
21:29:52 DEBUG| [stdout] (50 - 100] %age regression : 0 instances`

2021-02-02 13:01 UTC, harish-24 requested changes

2021-02-02 13:01 UTC, harish-24 commented on cpu/idle_ipi_latency.py
> +        maxcpu = process.system_output('expr %s - 1' % nrcpu).decode("utf-8")
this can be achieved in python code as well

2021-02-15 04:14 UTC, harish-24 requested changes

2021-02-15 04:14 UTC, harish-24 commented on cpu/idle_ipi_latency.py
> +        lastcpu_nr = int(multiprocessing.cpu_count()) - 1
better to use the avocado [`cpu`](https://github.com/avocado-framework/avocado/blob/master/avocado/utils/cpu.py) module

2021-02-15 04:14 UTC, harish-24 commented on cpu/idle_ipi_latency.py
> +        summarydir = self.params.get('summarydir', default='summary')
not included yet

2021-03-04 14:18 UTC, agoel5920 commented
Let's hold this one for now. Because I see a lots of hack code in the benchmark itself. Will rewrite the benchmark first, then we can add this wrapper at later point of time.

2021-07-09 07:23 UTC, harish-24 commented
Closing due to inactivity, please re-open if needed.

2021-07-09 07:23 UTC, closed without merging