Add test for soft dirty bits stability
avocado-framework-tests/avocado-misc-tests pull request #2014
Opened 2021-02-23 06:52 UTC by harish-24

Patch adds test for soft dirty bits stability

Signed-off-by: Harish <harish@linux.ibm.com>

2021-02-23 06:53 UTC, harish-24 commented
```
JOB ID     : 894406495c7c4e187acdc484fb24fbb0853b951f
JOB LOG    : /home/harish/avocado-fvt-wrapper/results/job-2021-02-23T01.44-8944064/job.log
 (1/1) memory/soft_dirty.py:SoftDirtyBits.test: PASS (1.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/harish/avocado-fvt-wrapper/results/job-2021-02-23T01.44-8944064/results.html
JOB TIME   : 1.73 s
```

2021-03-14 07:51 UTC, PraveenPenguin requested changes

2021-03-14 07:51 UTC, PraveenPenguin commented on memory/soft_dirty.py
> +                    self.src_file, shell=True, ignore_status=True)
i feel we need to check if compilation failed as next step will not make any sense if bin itself not created , To achieve this either we need have ignore_status = False or we need to check exit status

2021-03-14 07:51 UTC, PraveenPenguin commented on memory/soft_dirty.py
> +            self.fail("Soft dirty bits est failed, please check the logs!")
can this message need to reworded as some how it not convey message properly

2021-03-15 09:14 UTC, harish-24 commented
@PraveenPenguin Pushed with changes, Thanks.

2021-03-15 09:59 UTC, PraveenPenguin approved these changes
LGTM

2021-03-16 05:02 UTC, PraveenPenguin commented
@harish-24 can you please resolve Travis issue , so it is good to go in

2021-03-17 07:06 UTC, merged