fixing error: C++ compiler cannot create executables
avocado-framework-tests/avocado-misc-tests pull request #2036
Opened 2021-04-14 11:50 UTC by shirishaganta1

Added gcc-c++ package to the script in order to
compile the libraries

Signed-off-by: Shirisha Ganta <SHIRISHA.Ganta1@ibm.com>

2021-04-14 12:50 UTC, shirishaganta1 commented
Before Patch:
# avocado run stressapptest.py
JOB ID     : ec806333908c4649b009a24fd463c7552a4896d5
JOB LOG    : /home/siri/avocado-fvt-wrapper/results/job-2021-04-14T16.34-ec80633/job.log
 (1/1) stressapptest.py:StressAppTest.test: ERROR: Command './configure' failed.\nstdout: b'configure: Compiling with dynamically linked libraries.\nchecking build system type... powerpc64le-unknown-linux-gnu\nchecking host system type... powerpc64le-unknown-linux-gnu\nchecking for a BSD-compatible install... (1.75 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/siri/avocado-fvt-wrapper/results/job-2021-04-14T16.34-ec80633/results.html
JOB TIME   : 2.22 s
After Patch:
 # avocado run stressapptest.py
JOB ID     : 0a398d34641eb436421f9c9a8f9b341329003214
JOB LOG    : /home/siri/avocado-fvt-wrapper/results/job-2021-04-14T16.39-0a398d3/job.log
 (1/1) stressapptest.py:StressAppTest.test: PASS (49.81 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/siri/avocado-fvt-wrapper/results/job-2021-04-14T16.39-0a398d3/results.html
JOB TIME   : 50.27 s

2021-04-15 05:10 UTC, harish-24 requested changes

2021-04-15 05:10 UTC, harish-24 commented on generic/stressapptest.py
> +        for package in ['gcc', 'libtool', 'autoconf', 'automake', 'make', 'gcc-c++']:
again needs to be handled for other distros as well.

2021-04-22 09:26 UTC, harish-24 approved these changes
LGTM

2021-04-22 09:26 UTC, merged