openblas.py: fixing make command for Power10
avocado-framework-tests/avocado-misc-tests pull request #2040
Opened 2021-04-16 05:39 UTC by shirishaganta1

gcc 10 would be required for power10 flags which is not there as
part of distro. So added extra args TARGET=POWER9 for fixing this

Signed-off-by: Shirisha Ganta <SHIRISHA.Ganta1@ibm.com>

2021-04-16 05:41 UTC, shirishaganta1 commented
Before Patch:
# avocado run openblas.py 
JOB ID     : b350b1b050d1d32c34a05ab1baf28b503fdfe310
JOB LOG    : /home/siri/avocado-fvt-wrapper/results/job-2021-04-16T10.41-b350b1b/job.log
 (1/1) openblas.py:Openblas.test: ERROR: Command 'make FC=gfortran ISMAXKERNEL=imax.S ISMINKERNEL=imin.S' failed.\nstdout: b'make[1]: Entering directory \'/var/tmp/avocado_evtac4tl/avocado_job_r_25o_hi/1-openblas.py_Openblas.test/OpenBLAS-develop/interface\'\ncc -O2 -DMAX_STACK_ALLOC=2048 -fopenm... (4.71 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/siri/avocado-fvt-wrapper/results/job-2021-04-16T10.41-b350b1b/results.html
JOB TIME   : 5.46 s
After Patch:
# avocado run openblas.py 
JOB ID     : adaed0d031ffcc0547094ec14025 ee570ec19de8
JOB LOG    : /home/siri/avocado-fvt-wrapper/results/job-2021-04-16T10.19-adaed0d/job.log
 (1/1) test.py:Openblas.test: PASS (264.12 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/siri/avocado-fvt-wrapper/results/job-2021-04-16T10.19-adaed0d/results.html
JOB TIME   : 264.61 s

2021-04-16 11:06 UTC, harish-24 requested changes

2021-04-16 11:06 UTC, harish-24 commented on generic/openblas.py
> +        for line in output.splitlines():
if we know the first line has the version we dont need to loop through all lines.

2021-04-16 11:06 UTC, harish-24 commented on generic/openblas.py
> +        proc_type = genio.read_file('/proc/cpuinfo').rstrip('\t\r\n\0')
we can use `cpu.get_family()` for version of power.

2021-04-16 11:06 UTC, harish-24 commented on generic/openblas.py
> +        print(self.test_dir)
we can remove this?

2021-04-22 09:32 UTC, harish-24 requested changes

2021-04-22 09:32 UTC, harish-24 commented on generic/openblas.py
> +        gcc_ver = re.search(r'\d+', output)
although this works can we narrow it down to `output.splitlines()[0]` so that the execution time reduces?

2021-04-22 09:32 UTC, harish-24 commented on generic/openblas.py
> +        result = build.make(self.test_dir, extra_args=self.target)
`build.make` returns only exit status, hence the following lines after this wont make sense. So please change it accordingly to `run_make`.

2021-05-06 14:26 UTC, harish-24 approved these changes
LGTM

2021-05-06 14:27 UTC, harish-24 commented
Once the summary after recent changes is pasted, this can be merged.

2021-06-08 10:12 UTC, shirishaganta1 commented
> Once the summary after recent changes is pasted, this can be merged.

After addressing all the above changes , below is the recent output 
--After Patch--
localhost:/home/avocado-fvt-wrapper/tests/avocado-misc-tests/generic # avocado run openblas.py 
JOB ID     : c82a52e1b99497f688b573bd04afcb23b496112f
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2021-06-09T09.50-c82a52e/job.log
 (1/1) openblas.py:Openblas.test: PASS (121.09 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2021-06-09T09.50-c82a52e/results.html
JOB TIME   : 121.80 s
localhost:/home/avocado-fvt-wrapper/tests/avocado-misc-tests/generic #

2021-06-08 10:14 UTC, merged