ssh control file check for bonding test
avocado-framework-tests/avocado-misc-tests pull request #2044
Opened 2021-04-19 09:20 UTC by vaishnavibhat

Bug fix for issue
https://github.com/avocado-framework-tests/avocado-misc-tests/issues/2032

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

2021-04-19 09:33 UTC, vaishnavibhat commented
avocado run bonding.py -m bonding.py.data/bonding_single.yaml
JOB ID     : 2318d20dff96315c3f2a2a210ae2e9a345e0b2fd
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2021-04-19T05.10-2318d20/job.log
 (1/3) bonding.py:Bonding.test_setup;run-1fe2: PASS (23.54 s)
 (2/3) bonding.py:Bonding.test_run;run-1fe2: PASS (237.54 s)
 (3/3) bonding.py:Bonding.test_cleanup;run-1fe2: PASS (27.98 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2021-04-19T05.10-2318d20/results.html
JOB TIME   : 290.04 s

[bonding.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6334870/bonding.log)

2021-05-20 11:06 UTC, abdhaleegit requested changes
Please make the file name generic

2021-05-20 11:06 UTC, abdhaleegit commented on io/net/bonding.py
> +                if file.startswith("avocado-master-root"):
when user changes, the file name changes too.. example `avocado-master-hscroot` ... make it generic something like `avocado-master`

2021-05-20 11:06 UTC, abdhaleegit commented on io/net/bonding.py
> +                if file.startswith("avocado-master-root"):
same for padmin

2021-05-20 11:54 UTC, abdhaleegit commented on io/net/bonding.py
> +                if file.startswith("avocado-master-root"):
`file` is a builtin in python,  but it works fine on python3.

2021-12-06 13:50 UTC, abdhaleegit approved these changes
LGTM

2021-12-07 05:26 UTC, merged