fsverity-tests.py: Add fsverity test cases
avocado-framework-tests/avocado-misc-tests pull request #2097
Opened 2021-07-06 06:49 UTC by nasastry

fsverity tests verifies the integrity/authenticity associtated
with the file.

Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>

2021-07-06 07:26 UTC, nasastry commented
```
RHEL:
JOB ID     : 200c158bd27c7d2b4924fe99137f38581bf845e1
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2021-07-06T02.22-200c158/job.log
 (1/1) fsverity-tests.py:fsverity.test: PASS (1.94 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2021-07-06T02.22-200c158/results.html
JOB TIME   : 2.51 s

SLES:
JOB ID     : 23cdfce2c80dd34d549995323e0b80882f7bc34f
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2021-07-06T11.52-23cdfce/job.log
 (1/1) fsverity-tests.py:fsverity.test: PASS (1.76 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2021-07-06T11.52-23cdfce/results.html
JOB TIME   : 2.03 s


JOB ID     : 4015ecbb86ff0348f7f6cf325de8f2cc5efa3635
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2021-07-06T02.41-4015ecb/job.log
 (1/1) fsverity-tests.py:fsverity.test: CANCEL: CONFIG_FS_VERITY not set. (0.59 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2021-07-06T02.41-4015ecb/results.html
JOB TIME   : 1.13 s
```

2022-09-30 10:48 UTC, abdhaleegit requested changes
apart from url rest all LGTM

2022-09-30 10:48 UTC, abdhaleegit commented on security/fsverity-tests.py
> +        url = "https://git.kernel.org/pub/scm/linux/kernel/git/ebiggers/fsverity-utils.git"
better to also have url from yaml

2022-10-19 08:33 UTC, nasastry commented
This test case run applies only to `upstream`, there is no `distro` package. 

```
RHEL:
JOB ID     : cd173e8c457a6efc3267a818a03fc276daf1acbd
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-19T03.26-cd173e8/job.log
 (1/1) fsverity-tests.py:fsverity.test: CANCEL: CONFIG_FS_VERITY not set. (0.45 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-19T03.26-cd173e8/results.html
JOB TIME   : 12.56 s


SLES:
JOB ID     : b4ba9de4810128de1c3f4ef21df608cbbe8add0b
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-19T13.54-b4ba9de/job.log
 (1/1) fsverity-tests.py:fsverity.test: PASS (3.80 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-19T13.54-b4ba9de/results.html
JOB TIME   : 25.09 s

```

[rhel_fsverity_job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9818399/rhel_fsverity_job.log)
[sles_fsverity_job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9818402/sles_fsverity_job.log)

2022-10-19 09:09 UTC, abdhaleegit approved these changes
LGTM

2022-10-19 09:09 UTC, merged