Added testcase for smtstate tool.
avocado-framework-tests/avocado-misc-tests pull request #2117
Opened 2021-08-05 13:39 UTC by Pavithra1602

This script tests smtstate tool for all smt states.

Signed-off-by: Pavithra <pavrampu@linux.vnet.ibm.com>

2021-08-05 13:40 UTC, Pavithra1602 commented
[console_log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/6939047/console_log.txt)

2021-08-08 14:26 UTC, PraveenPenguin requested changes

2021-08-08 14:26 UTC, PraveenPenguin commented on ras/smtstate.py
> +# See LICENSE for more details.
Copyright signature please  

```#
# Copyright: 2021 IBM
```

2021-08-08 14:26 UTC, PraveenPenguin commented on ras/smtstate.py
> +                process.system("smtstate --save")
if this command failed is next steps make sense , i say we need to check and fail the test if command failed

2021-08-08 14:26 UTC, PraveenPenguin commented on ras/smtstate.py
> +                process.system("smtstate --load")
here also

2021-08-08 14:26 UTC, PraveenPenguin commented on ras/smtstate.py
> +        self.detected_distro = distro.detect()
scope of variable can be method only

2021-08-11 10:24 UTC, closed without merging