[io/net] vlan.py: update the vlan test to use the latest utils
avocado-framework-tests/avocado-misc-tests pull request #2140
Opened 2021-10-04 20:14 UTC by cforno12-zz

Refactored and reorganized vlan test to use the latest avocado utils.

Signed-off-by: Cris Forno <fornosoccer12@gmail.com>

2021-12-02 01:16 UTC, Naresh-ibm commented on io/net/vlan_test.py
> +        self.peer_interface.ping_check(peer_ip=self.peer_ip, count=5)
is this something your doing self ping check?
Or ping from peer to host? if that is the case it should be,
self.peer_interface.ping_check(peer_ip=<host_ip>, count=5)

2021-12-14 05:59 UTC, abdhaleegit requested changes
@cforno12  Job logs please ?

2022-01-21 16:56 UTC, Naresh-ibm commented on io/net/vlan_test.py
> +        self.peer_interface.ping_check(peer_ip=self.peer_ip, count=5)
@vaishnavibhat can you please re-check on this and attached the latest logs?
So that we can ask for next steps.

2023-08-14 10:02 UTC, abdhaleegit commented
No activity from long time, Please reopen if you want to proceed further, also the PR does not work on latest switches as the cli is different, so not good idea to hardcode for one switch

2023-08-14 10:02 UTC, closed without merging