Added test support for ksm_tests.c
avocado-framework-tests/avocado-misc-tests pull request #2246
Opened 2022-03-03 19:49 UTC by SamirMulani

Signed-off-by: Samir Mulani <samir@linux.vnet.ibm.com>

2022-03-03 19:56 UTC, SamirMulani commented
Environment P9
Device Used:- SLES15-SP4 - Latest
Avocado version:- 94.0
*****************************************************************************************************
Test Logs:
```
install:/Workspace/Avocado_TestDev_Branch/KsmTest/MainBranch/avocado-misc-tests/kernel # avocado run --test-runner runner  kselftest.py -m kselftest.py.data/ksmtest.yaml
Fetching asset from kselftest.py:kselftest.test1
JOB ID     : 0ac8288c454ad4530c3ea4f3dfff49813c66562d
JOB LOG    : /root/avocado/job-results/job-2022-03-03T15.05-0ac8288/job.log
 (1/1) kselftest.py:kselftest.test1;run-component-334b: PASS (104.61 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-03-03T15.05-0ac8288/results.html
JOB TIME   : 105.35 s
```
********************************************************************************************************
-M option
#########
jg7ka/1-kselftest.py_kselftest.test1_run-component-9fc8/linux-master/tools/testing/selftests/zram'
2022-03-03 08:13:03,695 avocado.test DEBUG| PARAMS (key=test_type, path=*, default=-H) => '-M'
2022-03-03 08:13:03,695 avocado.test DEBUG| PARAMS (key=Size, path=*, default=-s) => '-s'
2022-03-03 08:13:03,695 avocado.test DEBUG| PARAMS (key=Dup_MM_Area, path=*, default=100) => '50'
2022-03-03 08:13:03,698 avocado.test INFO | =============./ksm_tests Logs============
2022-03-03 08:13:03,698 avocado.test INFO | OK

##############################################################################
-Z option
#########
2022-03-03 08:17:43,646 avocado.test INFO | =============./ksm_tests Logs============
2022-03-03 08:17:43,646 avocado.test INFO | OK

#############################################################################
-N option
#########
2022-03-03 08:24:29,283 avocado.test INFO | =============./ksm_tests Logs============
2022-03-03 08:24:29,283 avocado.test INFO | At least 2 NUMA nodes must be available

#############################################################################
-H option
#########
022-03-03 08:28:17,016 avocado.test INFO | =============./ksm_tests Logs============
2022-03-03 08:28:17,017 avocado.test INFO | Number of normal pages:    25
Number of huge pages:    0
Total size:    50 MiB
Total time:    0.015137814 s
Average speed:  3302.987 MiB/s

2022-03-24 11:05 UTC, Naresh-ibm commented on kernel/kselftest.py
> +            elif(self.test_type == "-M" or self.test_type == "-Z" or self.test_type == "-N" or self.test_type == "-U" or self.test_type == "-C"):
this can be as simple as below,
elif(self.test_type in ["-M", "-Z", "-N", "-U", "-C"]):

2022-03-24 11:10 UTC, Naresh-ibm commented on kernel/kselftest.py
> +                arg_payload = [r"./ksm_tests", self.test_type, self.Size_flag, self.Dup_MM_Area]
please make sure you are following the proper indentation like length > 79 char.
run pycodestyle and pylint before pushing the code.

2022-03-25 16:40 UTC, Naresh-ibm commented on kernel/kselftest.py
> +            self.fail("==============Envalied ksm_tests build path==============")
please add the path here like u added test_type in above line.
please also make sure that you follow the indentation as asked.
let me know if you need any help here.

2022-03-25 16:40 UTC, Naresh-ibm commented on kernel/kselftest.py
> +                    self.fail("========Failed to execute the ./ksm_tests {} {} {} Command=========".format(self.test_type, self.Size_flag, self.Dup_MM_Area))
maintain the indentation here.

2022-04-13 06:18 UTC, SamirMulani commented on kernel/kselftest.py
> +
Latest commit removes unwanted blank lines and keeps the ones that are needed.
**commit Id:** e7d23ef7a1a7fdb250e423857e0a80c8eb2e2806

2022-04-13 07:33 UTC, PraveenPenguin approved these changes
LGTM

2022-04-13 07:34 UTC, PraveenPenguin commented
@Naresh-ibm can you Please ACK this

2022-04-13 10:20 UTC, Naresh-ibm requested changes

2022-04-13 10:20 UTC, Naresh-ibm commented on kernel/kselftest.py
> +                                  self.Dup_MM_Area))
can be more simple than this, as below, for easy indentation too.

`self.fail("Test failed {}" .format(" ".join(arg_payload))`

2022-04-13 10:20 UTC, Naresh-ibm commented on kernel/kselftest.py.data/ksmtest.yaml
> +        Dup_MM_Area: "50"
I don't think these are only values needed for this test.
So you can leave them as blank
        test_type: " "
        Size: " "
        Dup_MM_Area: " "
        
        make sure you add the expected values for this input parameters in Readme file.
        if possible add some example for expected values.

2022-04-13 10:23 UTC, Naresh-ibm commented
@SamirMulani overall looks good to me.
just few cosmetic changes are required :-)

2022-04-13 16:44 UTC, PraveenPenguin requested changes
ah i did over looked the implementation i feel it require quite lot rework

2022-04-13 16:44 UTC, PraveenPenguin commented on kernel/kselftest.py
> +        cmd_output = subprocess.Popen(arg_payload,
can you please use avocado API like `process`

2022-04-13 16:44 UTC, PraveenPenguin commented on kernel/kselftest.py
> +        output_payload = output.decode("utf-8")
when you use `process` API it will be much simpler

2022-04-13 16:44 UTC, PraveenPenguin commented on kernel/kselftest.py
> +        """
yes, I did agree with @Naresh-ibm

2022-04-13 16:44 UTC, PraveenPenguin commented on kernel/kselftest.py
> +        self.test_type = self.params.get('test_type', default='-H')
these values can be read in the test itself

2022-04-13 18:03 UTC, Naresh-ibm requested changes

2022-04-13 18:06 UTC, Naresh-ibm commented
@SamirMulani I think Praveen's comments yet to taken care.
please let us know if you don't know how to use avocado's API, will help you.
So while re-sending the changes requested by Praveen, please take care the typo error

2022-04-14 06:38 UTC, Naresh-ibm commented
@SamirMulani looks like you have imported the subprocess but not used any where.
Thats what the alert says.
please remove it if your not using it and do a force push again

2022-04-14 10:11 UTC, SamirMulani commented on kernel/kselftest.py
> +
The typo mistake has been corrected in the latest commit.
**commit ID:** #2da6356

2022-04-19 10:50 UTC, PraveenPenguin approved these changes

2022-04-20 16:10 UTC, Naresh-ibm requested changes

2022-04-20 16:10 UTC, Naresh-ibm commented on kernel/kselftest.py
> +        self.Dup_MM_Area = self.params.get('Dup_MM_Area', default='100')
@SamirMulani this has not moved to setUp() still.
can u please check this. All user inputs should be capture or configured in method setUp().

2022-04-20 16:12 UTC, Naresh-ibm commented
Rest looks good to me. just do a quick force push with changes. and we are good to go then

2022-04-21 10:26 UTC, Naresh-ibm commented
Thanks @SamirMulani 
LGTM

2022-04-21 10:27 UTC, Naresh-ibm approved these changes

2022-04-25 08:09 UTC, merged