Code optimization for uprobe.py test script.
avocado-framework-tests/avocado-misc-tests pull request #2267
Opened 2022-04-04 12:24 UTC by SamirMulani

Code optimization for uprobe.py,
The enable_uprobes and disable_uprobes functions have been removed and a single function has been added to control uprobes.
Added support for handling system exceptions while writing data into the /sys/kernel/debug/tracing/ uprobe_events and other files

Signed-off-by: Samir Mulani <samir@linux.vnet.ibm.com>

2022-04-04 18:42 UTC, Naresh-ibm requested changes

2022-04-04 18:42 UTC, Naresh-ibm commented on ras/uprobe.py
> +    def ena_dis_uprobes(self, prob_value):
@SamirMulani can you please add docstrings to all the methods.
I don't see to any of the method. having doctrings methods are more self explanatory :-)

2022-04-05 16:54 UTC, Naresh-ibm requested changes

2022-04-05 16:54 UTC, Naresh-ibm commented on ras/uprobe.py
>      def test(self):
@SamirMulani please add here too.

2022-04-05 16:54 UTC, Naresh-ibm commented on ras/uprobe.py
> +
extra line is not require. please check this and remove it.

2022-04-05 16:54 UTC, Naresh-ibm commented on ras/uprobe.py
> +
here too.

2022-04-05 16:54 UTC, Naresh-ibm commented on ras/uprobe.py
> +
extra line not required

2022-04-05 16:54 UTC, Naresh-ibm commented on ras/uprobe.py
> +        ------------
I feel these cosmetic line are not required here as your already adding new line for better visualization.

2022-04-05 16:54 UTC, Naresh-ibm commented on ras/uprobe.py
> +
extra line not required

2022-04-05 16:54 UTC, Naresh-ibm commented on ras/uprobe.py
> +
same here, extra line not required.

2022-04-05 17:21 UTC, Naresh-ibm commented on ras/uprobe.py
> +
you missed this :-)

2022-04-05 17:23 UTC, Naresh-ibm commented
@PraveenPenguin its looks good to me.
test case wise if it is ok, then we can merge this.

2022-04-06 09:19 UTC, PraveenPenguin commented
@SamirMulani can you please wrap both the commits in single logical commit

2022-04-12 09:19 UTC, Naresh-ibm commented
LGTM.
@PraveenPenguin we can merge this if nothing from your end.

2022-04-13 06:06 UTC, PraveenPenguin approved these changes

2022-04-13 06:07 UTC, merged