updated the script to pick latest version
avocado-framework-tests/avocado-misc-tests pull request #2279
Opened 2022-04-20 15:16 UTC by preetithakur

script is updated so that it can pick the latest valgrind  version automatically
whenever its available.

Signed-off-by: preeti thakur <preeti.thakur@in.ibm.com>

[root@ltcever87-lp6 toolchain]# avocado run --test-runner runner valgrind.py
Fetching asset from valgrind.py:Valgrind.test
JOB ID     : a23ac84f87a1ee57703a9af355ab0b81dc54b4f6
JOB LOG    : /root/preeti/avocado-fvt-wrapper/results/job-2022-04-20T08.14-a23ac84/job.log
 (1/1) valgrind.py:Valgrind.test:  PASS (1966.78 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/preeti/avocado-fvt-wrapper/results/job-2022-04-20T08.14-a23ac84/results.html
JOB TIME   : 1997.65 s

2022-04-21 09:09 UTC, PraveenPenguin requested changes

2022-04-21 09:09 UTC, PraveenPenguin commented on toolchain/valgrind.py
> +            version = self.params.get('version', default="3.18.1")
please add this in ymal file

2022-04-21 09:11 UTC, Naresh-ibm approved these changes

2022-04-21 09:11 UTC, Naresh-ibm commented on toolchain/valgrind.py
> +            url = '%s/valgrind-%s.tar.bz2' % (url, version)
LGTM

2022-04-21 09:13 UTC, Naresh-ibm commented on toolchain/valgrind.py
> +            version = self.params.get('version', default="3.18.1")
> please add this in yaml file
ya, I was above to quote this.

2022-04-21 10:21 UTC, Naresh-ibm requested changes

2022-04-21 10:21 UTC, Naresh-ibm commented on toolchain/valgrind.py.data/valgrind_source.yaml
> +        version = self.params.get('version', default="3.18.1")
@preetithakur the right way to add parameter to the yaml is as below.
version: ""

I think url is not required here as it is defined in .py itself and doesn't need any input from yaml.
So only above line is enough but make sure the indentation part.

2022-04-25 10:59 UTC, Naresh-ibm commented
LGTM

2022-04-25 17:40 UTC, PraveenPenguin approved these changes

2022-04-25 17:40 UTC, merged