ras/smtstate: Simplify and fix distribution release/version checks
avocado-framework-tests/avocado-misc-tests pull request #2289
Opened 2022-05-04 08:48 UTC by sacsant

Existing check to detect distribution versions which support smtstate
tool is broken. The test will cancel out while running on any new major
versions for example RHEL9.0.

Simplify the code to detect and check distribution releases and versions,
also fix the warnings reported by pycodestyle.
    
Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>

2022-05-04 13:02 UTC, sacsant commented
JOB ID     : d6f877f0c429c7e778bbd0604e7a5784ab58e9bb
JOB LOG    : /home/avocado/results/job-2022-05-04T08.57-d6f877f/job.log
 (1/1) ras/smtstate.py:smtstate_tool.test: PASS (251.93 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado/results/job-2022-05-04T08.57-d6f877f/results.html
JOB TIME   : 268.19 s

2022-05-09 10:49 UTC, PraveenPenguin requested changes

2022-05-09 10:49 UTC, PraveenPenguin commented on ras/smtstate.py
> +                self.cancel("smtstate tool is supported only after SLES15 SP3")
the message needs to be included for SLES12 as well maybe like  `smtstate tool not  supported in SLES12 and SLES15SP3 `

2022-05-10 05:15 UTC, PraveenPenguin commented on ras/smtstate.py
> +                self.cancel("smtstate tool is supported only after SLES15 SP3")
ah sure make sense

2022-05-10 05:15 UTC, merged