Added proper cleanup for stress
avocado-framework-tests/avocado-misc-tests pull request #2301
Opened 2022-05-10 13:24 UTC by PraveenPenguin

as some cases load not got cleanup and in system those process running still and making system slow
making sure we kill these process in tearDown

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>

2022-05-10 13:24 UTC, PraveenPenguin commented
error log :
```
14:32:52 JOB ID     : 1e39837096aad081aa970690e870848890e9de9d
14:32:52 JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2022-05-09T05.02-1e39837/job.log
07:07:09  (1/1) avocado-misc-tests/cpu/cpustress.py:cpustresstest.test:  ERROR: [Errno 24] Too many open files (while :; do :; done) (59655.88 s)
07:07:09 RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
07:07:14 JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2022-05-09T05.02-1e39837/results.html
07:07:14 JOB TIME   : 59668.40 s
```

2022-05-13 04:49 UTC, PraveenPenguin commented
@abdhaleegit can you please review this PR as it kind of a hot Fix for CR runs

2022-05-14 10:24 UTC, sacsant commented
@PraveenPenguin while cleanup of resources before test exit is a good practice I am not sure how this will help fix too many open files issue reported while running cpustress test.

Killing the unwanted running process in teardown will help any subsequent test executed after cpustress test but will not help cpustress itself.  Did I miss any  particular aspect?

IMO a proper solution will be to set ulimit value (ulimit -n ) for open files to a very large number before starting the regression tests. By default 1024 is the value set for number of open files.

2022-05-16 07:44 UTC, abdhaleegit requested changes
@PraveenPenguin yes, the while loop in pinnned_cpus test

https://github.com/avocado-framework-tests/avocado-misc-tests/blob/2cf3cd00e10af2786a6378f5d66e9a3a08040e3c/cpu/cpustress.py#L224

though it is being killed by 
        self.__kill_process(pids)
        
@PraveenPenguin does it not solve the problem ?

2022-05-17 16:05 UTC, PraveenPenguin commented
> @PraveenPenguin yes, the while loop in pinnned_cpus test
> 
> https://github.com/avocado-framework-tests/avocado-misc-tests/blob/2cf3cd00e10af2786a6378f5d66e9a3a08040e3c/cpu/cpustress.py#L224
> 
> though it is being killed by self.__kill_process(pids)
> 
> @PraveenPenguin does it not solve the problem ?

no @abdhaleegit no luck with this :(

2022-05-17 16:12 UTC, PraveenPenguin commented
> @PraveenPenguin while cleanup of resources before test exit is a good practice I am not sure how this will help fix too many open files issue reported while running cpustress test.
> 
> Killing the unwanted running process in teardown will help any subsequent test executed after cpustress test but will not help cpustress itself. Did I miss any particular aspect?
> 
> IMO a proper solution will be to set ulimit value (ulimit -n ) for open files to a very large number before starting the regression tests. By default 1024 is the value set for number of open files.

@sacsant thank you for the review, yes good idea I just went ahead with an error message
 maybe we handle this way  
 1- having a cleanup making sure all workload is killed (even as Abdul pointed __kill_process not doing this )
 2- can we have ulimt set part of the test case or have documentation

2022-05-18 06:18 UTC, sacsant commented
> > @PraveenPenguin while cleanup of resources before test exit is a good practice I am not sure how this will help fix too many open files issue reported while running cpustress test.
> > Killing the unwanted running process in teardown will help any subsequent test executed after cpustress test but will not help cpustress itself. Did I miss any particular aspect?
> > IMO a proper solution will be to set ulimit value (ulimit -n ) for open files to a very large number before starting the regression tests. By default 1024 is the value set for number of open files.
> 
> @sacsant thank you for the review, yes good idea I just went ahead with an error message maybe we handle this way 1- having a cleanup making sure all workload is killed (even as Abdul pointed __kill_process not doing this ) 2- can we have ulimt set part of the test case or have documentation
> 
> Please let me know your through

How about following approach?

1. In setup save existing value of ulimit -n and the set it to a large value (depending on how many processes will be spawned by the test)
2. Print a info message letting the user know that open files descriptor value has been changed
3. in teardown extend the login to kill remaining unwanted processes and reset the ulimit -n value back to original.

2022-05-19 09:46 UTC, PraveenPenguin commented
> > > @PraveenPenguin while cleanup of resources before test exit is a good practice I am not sure how this will help fix too many open files issue reported while running cpustress test.
> > > Killing the unwanted running process in teardown will help any subsequent test executed after cpustress test but will not help cpustress itself. Did I miss any particular aspect?
> > > IMO a proper solution will be to set ulimit value (ulimit -n ) for open files to a very large number before starting the regression tests. By default 1024 is the value set for number of open files.
> > 
> > 
> > @sacsant thank you for the review, yes good idea I just went ahead with an error message maybe we handle this way 1- having a cleanup making sure all workload is killed (even as Abdul pointed __kill_process not doing this ) 2- can we have ulimt set part of the test case or have documentation
> > Please let me know your through
> 
> How about following approach?
> 
>     1. In setup save existing value of ulimit -n and the set it to a large value (depending on how many processes will be spawned by the test)
> 
>     2. Print a info message letting the user know that open files descriptor value has been changed
> 
>     3. in teardown extend the logic to kill remaining unwanted processes and reset the ulimit -n value back to original.

looks good @sacsant will send fix soon

2023-02-25 12:38 UTC, PraveenPenguin commented
closing this as not seeing this issue any more

2023-02-25 12:38 UTC, closed without merging