Done rework for va_test.c
avocado-framework-tests/avocado-misc-tests pull request #2349
Opened 2022-06-21 11:05 UTC by SamirMulani

With older implementations, MAP_CHUNK_SIZE is fixed to 16 GB, as a
result fix value, On low memory the test case is getting failed with
ENOMEM error message where it clearly indicates that not enough memory
is present in the system, which results in a few va_test cases failing.
The above changes will dynamically adjust the MAP_CHUNK_SIZE value
according to the amount of space in the system.

Signed-off-by: Samir Mulani <samir@linux.vnet.ibm.com>

2022-06-23 07:17 UTC, sacsant requested changes

2022-06-23 07:17 UTC, sacsant commented on memory/vatest.py.data/va_test.c
> +                        //printf("Number is: %i", num);
I guess we don't need this statement and can be removed.

2022-06-23 07:17 UTC, sacsant commented on memory/vatest.py.data/va_test.c
> +                        return num;
A corresponding pclose() call is missing.

2022-06-23 07:17 UTC, sacsant commented on memory/vatest.py.data/va_test.c
> +                unsigned long map_chunk_size = mm_aloc*1024*1024*1024;
Do we really need these 2 additional variables. We should be able to change this to
MAP_CHUNK_SIZE = (total_free_mm - 2)*1024*1024*1024

2022-06-23 07:17 UTC, sacsant commented on memory/vatest.py.data/va_test.c
> +	mem_checkpoint();
This call should be moved after the check for argc < 3

2022-06-23 12:16 UTC, sacsant commented on memory/vatest.py.data/va_test.c
> +
Remove the blank line.

2022-06-23 12:16 UTC, sacsant commented on memory/vatest.py.data/va_test.c
> +        }
Requires another pclose() if the control reaches here.

2022-06-23 12:16 UTC, sacsant commented on memory/vatest.py.data/va_test.c
> +        {
No need to have these brackets

2022-06-23 12:16 UTC, sacsant commented on memory/vatest.py.data/va_test.c
> +
Can you add a comment on logic used in this code?

2022-06-24 05:38 UTC, sacsant commented
> A corresponding pclose() call is missing.

@SamirMulani , on second thought, do we really need another function for parsing /proc/meminfo? Why can't existing function local_read_meminfo() be reused/extended?

2022-06-24 09:38 UTC, SamirMulani commented
> > A corresponding pclose() call is missing.
> 
> @SamirMulani , on second thought, do we really need another function for parsing /proc/meminfo? Why can't existing function local_read_meminfo() be reused/extended?

@sacsant Thank you for the guidance. Yes, we can use the existing local_read_meminfo() function. Updated commit reflects all the changes as per the inputs.

2022-06-27 05:19 UTC, sacsant commented
> @sacsant Thank you for the guidance. Yes, we can use the existing local_read_meminfo() function. Updated commit reflects all the changes as per the inputs.
I see that you have incorporated the review changes into a different commit. Can you fold the latest changes into a single commit ?

2022-06-27 08:59 UTC, sacsant reviewed
Can you update the commit message to match with the changes proposed? You can use the same text mentioned in the initial comment of this PR. 

Rest of the changes LGTM.

2022-06-28 15:16 UTC, sacsant approved these changes
Can you post run logs for reference.

LGTM.

2022-06-28 19:12 UTC, SamirMulani commented
```
**Avocado test case run log:**
# avocado run --test-runner runner vatest.py
JOB ID     : 0c4e21e92db037e1b2bc46ae1cdb99f0afebd5b4
JOB LOG    : /root/avocado/job-results/job-2022-06-29T00.35-0c4e21e/job.log
 (1/1) vatest.py:VATest.test: PASS (2.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2022-06-29T00.35-0c4e21e/results.html
JOB TIME   : 2.45 s
```

**Va test binary run log:**
```
 ./va_test -s 1 -n 0 -h 0 -d 0

Scenario 1 : Alloc default pagesize from 0-512 tb VA with above 128 first

Allocating default pagesize pages > 128TB 
> 128Tb: 
 chunks allocated= 24575 
Allocating default pagesize pages < 128TB 
< 128Tb: 
 chunks allocated= 8190 

Test Passed!!
```

2022-06-29 04:10 UTC, merged