ras_extended.py: Added locking mechanism testcase
avocado-framework-tests/avocado-misc-tests pull request #2352
Opened 2022-06-23 02:42 UTC by shirishaganta1

Locking mechanism prevents corruption of DB file when running vpdupdate.
This tests database (vpd.db) locking mechanism when multiple instances
of vpdupdate and lsvpd are running simultaneously.

Signed-off-by: Shirisha Ganta <SHIRISHA.Ganta1@ibm.com>

2022-06-23 02:43 UTC, shirishaganta1 commented
on Rhel9.1
\# avocado run --test-runner runner ras_extended.py
JOB ID     : 200271d271d1284e443dd93f510efb5008d26cac
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-06-22T21.34-200271d/job.log
 (01/12) ras_extended.py:RASTools.test1_uesensor: PASS (1.24 s)
 (02/12) ras_extended.py:RASTools.test1_serv_config: PASS (1.32 s)
 (03/12) ras_extended.py:RASTools.test1_ls_vscsi: PASS (1.40 s)
 (04/12) ras_extended.py:RASTools.test1_ls_veth: PASS (1.08 s)
 (05/12) ras_extended.py:RASTools.test1_ls_vdev: PASS (1.26 s)
 (06/12) ras_extended.py:RASTools.test1_lsdevinfo: PASS (1.70 s)
 (07/12) ras_extended.py:RASTools.test1_hvcsadmin: PASS (1.36 s)
 (08/12) ras_extended.py:RASTools.test1_bootlist: PASS (53.35 s)
 (09/12) ras_extended.py:RASTools.test1_vpdupdate: PASS (2.40 s)
 (10/12) ras_extended.py:RASTools.test3_lsvpd: PASS (3.26 s)
 (11/12) ras_extended.py:RASTools.test3_lscfg: PASS (1.86 s)
 (12/12) ras_extended.py:RASTools.test_locking_mechanism: PASS (3.19 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-06-22T21.34-200271d/results.html
JOB TIME   : 94.96 s

on Rhel8.4
\# avocado run --test-runner runner ras_extended.py
JOB ID     : 42b5307893555f338bcc94c27db83613ccb47cec
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-06-22T21.31-42b5307/job.log
 (01/13) ras_extended.py:RASTools.test1_uesensor: PASS (1.62 s)
 (02/13) ras_extended.py:RASTools.test1_serv_config: PASS (1.63 s)
 (03/13) ras_extended.py:RASTools.test1_ls_vscsi: PASS (1.52 s)
 (04/13) ras_extended.py:RASTools.test1_ls_veth: PASS (1.58 s)
 (05/13) ras_extended.py:RASTools.test1_ls_vdev: PASS (1.55 s)
 (06/13) ras_extended.py:RASTools.test1_lsdevinfo: PASS (2.97 s)
 (07/13) ras_extended.py:RASTools.test1_hvcsadmin: PASS (1.86 s)
 (08/13) ras_extended.py:RASTools.test1_bootlist: PASS (2.66 s)
 (09/13) ras_extended.py:RASTools.test1_vpdupdate: PASS (2.74 s)
 (10/13) ras_extended.py:RASTools.test3_lsvpd: PASS (2.88 s)
 (11/13) ras_extended.py:RASTools.test3_lscfg: PASS (1.90 s)
 (12/13) ras_extended.py:RASTools.test_usysident: PASS (3.34 s)
 (13/13) ras_extended.py:RASTools.test_locking_mechanism: FAIL: Database corruption detected (23.15 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-06-22T21.31-42b5307/results.html
JOB TIME   : 63.07 s

2022-06-23 06:47 UTC, sacsant commented on ras/ras_extended.py
> +        ret = process.run(cmd, ignore_bg_processes=True, ignore_status=True,
@shirishaganta1 can you incorporate the review comments(from the previous PR) from Naresh?
for _ in range(500):                                                                                                                                                                    
    ret = process.run("vpdupdate", ignore_status=True, shell=True)

2022-06-23 06:48 UTC, sacsant commented on ras/ras_extended.py
> +        ret1 = process.run(cmd1, ignore_bg_processes=True, ignore_status=True,
Same changes required.

2022-06-23 16:17 UTC, Naresh-ibm commented
@shirishaganta1 also please  attach the job.log file

2022-06-24 06:38 UTC, abdhaleegit requested changes
@shirishaganta1 So if vpdupdate and lsvpd run in parallel .. there is always chances of corruption
```
terminate called after throwing an instance of 'lsvpd::VpdException'
  what():  SQLITE Error 5: database is locked

Aborted (core dumped)
terminate called after throwing an instance of 'lsvpd::VpdException'
  what():  SQLITE Error 1: SQL logic error

Aborted (core dumped)
````
So is this a bug ?

aren't we suppose to run lsvpd and vpdupdate serially ?

2022-06-30 04:29 UTC, sacsant commented
> @shirishaganta1 So if vpdupdate and lsvpd run in parallel .. there is always chances of corruption
> 
> ```
> terminate called after throwing an instance of 'lsvpd::VpdException'
>   what():  SQLITE Error 5: database is locked
> 
> Aborted (core dumped)
> terminate called after throwing an instance of 'lsvpd::VpdException'
>   what():  SQLITE Error 1: SQL logic error
> 
> Aborted (core dumped)
> ```
> 
> So is this a bug ?
> 
> aren't we suppose to run lsvpd and vpdupdate serially ?

The test case is written to exactly check for this defect, If run in parallel no data corruption should occur.

2022-06-30 04:31 UTC, sacsant commented on ras/ras_extended.py
> +        ret = process.run(cmd, ignore_bg_processes=True, ignore_status=True,
For some reason the above code does not work as expected. Let's go ahead with the original code for now. We can figure out later if any additional modifications are required.

2022-06-30 04:35 UTC, shirishaganta1 commented
As discussed offline,   we will go ahead with current code changes

2022-06-30 04:36 UTC, shirishaganta1 commented
> @shirishaganta1 also please attach the job.log file

[Rehl91-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9016404/Rehl91-job.log)
[Rhel87-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9016405/Rhel87-job.log)

2022-07-13 06:28 UTC, sacsant approved these changes
LGTM.

2022-07-27 10:49 UTC, PraveenPenguin approved these changes

2022-07-27 10:49 UTC, merged