removing the no_fs support for disktest.py
avocado-framework-tests/avocado-misc-tests pull request #2384
Opened 2022-07-29 16:19 UTC by Naresh-ibm

for larger size disks like nvme, this is utilizing the complete root space
to run the test when no_fs option is given and hence, OS will be left with
no space and other runs are failing. hence removing the no_fs support for
the disktest.

Signed-off-by: Naresh Bannoth <nbannoth@in.ibm.com>

2022-07-29 16:22 UTC, Naresh-ibm commented
with no_fs 
------------------

07:03:33 INFO    : Running Host Tests Suite io_fc_disktest_disktest
07:03:33 INFO    : Running: /usr/local/bin/avocado run --nrunner-max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py -m /tmp/mux/io_fc_disktest_disktest.yaml --force-job-id 4cab9f71249050b77ea4c9df7e527fb2e36b689d  --job-results-dir /root/nvmf-output/results
JOB ID     : 4cab9f71249050b77ea4c9df7e527fb2e36b689d
JOB LOG    : /root/nvmf-output/results/job-2022-07-29T07.03-4cab9f7/job.log
 (1/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-ext4-raid-raid-e72e: STARTED
 (1/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-ext4-raid-raid-e72e: PASS (454.52 s)
 (2/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-ext4-raid-no_raid-a2b7: STARTED
 (2/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-ext4-raid-no_raid-a2b7: PASS (454.32 s)
 (3/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-xfs-raid-raid-871d: STARTED
 (3/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-xfs-raid-raid-871d: PASS (444.65 s)
 (4/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-xfs-raid-no_raid-66a9: STARTED
 (4/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-xfs-raid-no_raid-66a9: PASS (487.86 s)
 (5/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-btrfs-raid-raid-fae9: STARTED
 (5/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-btrfs-raid-raid-fae9: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (1.19 s)
 (6/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-btrfs-raid-no_raid-7e75: STARTED
 (6/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-btrfs-raid-no_raid-7e75: CANCEL: btrfs is not supported with                                 RHEL 7.4 onwards (1.76 s)
 (7/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/disktest.py:Disktest.test;run-filesystem-no_fs-raid-raid-087a: STARTED
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Runner._update_status() done, defined at /usr/local/lib/python3.9/site-packages/avocado_framework-94.0-py3.9.egg/avocado/plugins/runner_nrunner.py:310> exception=OSError(28, 'No space left on device')>
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/avocado_framework-94.0-py3.9.egg/avocado/plugins/runner_nrunner.py", line 325, in _update_status
    message_handler.process_message(message, task, job)
  File "/usr/local/lib/python3.9/site-packages/avocado_framework-94.0-py3.9.egg/avocado/core/messages.py", line 68, in process_message
    handler.process_message(message, task, job)
  File "/usr/local/lib/python3.9/site-packages/avocado_framework-94.0-py3.9.egg/avocado/core/messages.py", line 84, in process_message
    handler.process_message(message, task, job)
  File "/usr/local/lib/python3.9/site-packages/avocado_framework-94.0-py3.9.egg/avocado/core/messages.py", line 55, in process_message
    self.handle(message, task, job)
  File "/usr/local/lib/python3.9/site-packages/avocado_framework-94.0-py3.9.egg/avocado/core/messages.py", line 308, in handle
    self._save_to_default_file(message, task)
  File "/usr/local/lib/python3.9/site-packages/avocado_framework-94.0-py3.9.egg/avocado/core/messages.py", line 226, in _save_to_default_file
    self._save_message_to_file(DEFAULT_LOG_FILE, data, task,
  File "/usr/local/lib/python3.9/site-packages/avocado_framework-94.0-py3.9.egg/avocado/core/messages.py", line 275, in _save_message_to_file
    _save_to_file(file, "a")
  File "/usr/local/lib/python3.9/site-packages/avocado_framework-94.0-py3.9.egg/avocado/core/messages.py", line 270, in _save_to_file
    fp.write(buff)
OSError: [Errno 28] No space left on device

Avocado crashed: OSError: [Errno 28] No space left on device: '/root/nvmf-output/results/job-2022-07-29T07.03-4cab9f7/test-results/8-_root_avocado-fvt-wrapper_tests_avocado-misc-tests_io_disk_disktest.py_Disktest.test_run-filesystem-no_fs-raid-no_raid-dc7d'

2022-07-29 16:23 UTC, Naresh-ibm commented
`[root@ltcever60-lp12 ~]# df -lH
Filesystem                             Size  Used Avail Use% Mounted on
devtmpfs                                21G     0   21G   0% /dev
tmpfs                                   21G  263k   21G   1% /dev/shm
tmpfs                                  8.4G   37M  8.3G   1% /run
/dev/mapper/rhel_ltcever60--lp12-root   39G   39G  8.0M 100% /
/dev/sda2                              1.1G  431M  633M  41% /boot
/dev/mapper/rhel_ltcever60--lp12-home   19G  164M   19G   1% /home
tmpfs                                  4.2G  525k  4.2G   1% /run/user/0
[root@ltcever60-lp12 ~]#`

2022-07-30 04:26 UTC, PraveenPenguin approved these changes

2022-08-08 09:41 UTC, abdhaleegit requested changes
@Naresh-ibm will this problem can be seen on fio, tiobench, dbench, iozone  as it also has no_fs ?  should you remove their too

2022-08-09 07:24 UTC, Naresh-ibm commented
> @Naresh-ibm will this problem can be seen on fio, tiobench, dbench, iozone as it also has no_fs ? should you remove their too

As discussed this is not effecting other test but disktest uses the larger chunks of memory, hence it is utilizing complete /root/ disk space and OS hangs as a effect.

2022-08-09 07:29 UTC, abdhaleegit approved these changes
LGTM

2022-08-09 07:29 UTC, merged