evmctl-tests.py: add distribution specific test cases
avocado-framework-tests/avocado-misc-tests pull request #2412
Opened 2022-09-20 14:46 UTC by nasastry

Add distribution specific test cases.
With the support of yaml, can run distribution and upstream test cases.

Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>

2022-09-20 14:47 UTC, nasastry commented
RHEL:

```
JOB ID     : 096e4af24b6e7d646154870652d4dbf95aa04bec
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-20T09.33-096e4af/job.log
 (1/2) evmctl-tests.py:EvmCtl.test;run-run_type-upstream-583f: FAIL: 2 test(s) failed, please refer to the log (19.71 s)
 (2/2) evmctl-tests.py:EvmCtl.test;run-run_type-distro-70cf: FAIL: 2 test(s) failed, please refer to the log (26.43 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-20T09.33-096e4af/results.html
JOB TIME   : 56.14 s
```

SLES:
```
JOB ID     : fa4dbb932f4eac6d3cc1b13b1822785b5730a53a
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-20T20.04-fa4dbb9/job.log
 (1/2) evmctl-tests.py:EvmCtl.test;run-run_type-upstream-583f: FAIL: 1 test(s) failed, please refer to the log (32.23 s)
 (2/2) evmctl-tests.py:EvmCtl.test;run-run_type-distro-70cf: FAIL: 1 test(s) failed, please refer to the log (42.06 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-20T20.04-fa4dbb9/results.html
JOB TIME   : 94.81 s
```

2022-09-21 04:39 UTC, nasastry commented
RHEL:
```
JOB ID     : 78764db8593bf669d7fd48cd7f3ca058ed46d1a7
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-20T23.37-78764db/job.log
 (1/2) evmctl-tests.py:EvmCtl.test;run-run_type-upstream-37c6: FAIL: 2 test(s) failed, please refer to the log (22.74 s)
 (2/2) evmctl-tests.py:EvmCtl.test;run-run_type-distro-c4a8: FAIL: 2 test(s) failed, please refer to the log (29.53 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-20T23.37-78764db/results.html
JOB TIME   : 59.58 s
```

SLES:
```
JOB ID     : fd140c4a5cbf7650ff3a1052183c4c87c2a975e7
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-21T10.04-fd140c4/job.log
 (1/2) evmctl-tests.py:EvmCtl.test;run-run_type-upstream-37c6: FAIL: 1 test(s) failed, please refer to the log (40.76 s)
 (2/2) evmctl-tests.py:EvmCtl.test;run-run_type-distro-c4a8: FAIL: 1 test(s) failed, please refer to the log (45.57 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-21T10.04-fd140c4/results.html
JOB TIME   : 107.06 s
```

2022-10-07 06:54 UTC, nasastry commented
```
SLES:
JOB ID     : f978bfc6f951d0612977e5c27ee10e1b117e1609
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-07T12.16-f978bfc/job.log
 (1/2) evmctl-tests.py:EvmCtl.test;run-run_type-upstream-37c6: PASS (18.42 s)
 (2/2) evmctl-tests.py:EvmCtl.test;run-run_type-distro-c4a8: PASS (25.78 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-07T12.16-f978bfc/results.html
JOB TIME   : 65.31 s


RHEL:
JOB ID     : a56d28e3bd7857b27e03a99270d8e5906c296dc9
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-07T01.51-a56d28e/job.log
 (1/2) evmctl-tests.py:EvmCtl.test;run-run_type-upstream-37c6: FAIL: 1 test(s) failed, please refer to the log (18.53 s)
 (2/2) evmctl-tests.py:EvmCtl.test;run-run_type-distro-c4a8: FAIL: 1 test(s) failed, please refer to the log (25.50 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-07T01.51-a56d28e/results.html
JOB TIME   : 56.13 s
```

2022-10-18 03:46 UTC, PraveenPenguin approved these changes

2022-10-18 04:04 UTC, Naresh-ibm requested changes

2022-10-18 04:04 UTC, Naresh-ibm commented on security/evmctl-tests.py
> +        run_type = self.params.get('type', default='upstream')
@nasastry please add distro as default parameter

2022-10-18 04:04 UTC, Naresh-ibm commented on security/evmctl-tests.py
> +                           "files/latest/download")
remove the default_url as we are hard coding it in yaml

2022-10-18 09:17 UTC, abdhaleegit approved these changes
LGTM

2022-10-19 07:17 UTC, Naresh-ibm approved these changes
LGTM

2022-10-19 08:36 UTC, abdhaleegit approved these changes
LGTM

2022-10-19 08:51 UTC, merged