selinux-tests.py: add distribution specific test cases
avocado-framework-tests/avocado-misc-tests pull request #2419
Opened 2022-09-26 10:07 UTC by nasastry

Add distribution specific test cases.
With the support of yaml, can run distribution and upstream test cases.

Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>

2022-09-26 10:07 UTC, nasastry commented
```
RHEL:
JOB ID     : 9d2e3e0958848846a2c982b1febefe37e7426ef2
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-26T15.30-9d2e3e0/job.log
 (1/2) selinux-tests.py:SELinux.test;run-run_type-upstream-0113: CANCEL: SELinux tests not supported on SuSE (0.51 s)
 (2/2) selinux-tests.py:SELinux.test;run-run_type-distro-9cc6: CANCEL: SELinux tests not supported on SuSE (0.53 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 2
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-26T15.30-9d2e3e0/results.html
JOB TIME   : 19.78 s


SLES:
JOB ID     : 9d2e3e0958848846a2c982b1febefe37e7426ef2
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-26T15.30-9d2e3e0/job.log
 (1/2) selinux-tests.py:SELinux.test;run-run_type-upstream-0113: CANCEL: SELinux tests not supported on SuSE (0.51 s)
 (2/2) selinux-tests.py:SELinux.test;run-run_type-distro-9cc6: CANCEL: SELinux tests not supported on SuSE (0.53 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 2
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-26T15.30-9d2e3e0/results.html
JOB TIME   : 19.78 s

```

2022-10-12 06:27 UTC, Naresh-ibm requested changes

2022-10-12 06:27 UTC, Naresh-ibm commented on security/selinux-tests.py
> +        run_type = self.params.get('type', default='upstream')
@nasastry change default='distro'

2022-10-12 06:27 UTC, Naresh-ibm commented on security/selinux-tests.py
> +            url = self.params.get('url', default=default_url)
remove def_url variable and change default=None

2022-10-18 11:09 UTC, abdhaleegit approved these changes
LGTM

2022-10-18 14:46 UTC, Naresh-ibm approved these changes
Thanks @abdhaleegit @nasastry 
LGTM

2022-10-18 14:46 UTC, merged