seccomp-tests.py: add distribution specific test cases
avocado-framework-tests/avocado-misc-tests pull request #2423
Opened 2022-09-27 08:43 UTC by nasastry

Add distribution specific test cases.
With the support of yaml, can run distribution and upstream test cases.

Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>

2022-09-27 08:44 UTC, nasastry commented
```
RHEL:
JOB ID     : 0a513f4d1c70ca635946b07728ccad64daa204af
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-27T03.33-0a513f4/job.log
 (1/2) seccomp-tests.py:SecComp.test;run-run_type-upstream-395e:  PASS (160.16 s)
 (2/2) seccomp-tests.py:SecComp.test;run-run_type-distro-94ba:  PASS (116.38 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-27T03.33-0a513f4/results.html
JOB TIME   : 287.64 s

SLES:
JOB ID     : d190872a38f1d7e05ff7814ab4e6599e6d490c3f
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-27T14.01-d190872/job.log
 (1/2) seccomp-tests.py:SecComp.test;run-run_type-upstream-395e:  PASS (128.12 s)
 (2/2) seccomp-tests.py:SecComp.test;run-run_type-distro-94ba:  PASS (346.87 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-27T14.01-d190872/results.html
JOB TIME   : 493.79 s
```

2022-10-07 08:51 UTC, nasastry commented
```
SLES:
JOB ID     : 22e4c756cf761741166373292714f7e23027ff82
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-07T14.09-22e4c75/job.log
 (1/2) seccomp-tests.py:SecComp.test;run-run_type-upstream-395e: PASS (137.83 s)
 (2/2) seccomp-tests.py:SecComp.test;run-run_type-distro-94ba: PASS (391.18 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-07T14.09-22e4c75/results.html
JOB TIME   : 550.98 s

RHEL:
JOB ID     : a1fcb2535f7004e032093f26c477c6bb1968e664
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-10-07T03.42-a1fcb25/job.log
 (1/2) seccomp-tests.py:SecComp.test;run-run_type-upstream-395e: PASS (164.20 s)
 (2/2) seccomp-tests.py:SecComp.test;run-run_type-distro-94ba: PASS (122.68 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-10-07T03.42-a1fcb25/results.html
JOB TIME   : 299.09 s

```

2022-10-12 05:28 UTC, Naresh-ibm requested changes

2022-10-12 05:28 UTC, Naresh-ibm commented on security/seccomp-tests.py
> +        run_type = self.params.get('type', default='upstream')
@nasastry as discussed, change default='distro'

2022-10-12 05:28 UTC, Naresh-ibm commented on security/seccomp-tests.py
> +            url = self.params.get('url', default=def_url)
remove the default_url variable and make `default=None`

2022-10-18 14:42 UTC, Naresh-ibm approved these changes
@nasastry thanks for the PR
@abdhaleegit thanks for Reviews
LGTM

2022-10-18 14:42 UTC, merged