ima-modsig-tests.py: Add IMA modsig test cases
avocado-framework-tests/avocado-misc-tests pull request #2428
Opened 2022-09-28 08:29 UTC by nasastry

Add IMA modsig test cases, to check the required kernel config options and check whether the signing key exists in both ima and builtin_trusted_keys

Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>

2022-09-28 08:29 UTC, nasastry commented
```
RHEL:
JOB ID     : 4c382c7683fbb3c317c5dccc8ce9873e60fd0288
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T03.19-4c382c7/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.80 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T03.19-4c382c7/results.html
JOB TIME   : 11.83 s

SLES:JOB ID     : fb801397b267023b96925598d78f9193678bf3ff
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T13.46-fb80139/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.56 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fat-wrapper/results/job-2022-09-28T13.46-fb80139/results.html
JOB TIME   : 19.54 s
```

2022-09-28 09:00 UTC, nasastry commented
```
RHEL:
JOB ID     : 68cac86eeb222ed482c75794aa1429ca8802e6b4
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T03.58-68cac86/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.86 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T03.58-68cac86/results.html
JOB TIME   : 11.88 s


SLES:
JOB ID     : d363f77d27666ef6fe96b050bce184d5a1fae7ba
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T14.26-d363f77/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.56 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T14.26-d363f77/results.html
JOB TIME   : 19.67 s
```

2022-09-28 09:54 UTC, nasastry commented
```
RHEL:
JOB ID     : 027cf9afbde74798bd1e325053ce06a6add512d2
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T04.52-027cf9a/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.87 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T04.52-027cf9a/results.html
JOB TIME   : 11.94 s

SLES:
JOB ID     : ae59e3a638add11a94c5ac8979f4e05472971290
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T15.20-ae59e3a/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.54 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T15.20-ae59e3a/results.html
JOB TIME   : 19.51 s
```

2022-09-28 10:16 UTC, abdhaleegit approved these changes
LGTM

2022-09-28 10:22 UTC, abdhaleegit commented
@nasastry in line 46 you are decoding rhe output, it must be in utf-8 format   decode(utf-8)

2022-09-28 10:23 UTC, abdhaleegit requested changes
Can you please look into above comment

2022-09-28 13:52 UTC, nasastry commented
@abdhaleegit Done with the requested changes.

```
RHEL:
JOB ID     : d015a38df709dcca46f0f645dbf4c043e45500b3
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T08.49-d015a38/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.80 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T08.49-d015a38/results.html
JOB TIME   : 11.88 s

SLES:
JOB ID     : 82fee4edae7e1ad7df666d5281448b2fb2f53ac4
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2022-09-28T19.16-82fee4e/job.log
 (1/1) ima-modsig-tests.py:IMAmodsig.test: PASS (0.59 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2022-09-28T19.16-82fee4e/results.html
JOB TIME   : 19.58 s
```

2022-09-30 09:43 UTC, abdhaleegit approved these changes
LGTM

2022-09-30 09:54 UTC, PraveenPenguin approved these changes

2022-09-30 09:54 UTC, merged