We don't use mlx5_fpga_tools sub module
avocado-framework-tests/avocado-misc-tests pull request #2439
Opened 2022-10-10 11:05 UTC by PavamanSubramaniyam

mlx_fpga tool allows the user to burn and update a new FPGA image on Mellanox Innova adapter cards

On IBM Power box we don't support Mellanox Innova adapter cards

As per the bug 192581 we don't need to check this module in the testcase

Signed-off-by: Pavaman Subramaniyam <pavsubra@linux.vnet.ibm.com>

2022-10-10 13:02 UTC, Naresh-ibm requested changes

2022-10-10 13:02 UTC, Naresh-ibm commented on io/driver/module_unload_load.py.data/config
> +mlx5_core=mlx5_vdpa mlx5_ib
also please add the run logs and job/debug.log for reference.

2022-10-11 05:51 UTC, PavamanSubramaniyam commented on io/driver/module_unload_load.py.data/config
> +mlx5_core=mlx5_vdpa mlx5_ib
mlx_fpga tool allows the user to burn and update a new FPGA image on Mellanox Innova adapter cards.
On IBM Power box, we don't support Mellanox Innova adapter cards.
As mentioned in the reference bug 192581, developer has mentioned that we don't support these cards.

Also, in the latest kernel and distro releases there is no mlx5_fpga_tools driver sub module loaded when the main mlx5_core module is loaded.

2022-10-11 06:20 UTC, PavamanSubramaniyam commented
I have pasted the results of the execution here after making the changes to the config file.

cat module_unload_load.py.data/config
mlx4_core=mlx4_en mlx4_ib
mlx5_core=mlx5_vdpa mlx5_ib
#mlx5_core=mlx5_fpga_tools mlx5_ib
xhci_hcd=xhci_pci
qla2xxx=multipath
lpfc=multipath
ibmvfc=multipath
nvme_fc=lpfc multipath

cat module_unload_load.py.data/module_unload_load.yaml
Parameters:
    module: "mlx5_core"
    iteration: 1
    only_io: True

avocado run --test-runner runner module_unload_load.py -m module_unload_load.py.data/module_unload_load.yaml
JOB ID     : 2561656b0423cf2ec3a781065e0d0885c2025aa8
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2022-10-11T01.05-2561656/job.log
 (1/1) module_unload_load.py:ModuleLoadUnload.test;run-Parameters-5f46: PASS (113.68 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2022-10-11T01.05-2561656/results.html
JOB TIME   : 129.54 s

2022-10-11 06:26 UTC, Naresh-ibm approved these changes

2022-10-11 06:26 UTC, Naresh-ibm commented on io/driver/module_unload_load.py.data/config
> +mlx5_core=mlx5_vdpa mlx5_ib
Thanks @PavamanSubramaniyam .
LGTM

2022-10-11 06:26 UTC, merged