Bug fix for vnic backing device remove failure and vnic auto failover
avocado-framework-tests/avocado-misc-tests pull request #2440
Opened 2022-10-10 16:22 UTC by vaishnavibhat

Fixing below issues:
- vnic backing device remove failure is seen when auto failover test is run for odd timings. Addressing this issue by setting back the priority
- Setting back original priorities after vnic auto failover which sets the priority to 1 and 100
- Seeting back active interface in teardown after every tests

Signed-off-by: Vaishnavi Bhat <vaishnavi@linux.vnet.ibm.com>

2022-10-10 16:24 UTC, vaishnavibhat commented
avocado run --test-runner runner network_virtualization.py -m network_virtualization.yaml
JOB ID     : 1066ae8569efb24b1997170d27237cd1f0aa96f2
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2022-10-10T11.03-1066ae8/job.log
 (01/11) network_virtualization.py:NetworkVirtualization.test_add;run-f043: PASS (19.26 s)
 (02/11) network_virtualization.py:NetworkVirtualization.test_backingdevadd;run-f043: PASS (16.24 s)
 (03/11) network_virtualization.py:NetworkVirtualization.test_disable_enable_dev;run-f043: FAIL: test failed,check dmesg log in debug log (18.80 s)
 (04/11) network_virtualization.py:NetworkVirtualization.test_hmcfailover;run-f043: PASS (78.59 s)
 (05/11) network_virtualization.py:NetworkVirtualization.test_clientfailover;run-f043: PASS (136.19 s)
 (06/11) network_virtualization.py:NetworkVirtualization.test_vnic_auto_failover;run-f043: PASS (85.77 s)
 (07/11) network_virtualization.py:NetworkVirtualization.test_rmdev_viosfailover;run-f043: PASS (87.28 s)
 (08/11) network_virtualization.py:NetworkVirtualization.test_vnic_dlpar;run-f043: PASS (58.44 s)
 (09/11) network_virtualization.py:NetworkVirtualization.test_vnic_hmc_dlpar;run-f043: PASS (63.28 s)
 (10/11) network_virtualization.py:NetworkVirtualization.test_backingdevremove;run-f043: PASS (11.28 s)
 (11/11) network_virtualization.py:NetworkVirtualization.test_remove;run-f043: PASS (16.38 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2022-10-10T11.03-1066ae8/results.html
JOB TIME   : 599.16 s

[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/9747544/job.log)

2022-10-10 16:45 UTC, Naresh-ibm commented on io/net/virt-net/network_virtualization.py
> +        '''
docstring, same here

2022-10-14 05:36 UTC, Naresh-ibm requested changes

2022-10-14 05:36 UTC, Naresh-ibm commented on io/net/virt-net/network_virtualization.py
> +        '''
@vaishnavibhat you missed the docstrig part here.

2022-10-14 05:36 UTC, Naresh-ibm commented on io/net/virt-net/network_virtualization.py
> +        :param slot: vnic slot
please maintain the proper line spaces here after desciption

2022-10-14 05:36 UTC, Naresh-ibm commented on io/net/virt-net/network_virtualization.py
> +        :param slot: vnic slot
proper line spaces after description

2022-10-17 06:04 UTC, Naresh-ibm approved these changes
@vaishnavibhat thank you for adding the changes suggest.
LGTM

2022-10-17 14:55 UTC, abdhaleegit requested changes
@vaishnavibhat cant calling update_backing_device() function inside est_backingdevremove(self): ? will not solve this problem.. https://github.com/avocado-framework-tests/avocado-misc-tests/blob/af4918570d998f7d7db87e704edf334251d68f5a/io/net/virt-net/network_virtualization.py#L777

instead of new function

2022-10-18 05:40 UTC, vaishnavibhat commented
> @vaishnavibhat cant calling update_backing_device() function inside test_backingdevremove(self): ? will not solve this problem..
> 
> https://github.com/avocado-framework-tests/avocado-misc-tests/blob/af4918570d998f7d7db87e704edf334251d68f5a/io/net/virt-net/network_virtualization.py#L777
> 
> instead of new function

update_backing_devices() will update the information of the active device only. The function has does not record the latest priority of the active and backing device. 
  Also , if some other tests changes the priority to a different value apart from the ones mentioned by user in yaml file, this function fails to set it to original values. Hence the backing device and original device are not set like to original devices.

2022-11-08 13:13 UTC, vaishnavibhat commented
Resent the PR with requested changes. 

In test 1 (test_remove) and test 11 (test_remove), The tests will PASS but the logs will report ' Unable to set back the original active device' in the debug.log since there is only single backing device. 
Rest of the tests will either report 'Unable to set back the original active device' if failed to set back, or a success if the backing device is set back to original. 

Thank you.

2022-11-10 15:37 UTC, abdhaleegit approved these changes
LGTM

2022-11-10 15:45 UTC, merged