add_dawr_test
avocado-framework-tests/avocado-misc-tests pull request #2479
Opened 2022-11-17 06:40 UTC by akanksha216

Reading single dawr register with gdb interface

Signed-off-by: Akanksha J N <akanksha@linux.ibm.com>

avocado run --test-runner runner dawr.py
JOB ID     : 3e89a23cf9965dbbc666a23ac32a7a55def2f58f
JOB LOG    : /root/ak/avocado-fvt-wrapper/results/job-2022-11-16T23.27-3e89a23/job.log
 (1/1) dawr.py:Dawr.test_wp1: PASS (2.11 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/ak/avocado-fvt-wrapper/results/job-2022-11-16T23.27-3e89a23/results.html
JOB TIME   : 31.97 s
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/10028644/job.log)

2022-11-17 06:52 UTC, Naresh-ibm requested changes

2022-11-17 06:52 UTC, Naresh-ibm commented on trace/dawr.py
> +import platform
@akanksha216 this is not used any where. you can remove it.

2022-11-17 06:52 UTC, Naresh-ibm commented on trace/dawr.py
> +from avocado.utils import build, distro, process
similarly process is also not used. 
remove them

2022-11-17 07:02 UTC, Naresh-ibm commented
@akanksha216 please give the detailed description about test case in commit message.
like what each file is trying to do here

2022-11-17 08:23 UTC, PraveenPenguin commented
@akanksha216 have perf also included in this please , we will try to resolve perf report issue

2022-11-18 09:10 UTC, Naresh-ibm commented on trace/dawr.py
> +        #Running gdb
Please have a proper docstrings for all the methods

2022-11-18 09:12 UTC, Naresh-ibm requested changes

2022-11-18 09:12 UTC, Naresh-ibm commented on trace/dawr.py
> +
please add licensing and author related info.

2022-11-21 06:15 UTC, abdhaleegit requested changes

2022-11-21 06:15 UTC, abdhaleegit commented on trace/dawr.py
> +    def test_wp1(self):
a meaning full name would be good

2022-11-21 06:15 UTC, abdhaleegit commented on trace/dawr.py
> +        return_value.append(child.expect_exact(['exited normally',pexpect.TIMEOUT]))
@akanksha216 see if it is possible to optimized similar code lines in a loop

for all values in a list[] :
     return_value.append(child.expect_exact(['New value = ',pexpect.TIMEOUT]))
        child.sendline('c')

2022-11-21 08:08 UTC, Naresh-ibm commented on trace/dawr.py
> +        values= [pexpect.TIMEOUT,'Value = 10','New value = 20','Value = 10','New value = 20','Value = 20','Value = 20']
Please take care of pep8 and pylint errors

2022-11-21 08:08 UTC, Naresh-ibm commented on trace/dawr.py
> +        Setting Read/Write watchpoints on three variables using awatch and
is this awatch only?
as I could see in all method descriptions

2022-11-23 04:41 UTC, PraveenPenguin commented
@abdhaleegit review please

2022-11-24 08:35 UTC, abdhaleegit commented on trace/dawr.py
> +        Setting Read/Write watchpoint on single variable using awatch and
I think awatch is actual name of the program

2022-11-24 09:26 UTC, Naresh-ibm commented
@akanksha216 
I could see following pep8 errors,

```
test.py:14:53: W291 trailing whitespace
test.py:26:1: E302 expected 2 blank lines, found 1
test.py:33:50: W291 trailing whitespace
test.py:39:30: E231 missing whitespace after ','
test.py:60:14: E225 missing whitespace around operator
test.py:60:40: E231 missing whitespace after ','
test.py:64:21: E225 missing whitespace around operator
test.py:67:33: E231 missing whitespace after ','
test.py:69:61: E231 missing whitespace after ','
test.py:71:65: E231 missing whitespace after ','
test.py:71:80: E501 line too long (83 > 79 characters)
test.py:74:17: E225 missing whitespace around operator
test.py:82:14: E225 missing whitespace around operator
test.py:82:40: E231 missing whitespace after ','
test.py:86:21: E225 missing whitespace around operator
test.py:88:64: E231 missing whitespace after ','
test.py:88:80: E501 line too long (82 > 79 characters)
test.py:91:64: E231 missing whitespace after ','
test.py:91:80: E501 line too long (82 > 79 characters)
test.py:94:15: E225 missing whitespace around operator
test.py:94:33: E231 missing whitespace after ','
test.py:94:46: E231 missing whitespace after ','
test.py:94:63: E231 missing whitespace after ','
test.py:95:17: E128 continuation line under-indented for visual indent
test.py:95:33: E231 missing whitespace after ','
test.py:95:46: E231 missing whitespace after ','
test.py:97:68: E231 missing whitespace after ','
test.py:99:64: E231 missing whitespace after ','
test.py:99:80: E501 line too long (84 > 79 characters)
test.py:101:17: E225 missing whitespace around operator
test.py:106:75: W291 trailing whitespace
test.py:109:14: E225 missing whitespace around operator
test.py:109:40: E231 missing whitespace after ','
test.py:113:21: E225 missing whitespace around operator
test.py:116:33: E231 missing whitespace after ','
test.py:119:33: E231 missing whitespace after ','
test.py:122:33: E231 missing whitespace after ','
test.py:124:80: E501 line too long (81 > 79 characters)
test.py:125:36: E231 missing whitespace after ','
test.py:127:17: E225 missing whitespace around operator

```

2022-11-24 09:26 UTC, Naresh-ibm requested changes
Please re-check on pep8 errors

2022-11-25 09:43 UTC, Naresh-ibm commented
@akanksha216 Thanks for incorporating the changes.
LGTM

2022-11-25 10:42 UTC, abdhaleegit approved these changes
LGTM

2022-11-25 11:03 UTC, PraveenPenguin requested changes

2022-11-25 11:03 UTC, PraveenPenguin commented on trace/dawr.py
> +        return_value.append(child.expect_exact(['Hardware access (read/write) \
same for loop can be applied here

2022-11-25 11:03 UTC, PraveenPenguin commented on trace/dawr.py
> +        self.temp_file = tempfile.NamedTemporaryFile().name
I see this is not used anywhere, please remove and import as well

2022-11-28 06:14 UTC, sacsant commented on trace/dawr.py
> +        shutil.copyfile(self.get_data('wp1.c'),
add a loop for copyfile to iterate over source files

2022-11-28 06:14 UTC, sacsant commented on trace/dawr.py
> +        child.sendline('awatch a')
Initial few lines are common across 3 tests. May be move them to a common function??

2022-12-01 06:38 UTC, akanksha216 commented on trace/dawr.py
> +        time.sleep(0.3)
sleep is required here as it takes some time to enter the gdb prompt

2022-12-01 06:41 UTC, akanksha216 commented
I have addressed the above comments

2022-12-02 02:54 UTC, PraveenPenguin commented
@akanksha216 can you please delete unused files from PR like do git rm wp1.c ..so on ,

2022-12-11 10:17 UTC, sacsant approved these changes
LGTM. 

Not sure if it's a must but can we add the licence related prolog to the c files as well? @PraveenPenguin

2022-12-15 06:26 UTC, PraveenPenguin approved these changes

2022-12-15 06:26 UTC, merged