rawread.c: Add support of long disk device names
avocado-framework-tests/avocado-misc-tests pull request #2582
Opened 2023-03-15 10:13 UTC by abdhaleegit

The current code in rawread.tar fails on disk names which has lengthy path like

$ ./rawread -t 1 /dev/disk/by-id/scsi-360050768108001b3a8000000000000d0
/dev/disk/by-id/scsi-3600507681
open failed on device: No such file or directory

have modified rawread.c buffer size to allow long device names

2023-03-15 10:16 UTC, abdhaleegit commented
Before fix:
```
./rawread -t 1 /dev/disk/by-id/scsi-360050768108001b3a8000000000000d0
/dev/disk/by-id/scsi-3600507681
open failed on device: No such file or directory
^C

```

After fix:
```
./rawread -t 1 /dev/disk/by-id/scsi-360050768108001b3a8000000000000d0
              rawread 2.4.1.2
-t 1          sequential write() test
-p 1          number of processes
-s 262144     read buffer or readv size in bytes
-n 1024       inner loop count
-l 1          outer loop count
-r 1023       range in MB
-o 0          is seek offset

   262144     length of DASD read (kbytes)
   262144     minimum kbytes read by each process

   0.19       %user
   2.60       %sys
   97.21      %idle

procs           device    num read   KB/sec     I/O Ops/sec
-----  ---------------  ----------  -------  --------------
    1  /dev/disk/by-id/scsi-360050768108001b3a8000000000000d0        1024  19538197           76321 
-----  ---------------  ----------  -------  --------------
    1                         1024  19538197           76321 

Total run time 0.013417 seconds
```
works also for short names
----------------------------
```
 ./rawread -t 1 /dev/mapper/mpathd
              rawread 2.4.1.2
-t 1          sequential write() test
-p 1          number of processes
-s 262144     read buffer or readv size in bytes
-n 1024       inner loop count
-l 1          outer loop count
-r 1023       range in MB
-o 0          is seek offset

   262144     length of DASD read (kbytes)
   262144     minimum kbytes read by each process

   0.00       %user
   0.00       %sys
   100.00     %idle

procs           device    num read   KB/sec     I/O Ops/sec
-----  ---------------  ----------  -------  --------------
    1  /dev/mapper/mpathd        1024  1988017            7765 
-----  ---------------  ----------  -------  --------------
    1                         1024  1988017            7765 

Total run time 0.131862 seconds
```

2023-03-15 10:29 UTC, Naresh-ibm approved these changes
LGTM

2023-03-15 10:32 UTC, abdhaleegit commented
logs
```
avocado run --max-parallel-tasks=1 rawread.py  -m rawread.py.data/rawread.yaml 
JOB ID     : 62f712782a9db24f02968763c398f19796c7f57e
JOB LOG    : /home/ioci/logs/io_fc/results/job-2023-03-15T15.53-62f7127/job.log
 (1/1) rawread.py:Rawread.test;run-0914: STARTED
 (1/1) rawread.py:Rawread.test;run-0914: PASS (420.85 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/ioci/logs/io_fc/results/job-2023-03-15T15.53-62f7127/results.html
JOB TIME   : 448.21 s

2023-03-16 06:06 UTC, sacsant reviewed
Do we also need to change value for device_name[]

 470                 if (count) {
 471                         char device_name[30];
 472                         total_count += count;

This is passed to get_device_name() which uses strcpy(device_name, devices)

2023-03-16 17:02 UTC, abdhaleegit commented
> Do we also need to change value for device_name[]
> 
> 470 if (count) { 471 char device_name[30]; 472 total_count += count;
> 
> This is passed to get_device_name() which uses strcpy(device_name, devices)

Yeap, that was my first try device_name[100] but it did not solve the problem. so I have to increase memory allocation

2023-03-17 05:55 UTC, sacsant commented
> > Do we also need to change value for device_name[]
> > 470 if (count) { 471 char device_name[30]; 472 total_count += count;
> > This is passed to get_device_name() which uses strcpy(device_name, devices)
> 
> Yeap, that was my first try device_name[100] but it did not solve the problem. just increase memory allocation worked though 944 devices[j] = (char*)malloc(255 * sizeof(char));
> 

I think we need to increase the size of device_name also to match devices. Otherwise it may cause memory buffer overflow. Rest of the changes lgtm

2023-03-17 12:48 UTC, abdhaleegit commented
Retest post new changes
```
./rawread -t 1 /dev/mapper/mpathf
              rawread 2.4.1.2
-t 1          sequential write() test
-p 1          number of processes
-s 262144     read buffer or readv size in bytes
-n 1024       inner loop count
-l 1          outer loop count
-r 1023       range in MB
-o 0          is seek offset

   262144     length of DASD read (kbytes)
   262144     minimum kbytes read by each process

   0.00       %user
   0.00       %sys
   100.00     %idle

procs           device    num read   KB/sec     I/O Ops/sec
-----  ---------------  ----------  -------  --------------
    1  /dev/mapper/mpathf        1024   876337            3423 
-----  ---------------  ----------  -------  --------------
    1                         1024   876337            3423 

Total run time 0.299136 seconds
```
```
./rawread -t 1 /dev/disk/by-id/dm-uuid-part3-mpath-360050768108001b3a8000000000000c7
              rawread 2.4.1.2
-t 1          sequential write() test
-p 1          number of processes
-s 262144     read buffer or readv size in bytes
-n 1024       inner loop count
-l 1          outer loop count
-r 1023       range in MB
-o 0          is seek offset

   262144     length of DASD read (kbytes)
   262144     minimum kbytes read by each process

   0.03       %user
   0.03       %sys
   99.94      %idle

procs           device    num read   KB/sec     I/O Ops/sec
-----  ---------------  ----------  -------  --------------
    1  /dev/disk/by-id/dm-uuid-part3-mpath-360050768108001b3a8000000000000c7        1024   831018            3246 
-----  ---------------  ----------  -------  --------------
    1                         1024   831018            3246 

Total run time 0.315449 seconds
```

2023-03-17 13:29 UTC, sacsant requested changes
Any reason to use different values for size (100 and 128). Either use 128 or 100 in both the instances.

100 kept as device_name array size
128 was to allocate memory buffer ( so mutliple of 32) .. but having 100 still works though.  will change it

2023-03-20 06:13 UTC, sacsant approved these changes
Thanks. Looks good.

2023-03-20 07:24 UTC, PraveenPenguin approved these changes

2023-03-20 07:24 UTC, merged