README: Add README.md for eatmemory test
avocado-framework-tests/avocado-misc-tests pull request #2599
Opened 2023-04-07 10:03 UTC by Geet2

Add README.md for memory/eatmemory.py test

2023-04-07 11:15 UTC, Naresh-ibm requested changes

2023-04-07 11:15 UTC, Naresh-ibm commented on memory/eatmemory.py.data/README.md
> +* By default memory to test is 95% of the system's free memory. If you want to change that you can change the memory_to_test parameter in the yaml file.
@Geet2 Please add the yaml parameter here and add the description for them too. like what different values we can pass to this parameter and any other conditions one should be aware off, while passing the value for the parameter.

2023-04-09 06:22 UTC, Naresh-ibm approved these changes
@Geet2 LGTM
Thanks for the changes and PR

2023-04-09 06:23 UTC, Naresh-ibm commented
@PraveenPenguin Please ACK, so that I can merge this PR

2023-04-10 05:48 UTC, PraveenPenguin approved these changes
LGTM

2023-04-10 06:00 UTC, Naresh-ibm reviewed
@Geet2 Thanks for PR,
@PraveenPenguin Thanks for review.

2023-04-10 06:00 UTC, merged