Use '-t' option in log_repair_action only for Servicelog v0.2.9
avocado-framework-tests/avocado-misc-tests pull request #2611
Opened 2023-04-18 10:25 UTC by seeteena

'-t' option in log_repair_action is deprecated.

Loc code is sufficient for device lookup with v1 API. However, needs to be retained for v0.2.9 for backward compatibility.

Also, Fix code style warnings reported by pycodestyle.

2023-04-18 10:30 UTC, seeteena commented
More details - 

```

log_repair_action -h
Usage: log_repair_action -l <location> -p <procedure> {optional_flags}
    -l: location code of the device that was repaired
    -p: repair procedure that was followed
  Optional Flags:
    -d: date/time that the procedure was performed
        (defaults to current date/time if not specified)
    -n: include a note with the repair action
        (useful for indicating who performed the repair)
    -q: quiet mode (log the repair action without prompting
        for confirmation)
    -t: type of event this repair action is for (deprecated)
    -V: print the version of the command and exit
    -h: print this help text and exit
```

.....................

```
log_repair_action.c

case 't':	/* type - Added for backwards v29 compatibility */
			/* Not actually used.  Loc code is sufficient for device lookup with v1 API */
//			if ((rc = valid_type(optarg)) == -1) {
//				fprintf(stderr, "%s: Valid types are: os, "
//					"ppc64_rtas, or ppc64_encl\n", argv[0]);
//				print_usage(argv[0]);
//				return 1;
//			}
//			type = strdup(optarg);
			break;

debug.log (with Version 0.2.9)
```
```

[stdlog] 2023-04-13 03:24:14,263 avocado.test INFO | ===========3 - Introducing the repair action =========
[stdlog] 2023-04-13 03:24:14,263 avocado.utils.process INFO | Running 'servicelog --version | grep Version |  awk '{print $NF}''
[stdlog] 2023-04-13 03:24:14,265 avocado.utils.process DEBUG| [stdout] servicelog: Version 0.2.9
[stdlog] 2023-04-13 03:24:14,265 avocado.utils.process INFO | Command 'servicelog --version | grep Version |  awk '{print $NF}'' finished with 0 after 0.000966537s
[stdlog] 2023-04-13 03:24:14,266 avocado.utils.process INFO | Running 'log_repair_action -q -t ppc64_ras -l U787E.001.0458891'
[stdlog] 2023-04-13 03:24:14,268 avocado.utils.process DEBUG| [stderr] log_repair_action: A procedure was not specified. Defaulting to ''
[stdlog] 2023-04-13 03:24:14,291 avocado.utils.process INFO | Command 'log_repair_action -q -t ppc64_ras -l U787E.001.0458891' finished with 0 after 0.024551165s
[stdlog] 2023-04-13 03:24:14,291 avocado.test INFO | ===========4 - Checking servicelog after the repair action =========
...........................................
```

debug.log (with 1.1.16)

```
[stdlog] 2023-04-13 03:28:43,360 avocado.test INFO | ===========3 - Introducing the repair action =========
[stdlog] 2023-04-13 03:28:43,360 avocado.utils.process INFO | Running 'servicelog --version | grep Version |  awk '{print $NF}''
[stdlog] 2023-04-13 03:28:43,362 avocado.utils.process DEBUG| [stdout] servicelog: Version 1.1.16
[stdlog] 2023-04-13 03:28:43,362 avocado.utils.process INFO | Command 'servicelog --version | grep Version |  awk '{print $NF}'' finished with 0 after 0.000931547s
[stdlog] 2023-04-13 03:28:43,363 avocado.utils.process INFO | Running 'log_repair_action -q -l U787E.001.0458891'
[stdlog] 2023-04-13 03:28:43,370 avocado.utils.process DEBUG| [stderr] log_repair_action: A procedure was not specified. Defaulting to ''
[stdlog] 2023-04-13 03:28:43,392 avocado.utils.process INFO | Command 'log_repair_action -q -l U787E.001.0458891' finished with 0 after 0.028275938s
[stdlog] 2023-04-13 03:28:43,392 avocado.test INFO | ===========4 - Checking servicelog after the repair action =========
.
```

pycodestyle servicelog.py
no warnings.

2023-04-19 03:01 UTC, PraveenPenguin commented on ras/servicelog.py
> +                               "| sed 's/^ *//'" % notify_script)
these changes seems not relevant , can you please squash these

2023-04-19 03:01 UTC, PraveenPenguin commented on ras/servicelog.py
> +                                    "sed 's/^ *//'")
here as well

2023-04-19 03:01 UTC, PraveenPenguin commented on ras/servicelog.py
> +                                            "grep \"Repair Action\" | "
same here

2023-05-02 06:03 UTC, abdhaleegit requested changes

2023-05-02 06:03 UTC, abdhaleegit commented on ras/servicelog.py
> +        cmd = "servicelog --version | grep Version |  awk '{print $NF}'"
a better way to handle any command output is to avoid shell pipe

2023-05-09 11:03 UTC, seeteena commented
debug.log with 1.1.15 servicelog

06:37:52 INFO | ===========3 - Introducing the repair action =========
06:37:52 INFO | Running 'servicelog --version'
06:37:52 DEBUG| [stdout] servicelog: Version 1.1.15
06:37:52 INFO | Command 'servicelog --version' finished with 0 after 0.0013320446014404297s
06:37:52 INFO | Running 'log_repair_action -q -l U787E.001.0458891'
06:37:52 DEBUG| [stderr] log_repair_action: A procedure was not specified. Defaulting to ''
06:37:52 INFO | Command 'log_repair_action -q -l U787E.001.0458891' finished with 0 after 0.003952980041503906s
06:37:52 INFO | ===========4 - Checking servicelog after the repair action =========

debug log with 0.2.9 servicelog

06:46:56 INFO | ===========3 - Introducing the repair action =========
06:46:56 INFO | Running 'servicelog --version'
06:46:56 DEBUG| [stdout] servicelog: Version 0.2.9
06:46:56 INFO | Command 'servicelog --version' finished with 0 after 0.0013666152954101562s
06:46:56 INFO | Running 'log_repair_action -q -t ppc64_ras -l U787E.001.0458891'
06:46:56 DEBUG| [stderr] log_repair_action: A procedure was not specified. Defaulting to ''
06:46:56 INFO | Command 'log_repair_action -q -t ppc64_ras -l U787E.001.0458891' finished with 0 after 0.004759073257446289s
06:46:56 INFO | ===========4 - Checking servicelog after the repair action =========

2023-06-08 07:56 UTC, PraveenPenguin approved these changes

2023-06-13 14:34 UTC, abdhaleegit requested changes

2023-06-13 14:34 UTC, abdhaleegit commented on ras/servicelog.py
> +        cmd = "servicelog --version | grep Version |  awk '{print $NF}'"
Do not use shell pipe to parse the output, instead use python code

2023-08-14 11:49 UTC, seeteena commented
for Servicelog version - 1.1.16
```
servicelog: Version 1.1.16
/home/OpTest/avocado-fvt-wrapper/results/job-2023-08-14T16.56-499ad57
[stdlog] 2023-08-14 16:58:31,007 avocado.test INFO | ===========3 - Introducing the repair action =========
[stdlog] 2023-08-14 16:58:31,007 avocado.utils.process INFO | Running 'servicelog --version | grep Version |  awk '{print $NF}''
[stdlog] 2023-08-14 16:58:31,009 avocado.utils.process DEBUG| [stdout] servicelog: Version 1.1.16
[stdlog] 2023-08-14 16:58:31,009 avocado.utils.process INFO | Command 'servicelog --version | grep Version |  awk '{print $NF}'' finished with 0 after 0.000834939s
[stdlog] 2023-08-14 16:58:31,009 avocado.utils.process INFO | Running 'log_repair_action -q -l U787E.001.0458891'
[stdlog] 2023-08-14 16:58:31,011 avocado.utils.process DEBUG| [stderr] log_repair_action: A procedure was not specified. Defaulting to ''
[stdlog] 2023-08-14 16:58:31,013 avocado.utils.process INFO | Command 'log_repair_action -q -l U787E.001.0458891' finished with 0 after 0.002707515s
[stdlog] 2023-08-14 16:58:31,013 avocado.test INFO | ===========4 - Checking servicelog after the repair action ========= (
```

2023-08-14 11:52 UTC, abdhaleegit approved these changes
I will merge this PR to not block the unsupported option so the test should run fine,  and shell pipe command take this as next pr

2023-08-14 11:52 UTC, abdhaleegit commented
@seeteena Thanks for the PR

2023-08-14 11:52 UTC, merged