Added SMT, CPU workload support for different components(Ex: DLPAR)
avocado-framework-tests/avocado-misc-tests pull request #2618
Opened 2023-04-28 20:24 UTC by SamirMulani

1. Added new test cases to run SMT workload as a daemon process.
2. Added new test cases to run CPU workload as a daemon process.

2023-04-28 20:30 UTC, SamirMulani commented
Run Logs,
```
# avocado run smt.py:smt.test_smt_start
JOB ID     : bd03c448069d803f587109bfe4d9c80db4e5f476
JOB LOG    : /Workspace/avocado-fvt-wrapper/results/job-2023-04-28T15.11-bd03c44/job.log
 (1/1) smt.py:smt.test_smt_start: STARTED
 (1/1) smt.py:smt.test_smt_start: PASS (0.41 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /Workspace/avocado-fvt-wrapper/results/job-2023-04-28T15.11-bd03c44/results.html
JOB TIME   : 8.38 s
# avocado run smt.py:smt.test_smt_stop
JOB ID     : d4f8ca2cf8648fbb955cd625fb354558aeaeb0b6
JOB LOG    : /Workspace/avocado-fvt-wrapper/results/job-2023-04-28T15.11-d4f8ca2/job.log
 (1/1) smt.py:smt.test_smt_stop: STARTED
 (1/1) smt.py:smt.test_smt_stop: PASS (0.53 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /Workspace/avocado-fvt-wrapper/results/job-2023-04-28T15.11-d4f8ca2/results.html
JOB TIME   : 11.59 s


# avocado run cpu_fold.py:cpu_workload.test_cpu_start
JOB ID     : c4143160c97eaf2e7377f9e0a89a365079f1ce70
JOB LOG    : /Workspace/avocado-fvt-wrapper/results/job-2023-04-28T15.12-c414316/job.log
 (1/1) cpu_fold.py:cpu_workload.test_cpu_start: STARTED
 (1/1) cpu_fold.py:cpu_workload.test_cpu_start: PASS (0.42 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /Workspace/avocado-fvt-wrapper/results/job-2023-04-28T15.12-c414316/results.html
JOB TIME   : 8.59 s
# avocado run cpu_fold.py:cpu_workload.test_cpu_stop
JOB ID     : 9c8ea6b68e098d41a11fdc706727a8ebba7b4d56
JOB LOG    : /Workspace/avocado-fvt-wrapper/results/job-2023-04-28T15.13-9c8ea6b/job.log
 (1/1) cpu_fold.py:cpu_workload.test_cpu_stop: STARTED
 (1/1) cpu_fold.py:cpu_workload.test_cpu_stop: PASS (0.54 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /Workspace/avocado-fvt-wrapper/results/job-2023-04-28T15.13-9c8ea6b/results.html
JOB TIME   : 8.62 s
```

2023-05-02 14:43 UTC, abdhaleegit commented on workload/cpu_fold.py.data/cpu.sh
> +ppc64_cpu --offline-cores=10,11,13,15
@Geet2 @SamirMulani the .sh itself can get you the number of procs by using this command

`nproc`

```
[abdul@abdul ]$ nproc
16
```

2023-05-03 06:26 UTC, SamirMulani commented on workload/cpu_fold.py.data/cpu.sh
> +ppc64_cpu --offline-cores=10,11,13,15
Yes @abdhaleegit I have implemented it with the help of **nproc** Linux command.

2023-05-05 04:39 UTC, PraveenPenguin requested changes
@SamirMulani please address the style comment (same will be applicable to smt workload as well ) and add a check if the test is not running on PowerPC it should be canceled

2023-05-05 04:39 UTC, PraveenPenguin commented on workload/cpu_fold.py
> +        self.cwd = os.getcwd()
can we eliminate using extra variables?

2023-05-05 04:39 UTC, PraveenPenguin commented on workload/cpu_fold.py
> +        self.smt_workload = self.cwd + "/" + \
please have variable scope as local , even rename it logical name as this for cpu_folding

2023-05-05 04:39 UTC, PraveenPenguin commented on workload/cpu_fold.py
> +        self.cmd = "bash " + self.smt_workload
can we eliminate this variable as well

2023-05-05 04:39 UTC, PraveenPenguin commented on workload/cpu_fold.py.data/cpu.sh
> +set -x
why set -x , for debug? can we remove this

2023-05-05 09:26 UTC, PraveenPenguin approved these changes

2023-05-11 04:08 UTC, merged