Added support for EM:Extended test case scenario.
avocado-framework-tests/avocado-misc-tests pull request #2624
Opened 2023-05-04 10:50 UTC by SamirMulani

1. Added code changes to run the test_idlestate_mode function for a specific period of time as per the time input is given into the .yaml file. 
2. Checking dmesg for errors every 1/4 of the total runtime.
3. Added new .yaml file to get runtime parameter.
Note: The time unit is in second

2023-05-04 10:50 UTC, SamirMulani commented
Run Logs,
```
 avocado run cpupower_monitor.py:CpupowerMonitor.test_dis_ena_idlestate -m cpupower_monitor.py.data/cpupower.yaml --max-parallel-tasks=1
JOB ID     : 471c187c23a00f2313dd6cadbdcd3b718e913c1d
JOB LOG    : /Workspace/avocado-fvt-wrapper/results/job-2023-05-04T05.20-471c187/job.log
 (1/1) cpupower_monitor.py:CpupowerMonitor.test_dis_ena_idlestate;run-3f91: STARTED
 (1/1) cpupower_monitor.py:CpupowerMonitor.test_dis_ena_idlestate;run-3f91: PASS (104.22 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /Workspace/avocado-fvt-wrapper/results/job-2023-05-04T05.20-471c187/results.html
JOB TIME   : 113.00 s
```

2023-05-05 04:28 UTC, PraveenPenguin requested changes

2023-05-05 04:28 UTC, PraveenPenguin commented on cpu/cpupower_monitor.py
> +    def test_dis_ena_idlestate(self):
can you please change this to some meaningful name

2023-05-05 04:28 UTC, PraveenPenguin commented on cpu/cpupower_monitor.py
> +                shell=True).split()
i feel not relevant with change commit , can you please remove this and other places where it has style changes

2023-05-05 04:28 UTC, PraveenPenguin commented on cpu/cpupower.yaml
> +runtime: 15
what is unit of run time ?

2023-05-05 06:34 UTC, SamirMulani commented on cpu/cpupower.yaml
> +runtime: 15
runtime unit is in second.

2023-05-15 09:19 UTC, merged

2023-06-27 04:34 UTC, sacsant commented
We should make it mandatory to provide supporting logs which shows that introducing a new option in Yaml does not break existing code. This commit introduced a function name change but failed to update the same in places where the function was called.