Handle Attribute not found error in teardown
avocado-framework-tests/avocado-misc-tests pull request #2642
Opened 2023-05-18 11:05 UTC by AYUSHJAIN951

self.raid when not defined, ignoring in teardown and exiting testcase.

Before:
(07/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-1.2-raidlevel-raid0-raidname-spare_disks-bf42: STARTED
(07/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-1.2-raidlevel-raid0-raidname-spare_disks-bf42: PASS (0.63 s)
(08/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-0.9-raidlevel-raid1-raidname-spare_disks-88e8: STARTED
(08/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-0.9-raidlevel-raid1-raidname-spare_disks-88e8: ERROR: 'SoftwareRaid' object has no attribute 'sraid' (0.48 s)

After:
(07/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-1.2-raidlevel-raid0-raidname-spare_disks-bf42: STARTED
(07/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-1.2-raidlevel-raid0-raidname-spare_disks-bf42: PASS (0.63 s)
(08/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-0.9-raidlevel-raid1-raidname-spare_disks-88e8: STARTED
(08/23) softwareraid.py:SoftwareRaid.test;run-metadata-superblock-0.9-raidlevel-raid1-raidname-spare_disks-88e8: CANCEL: Minimum 2 disks required for 1 (0.49 s)

2023-05-18 12:07 UTC, Naresh-ibm commented
@AYUSHJAIN951 Please run the full test and attach the debug.log with different scenarios,
like  with 1, 2, 3 and 4 disks

2023-05-19 06:26 UTC, narasimhan-v approved these changes

2023-05-19 07:07 UTC, Naresh-ibm requested changes
@AYUSHJAIN951 Please run the full test and attach the logs for reference with scenarios mentioned above

2023-05-19 09:08 UTC, AYUSHJAIN951 commented
[software_raid.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/11515368/software_raid.log)
@Naresh-ibm  Attaching the logs here for reference

2023-05-19 09:47 UTC, Naresh-ibm approved these changes
@AYUSHJAIN951 Thanks for update.
@narasimhan-v Thanks for reviewing the PR
LGTM

2023-05-19 09:47 UTC, merged