htx, multiport: add support for mac base input
avocado-framework-tests/avocado-misc-tests pull request #2680
Opened 2023-07-18 18:05 UTC by abdhaleegit

In a contineous test environement setups where device names are not persistent accross os install, having a unique key like mac addr as yaml input which does not change across reboots, dlpar or os install with different linux flavours, also the legacy interface name still works.

2023-07-18 18:05 UTC, abdhaleegit commented
Test Htx NIC:

interface: "env3"
```
avocado run --max-parallel-tasks=1 htx_nic_devices.py --mux-yaml htx_nic_devices.py.data/htx_nic_devices.yaml
JOB ID     : 51b866a10098265026cf54887a66c9635076b99e
JOB LOG    : /root/sandbox/avocado-fvt-wrapper/results/job-2023-07-18T12.34-51b866a/job.log
 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-b275: STARTED
 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-b275: PASS (472.71 s)
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-b275: STARTED
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-b275: PASS (124.04 s)
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-b275: STARTED
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-b275: PASS (11.08 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/sandbox/avocado-fvt-wrapper/results/job-2023-07-18T12.34-51b866a/results.html
JOB TIME   : 611.16 s
```
interface: "02:5d:c7:xx:xx:03"
```
avocado run --max-parallel-tasks=1 htx_nic_devices.py --mux-yaml htx_nic_devices.py.data/htx_nic_devices.yaml
JOB ID     : 80a00ef379f0912b79b270190266617c7b9645fe
JOB LOG    : /root/sandbox/avocado-fvt-wrapper/results/job-2023-07-18T12.49-80a00ef/job.log
 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-659f: STARTED
 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-659f: PASS (461.94 s)
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-659f: STARTED
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-659f: PASS (123.92 s)
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-659f: STARTED
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-659f: PASS (13.12 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/sandbox/avocado-fvt-wrapper/results/job-2023-07-18T12.49-80a00ef/results.html
JOB TIME   : 601.28 s
```

2023-07-24 05:42 UTC, FarooqAbdulla02 commented
LGTM

2023-07-27 14:42 UTC, vaishnavibhat requested changes
Hi Abdul , 

Most of the tests are having ERROR status when wrong interface /  mac address is given for interface parm in yaml file. 
Can this be rectified to show the status with CANCEL with the right message ? 

avocado run multicast_orig.py -m multicast.yaml 
JOB ID     : 81839ecbc8be0e244c3ece97312b49e627b0a5cd
JOB LOG    : /root/new/avocado-fvt-wrapper/results/job-2023-07-27T09.59-81839ec/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/local/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) multicast_orig.py:ReceiveMulticastTest.test_multicast;run-Parameters-hbond-4823: STARTED
 (1/1) multicast_orig.py:ReceiveMulticastTest.test_multicast;run-Parameters-hbond-4823: ERROR: 'ReceiveMulticastTest' object has no attribute 'session' (0.01 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/new/avocado-fvt-wrapper/results/job-2023-07-27T09.59-81839ec/results.html
JOB TIME   : 1.73 s

Test summary:
multicast_orig.py:ReceiveMulticastTest.test_multicast;run-Parameters-hbond-4823: ERROR

2023-07-31 07:26 UTC, abdhaleegit commented
@vaishnavibhat this PR does not have multicast test, did you tested with this PR ?

2023-08-28 04:57 UTC, Naresh-ibm commented
@abdhaleegit what is the latest update on this?
are you still working on it?
if not can we get the latest run logs, so that we can merge.

2023-08-30 08:12 UTC, Naresh-ibm approved these changes
LGTM

2023-08-30 08:23 UTC, abdhaleegit commented
``` 
avocado run --max-parallel-tasks=1 htx_nic_devices.py -m htx_nic_devices.py.data/htx_nic_devices.yaml 
JOB ID     : ca5503d6f2a4110d8375d1bc341ac182e0babf0b
JOB LOG    : /home/ioci/logs/io_network/results/job-2023-08-30T02.54-ca5503d/job.log
 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-659f: STARTED

 (1/3) htx_nic_devices.py:HtxNicTest.test_start;run-659f: PASS (484.38 s)
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-659f: STARTED
 (2/3) htx_nic_devices.py:HtxNicTest.test_check;run-659f: PASS (123.93 s)
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-659f: STARTED
 (3/3) htx_nic_devices.py:HtxNicTest.test_stop;run-659f: PASS (12.64 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/ioci/logs/io_network/results/job-2023-08-30T02.54-ca5503d/results.html
JOB TIME   : 629.24 s
```

2023-08-30 08:29 UTC, merged