Fix the logic to cancel tests when arch other than [ppc.ppc64le]
avocado-framework-tests/avocado-misc-tests pull request #2692
Opened 2023-08-11 06:34 UTC by spoorthys1303

Logic to cancel the tests when detected distro arch is not ppc or ppc64le changed to use logical operator "and" instead of "or" , to get appropriate results
Signed-off-by: Spoorthy S<spoorts2@in.ibm.com>

2023-08-11 06:34 UTC, spoorthys1303 commented
A sample test:
`>>> detected_distro="ppc"
>>> if (detected_distro != 'ppc64' and detected_distro != 'ppc64le'):
...     print("cancel")
... 
cancel
>>> detected_distro="x86"
>>> if (detected_distro != 'ppc64' and detected_distro != 'ppc64le'):
...     print("cancel")
... 
cancel
>>> detected_distro="ppc64"
>>> 
>>> if (detected_distro != 'ppc64' and detected_distro != 'ppc64le'):
...     print("cancel")
... 
>>> detected_distro="ppc64le"
>>> 
>>> if (detected_distro != 'ppc64' and detected_distro != 'ppc64le'):
...     print("cancel")`

2023-08-14 04:30 UTC, abdhaleegit requested changes

2023-08-14 04:30 UTC, abdhaleegit commented on kernel/kselftest.py
> +            if (detected_distro.arch != 'ppc64' and detected_distro.arch != 'ppc64le'):
at given time, the ppc OS can be BE mode i.e ppc64 or LE mode i.e ppc64le   so  it will contradict with in power

2023-08-14 04:32 UTC, abdhaleegit commented on kernel/kselftest.py
> +            if (detected_distro.arch != 'ppc64' and detected_distro.arch != 'ppc64le'):
I would suggest to use 
`if 'ppc' not in detected_distro.arch:`

2023-08-14 10:46 UTC, abdhaleegit commented
@spoorthys1303 logs please, than we are good to go

2023-08-14 11:16 UTC, spoorthys1303 commented
```
>>> distro="ppc64"
>>> if 'ppc' not in distro:
...     print("cancel")
... 
>>> distro="ppc64le"
>>> if 'ppc' not in distro:
...     print("cancel")
... 
>>> distro="x86"
>>> if 'ppc' not in distro:
...     print("cancel")
... 
cancel
>>> if 'ppc' not in distro:
...     print("cancel")
... 
cancel
```

2023-08-14 11:34 UTC, spoorthys1303 commented
Before fixing issue:

```
# python avocado-setup.py --run-suite host_sanity_min
07:19:46 INFO    : Check for environment
07:19:46 INFO    : Creating temporary mux dir
07:19:46 INFO    : 
07:19:46 INFO    : Running Host Tests Suite sanity_min_kselftest_kselftest_powerpc
07:19:46 INFO    : Running: /usr/bin/avocado run --max-parallel-tasks=1 /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py -m /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py.data/kselftest_powerpc.yaml --force-job-id efbb0172e3a5127f120f804e041622980eae7007  --job-results-dir /home/OpTest/avocado-fvt-wrapper/results
Fetching asset from /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py:kselftest.test
JOB ID     : efbb0172e3a5127f120f804e041622980eae7007
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2023-08-14T07.19-efbb017/job.log
 (1/1) /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py:kselftest.test;run-component-power-run_type-distro-fab0: STARTED
 (1/1) /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py:kselftest.test;run-component-power-run_type-distro-fab0: CANCEL: Testing on a non powerpc platform (0.01 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2023-08-14T07.19-efbb017/results.html
JOB TIME   : 18.74 s
07:20:09 INFO    : 
07:20:09 INFO    : Summary of test results can be found below:
TestSuite                                                                                TestRun    Summary
 
host_sanity_min_kselftest_kselftest_powerpc                                              Run        Successfully executed
```

2023-08-14 11:35 UTC, spoorthys1303 commented
After fixing issue

```
# python avocado-setup.py --run-suite host_sanity_min
07:29:00 INFO    : Creating temporary mux dir
07:29:00 INFO    : 
07:29:00 INFO    : Running Host Tests Suite sanity_min_kselftest_kselftest_powerpc
07:29:00 INFO    : Running: /usr/bin/avocado run --max-parallel-tasks=1 /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py -m /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py.data/kselftest_powerpc.yaml --force-job-id 9ed1e6e2c44980cbef7088184cad08ecf42f4ebe  --job-results-dir /home/OpTest/avocado-fvt-wrapper/results
Fetching asset from /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py:kselftest.test
JOB ID     : 9ed1e6e2c44980cbef7088184cad08ecf42f4ebe
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2023-08-14T07.29-9ed1e6e/job.log
 (1/1) /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py:kselftest.test;run-component-power-run_type-distro-fab0: STARTED
 (1/1) /home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/kernel/kselftest.py:kselftest.test;run-component-power-run_type-distro-fab0: ERROR: Command 'make -C powerpc' failed.\nstdout: b'make: Entering directory \'/usr/src/linux-5.3.18-150300.59.106.1.ioktd775c1a72/tools/testing/selftests/powerpc\'\nBUILD_TARGET=/usr/src/linux-5.3.18-150300.59.106.1.ioktd775c1a72/tools/testing/selftests/powerpc/... (208.73 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/OpTest/avocado-fvt-wrapper/results/job-2023-08-14T07.29-9ed1e6e/results.html
JOB TIME   : 228.34 s

```

2023-08-14 11:53 UTC, abdhaleegit approved these changes
LGTM

2023-08-14 11:53 UTC, merged