Added invalid domain check, invalid core check, invalid chip check
avocado-framework-tests/avocado-misc-tests pull request #2705
Opened 2023-09-11 18:27 UTC by Krishan-Saraswat

Core values and Chip values are calculated using lscpu, Boundary conditions are added for domain values,
Boundary conditions are added for core values,
Boundary conditions are added for chip values.

2023-09-14 05:54 UTC, disgoel approved these changes
LGTM

2023-09-20 08:50 UTC, PraveenPenguin commented on perf/perf_24x7_hardware_counters.py
> +        self.chips = int(self.physical_sockets*self.physical_chips)
can we push this as part of avocado utils?

2023-09-20 10:00 UTC, Krishan-Saraswat commented on perf/perf_24x7_hardware_counters.py
> +        invalid_domains = [0, 7, 16]
yes, these are constant values for invalid domains.

2023-10-09 16:25 UTC, Naresh-ibm requested changes

2023-10-09 16:25 UTC, Naresh-ibm commented on perf/perf_24x7_hardware_counters.py
> +    def test_check_invalid_core(self):
Add the Docstring

2023-10-09 16:25 UTC, Naresh-ibm commented on perf/perf_24x7_hardware_counters.py
> +    def test_check_valid_chip(self):
dockstring

2023-10-30 08:18 UTC, disgoel commented
@PraveenPenguin @Naresh-ibm can you please review and close

2023-11-06 06:18 UTC, PraveenPenguin approved these changes

2023-11-16 06:06 UTC, PraveenPenguin commented
@Naresh-ibm can you please review this PR

2023-11-16 13:19 UTC, Naresh-ibm approved these changes
LGTM

2023-11-16 13:21 UTC, merged

2024-05-09 08:01 UTC, disgoel commented
> Hi Krishan,any reason on removing code to print " error msg to enable permission tp collect stats?" I think its better to have that code as many time, there is wrong alarm because of this option not enabled.

There were two checks for the same thing, so he removed the old check which was no more valid error message. Below check is still there.
```
        if "operations is limited" in result_perf.stderr.decode("utf-8"):
            self.cancel("Please enable lpar to allow collecting"
                        " the 24x7 counters info")
```

2024-06-07 12:49 UTC, disgoel commented on perf/perf_24x7_hardware_counters.py
> +        result = self.event_stat(',domain=3,core=65536/ sleep 1')
addressed this in PR https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2808