Patching netperf package for successful compilation
avocado-framework-tests/avocado-misc-tests pull request #2709
Opened 2023-09-15 18:45 UTC by vaishnavibhat

Use nettest_omni.patch for fixing make issue seen during compilation of package on host and peer machine

2023-09-15 18:46 UTC, vaishnavibhat commented
avocado run netperf_test.py -m netperf_test.py.data/netperf_test_virt.yaml --max-parallel-tasks=1
JOB ID     : b5cb1353d48ef7e856b4e68991090c68c688789d
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-09-15T07.14-b5cb135/job.log
 (01/10) netperf_test.py:Netperf.test;run-mtu-1500-option-generic-b1a8: STARTED
 (01/10) netperf_test.py:Netperf.test;run-mtu-1500-option-generic-b1a8: PASS (387.46 s)
 (02/10) netperf_test.py:Netperf.test;run-mtu-9000-option-generic-a750: STARTED
 (02/10) netperf_test.py:Netperf.test;run-mtu-9000-option-generic-a750: PASS (392.36 s)
 (03/10) netperf_test.py:Netperf.test;run-mtu-1500-option-tcp_stream-c378: STARTED
 (03/10) netperf_test.py:Netperf.test;run-mtu-1500-option-tcp_stream-c378: PASS (42.46 s)
 (04/10) netperf_test.py:Netperf.test;run-mtu-9000-option-tcp_stream-a706: STARTED
 (04/10) netperf_test.py:Netperf.test;run-mtu-9000-option-tcp_stream-a706: PASS (46.48 s)
 (05/10) netperf_test.py:Netperf.test;run-mtu-1500-option-udp_stream-1e99: STARTED
 (05/10) netperf_test.py:Netperf.test;run-mtu-1500-option-udp_stream-1e99: PASS (42.58 s)
 (06/10) netperf_test.py:Netperf.test;run-mtu-9000-option-udp_stream-6ddf: STARTED
 (06/10) netperf_test.py:Netperf.test;run-mtu-9000-option-udp_stream-6ddf: PASS (46.57 s)
 (07/10) netperf_test.py:Netperf.test;run-mtu-1500-option-tcp_rr-6644: STARTED
 (07/10) netperf_test.py:Netperf.test;run-mtu-1500-option-tcp_rr-6644: PASS (512.69 s)
 (08/10) netperf_test.py:Netperf.test;run-mtu-9000-option-tcp_rr-a7e0: STARTED
 (08/10) netperf_test.py:Netperf.test;run-mtu-9000-option-tcp_rr-a7e0: PASS (516.07 s)
 (09/10) netperf_test.py:Netperf.test;run-mtu-1500-option-udp_rr-09b2: STARTED
 (09/10) netperf_test.py:Netperf.test;run-mtu-1500-option-udp_rr-09b2: PASS (636.98 s)
 (10/10) netperf_test.py:Netperf.test;run-mtu-9000-option-udp_rr-e195: STARTED
 (10/10) netperf_test.py:Netperf.test;run-mtu-9000-option-udp_rr-e195: PASS (636.52 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-09-15T07.14-b5cb135/results.html
JOB TIME   : 3295.87 s

2023-09-16 07:03 UTC, PraveenPenguin commented on io/net/netperf_test.py
> +               self.netperf_dir_peer, peer_patch_name)
@vaishnavibhat have missed patch file to commit ?

2023-09-19 11:56 UTC, abdhaleegit requested changes

2023-09-19 11:56 UTC, abdhaleegit commented on io/net/netperf_test.py
> +        patch_file = self.params.get('patch', default='nettest_omni.patch')
you do not need to get the patchfile parameter,  this should be placed in data folder beside yamls and the same path should be used here

2023-09-25 09:20 UTC, merged