Fixed the issue happening while conpiling the upstream nvme-cli
avocado-framework-tests/avocado-misc-tests pull request #2711
Opened 2023-09-22 05:42 UTC by Naresh-ibm

compilation of upstream nvme-cli was failing. this script will fix this problem and it work fine

2023-09-22 05:46 UTC, Naresh-ibm commented
`[root@sys ssd]# avocado run --max-parallel-tasks=1 old-nvmetest.py -m nvmetest.py.data/nvmetest.yaml 
Fetching asset from old-nvmetest.py:NVMeTest.test_firmware_upgrade
Fetching asset from old-nvmetest.py:NVMeTest.test_create_max_ns
Fetching asset from old-nvmetest.py:NVMeTest.test_create_full_capacity_ns
Fetching asset from old-nvmetest.py:NVMeTest.testformatnamespace
Fetching asset from old-nvmetest.py:NVMeTest.testread
Fetching asset from old-nvmetest.py:NVMeTest.testwrite
Fetching asset from old-nvmetest.py:NVMeTest.testcompare
Fetching asset from old-nvmetest.py:NVMeTest.testflush
Fetching asset from old-nvmetest.py:NVMeTest.testwritezeroes
Fetching asset from old-nvmetest.py:NVMeTest.testwriteuncorrectable
Fetching asset from old-nvmetest.py:NVMeTest.testdsm
Fetching asset from old-nvmetest.py:NVMeTest.testreset
Fetching asset from old-nvmetest.py:NVMeTest.testreset_sysfs
Fetching asset from old-nvmetest.py:NVMeTest.testsubsystemreset
Fetching asset from old-nvmetest.py:NVMeTest.test_create_namespaces
Fetching asset from old-nvmetest.py:NVMeTest.test_delete_all_ns
JOB ID     : c8bfdfd68c7ce5164bc809a136a1f73945b3aa88
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2023-09-22T00.38-c8bfdfd/job.log
 (01/32) old-nvmetest.py:NVMeTest.test_firmware_upgrade;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (01/32) old-nvmetest.py:NVMeTest.test_firmware_upgrade;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: CANCEL: firmware url not given (12.79 s)
 (02/32) old-nvmetest.py:NVMeTest.test_firmware_upgrade;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (02/32) old-nvmetest.py:NVMeTest.test_firmware_upgrade;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: CANCEL: firmware url not given (0.35 s)
 (03/32) old-nvmetest.py:NVMeTest.test_create_max_ns;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (03/32) old-nvmetest.py:NVMeTest.test_create_max_ns;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (6.24 s)
 (04/32) old-nvmetest.py:NVMeTest.test_create_max_ns;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (04/32) old-nvmetest.py:NVMeTest.test_create_max_ns;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (0.84 s)
 (05/32) old-nvmetest.py:NVMeTest.test_create_full_capacity_ns;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (05/32) old-nvmetest.py:NVMeTest.test_create_full_capacity_ns;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (6.12 s)
 (06/32) old-nvmetest.py:NVMeTest.test_create_full_capacity_ns;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (06/32) old-nvmetest.py:NVMeTest.test_create_full_capacity_ns;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (0.95 s)
 (07/32) old-nvmetest.py:NVMeTest.testformatnamespace;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (07/32) old-nvmetest.py:NVMeTest.testformatnamespace;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (16.19 s)
 (08/32) old-nvmetest.py:NVMeTest.testformatnamespace;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (08/32) old-nvmetest.py:NVMeTest.testformatnamespace;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (10.91 s)
 (09/32) old-nvmetest.py:NVMeTest.testread;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (09/32) old-nvmetest.py:NVMeTest.testread;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (5.71 s)
 (10/32) old-nvmetest.py:NVMeTest.testread;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (10/32) old-nvmetest.py:NVMeTest.testread;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (0.37 s)
 (11/32) old-nvmetest.py:NVMeTest.testwrite;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (11/32) old-nvmetest.py:NVMeTest.testwrite;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (5.64 s)
 (12/32) old-nvmetest.py:NVMeTest.testwrite;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (12/32) old-nvmetest.py:NVMeTest.testwrite;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (0.39 s)
 (13/32) old-nvmetest.py:NVMeTest.testcompare;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (13/32) old-nvmetest.py:NVMeTest.testcompare;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (5.73 s)
 (14/32) old-nvmetest.py:NVMeTest.testcompare;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (14/32) old-nvmetest.py:NVMeTest.testcompare;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (0.37 s)
 (15/32) old-nvmetest.py:NVMeTest.testflush;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (15/32) old-nvmetest.py:NVMeTest.testflush;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (5.65 s)
 (16/32) old-nvmetest.py:NVMeTest.testflush;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (16/32) old-nvmetest.py:NVMeTest.testflush;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (0.38 s)
 (17/32) old-nvmetest.py:NVMeTest.testwritezeroes;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (17/32) old-nvmetest.py:NVMeTest.testwritezeroes;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (5.65 s)
 (18/32) old-nvmetest.py:NVMeTest.testwritezeroes;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (18/32) old-nvmetest.py:NVMeTest.testwritezeroes;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (0.37 s)
 (19/32) old-nvmetest.py:NVMeTest.testwriteuncorrectable;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (19/32) old-nvmetest.py:NVMeTest.testwriteuncorrectable;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (5.73 s)
 (20/32) old-nvmetest.py:NVMeTest.testwriteuncorrectable;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (20/32) old-nvmetest.py:NVMeTest.testwriteuncorrectable;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (0.37 s)
 (21/32) old-nvmetest.py:NVMeTest.testdsm;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (21/32) old-nvmetest.py:NVMeTest.testdsm;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (5.64 s)
 (22/32) old-nvmetest.py:NVMeTest.testdsm;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (22/32) old-nvmetest.py:NVMeTest.testdsm;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: PASS (0.38 s)
 (23/32) old-nvmetest.py:NVMeTest.testreset;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: STARTED
 (23/32) old-nvmetest.py:NVMeTest.testreset;run-Devices-device1-firmware_url-namespace_count-package-upstream-nvme-cli-9bc3: PASS (5.87 s)
 (24/32) old-nvmetest.py:NVMeTest.testreset;run-Devices-device1-firmware_url-namespace_count-package-distro-nvme-cli-5f61: STARTED
 (24/32) old-nvmetest.py:NVMeTest.testreset;run-Devices-device1-firmware_url-namespace_count-pack [...]

2023-09-22 07:00 UTC, abdhaleegit requested changes

2023-09-22 07:50 UTC, Naresh-ibm commented on io/disk/ssd/nvmetest.py
> +# from avocado.utils import build
This is not used any where. earlier it was used.
just commented thinking if needed in future.

2023-09-22 09:13 UTC, abdhaleegit commented on io/disk/ssd/nvmetest.py
> +# from avocado.utils import build
remove it

2023-09-25 06:47 UTC, abdhaleegit approved these changes
LGTM

2023-09-25 07:07 UTC, merged