Added testcase to capture the ebizzy workload
avocado-framework-tests/avocado-misc-tests pull request #2717
Opened 2023-10-03 10:00 UTC by Krishan-Saraswat

test_workload test case is added to capture the output of ebizzy workload using perf_top and validating it.
Added a readme file on how to run the workload test case separately.

2023-10-09 16:11 UTC, Naresh-ibm requested changes

2023-10-09 16:11 UTC, Naresh-ibm commented on perf/perf_top.py
> +        # Get ebizzy workload and build
@Krishan-Saraswat please have proper doc-string

2023-10-09 16:11 UTC, Naresh-ibm commented on perf/perf_top.py
> +    def run_workload(self):
same here too

2023-10-09 16:11 UTC, Naresh-ibm commented on perf/perf_top.py
> +    def capture_top_output(self):
same

2023-10-09 16:11 UTC, Naresh-ibm commented on perf/readme
> +avocado run perf_top.py:perf_top.test_workload
make this as `example:`

2023-10-09 16:11 UTC, Naresh-ibm commented on perf/readme
> +avocado run --max-parallel-tasks=1 perf_top.py:perf_top.test_top -m perf_top.py.data/perf_top.yaml
add the different yaml parameter and how to fetch the different values for those parameters.
check any other Readme file for reference

2023-10-19 04:57 UTC, abdhaleegit commented on perf/perf_top.py
> +        build.make(self.sourcedir, extra_args='LDFLAGS=-static')
As discussed yesterday, we can still add this as a scenario in a existing cfg, making sure ebizzy is modified to run with any other tests as this is a workload

2023-10-19 04:57 UTC, abdhaleegit requested changes
Just think about reusing ebizzy test instead of adding here

2024-03-22 07:36 UTC, closed without merging

2024-03-22 07:37 UTC, Krishan-Saraswat commented
Creating a fresh pull request for adding workload.