Added new testcase to run ebizzy workload.
avocado-framework-tests/avocado-misc-tests pull request #2739
Opened 2023-12-04 09:52 UTC by Krishan-Saraswat

Ebizzy workload and "perf top -a" command will run on threads to capture ebizzy workload.

[root@]# avocado run --max-parallel-tasks=1 ebizzy.py
Fetching asset from ebizzy.py:ebizzy.test_workload
JOB ID     : 2b416d00bcf2402cb6c3373d1fa68e410ed84b45
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-12-04T03.18-2b416d0/job.log
 (1/1) ebizzy.py:ebizzy.test_workload: STARTED
 (1/1) ebizzy.py:ebizzy.test_workload: PASS (12.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-12-04T03.18-2b416d0/results.html
JOB TIME   : 40.09 s

2023-12-11 06:50 UTC, PraveenPenguin requested changes
@Krishan-Saraswat can we have this py file only be run ebizzy alone and perf verify logic can be moved in perf test case , so on that case this can be used easily and work load ask

2023-12-11 06:50 UTC, PraveenPenguin commented on workload/ebizzy.py
> +        process.run("./ebizzy -S1 -s1024 -t10", shell=True)
can input value drive as yaml input so it can be user-driven as well

2023-12-11 06:50 UTC, PraveenPenguin commented on workload/ebizzy.py
> +        thread1 = threading.Thread(target=self.run_workload)
please have some meaningful variable  name

2023-12-11 06:50 UTC, PraveenPenguin commented on workload/ebizzy.py
> +        url = 'https://sourceforge.net/projects/ebizzy/files/ebizzy/0.3/ebizzy-0.3.tar.gz'
have this also a YAML configured

2024-01-09 07:30 UTC, Naresh-ibm requested changes

2024-01-09 07:30 UTC, Naresh-ibm commented on workload/ebizzy.py
> +# Copyright: 2022 IBM
Please change this to 2023/24

2024-01-09 07:30 UTC, Naresh-ibm commented on workload/ebizzy.py
> +# Author: Disha Goel <disgoel@linux.vnet.ibm.com>
This also

2024-01-09 07:30 UTC, Naresh-ibm commented on workload/ebizzy.py
> +    def run_workload(self):
Dock strings please

2024-01-09 07:30 UTC, Naresh-ibm commented on workload/ebizzy.py
> +    def capture_top_output(self):
same here

2024-01-09 07:30 UTC, Naresh-ibm commented on workload/ebizzy.py
> +    def teardown(self):
Dock Strings

2024-02-14 06:55 UTC, Naresh-ibm commented
@Krishan-Saraswat any updates?

2024-05-07 06:23 UTC, Krishan-Saraswat commented
Hi @abdhaleegit @Naresh-ibm  this code is already merged in Avocdo with a fresh new Pull request, I'm closing this one.

2024-05-07 06:23 UTC, closed without merging