EEH test for vnic interfaces
avocado-framework-tests/avocado-misc-tests pull request #2771
Opened 2024-03-13 12:34 UTC by vaishnavibhat

Adding test to trigger EEH for vnic interfaces from vios. The test does the following:
- change the active logport to the original logport
- login to the vios and find the respective backing device
- trigger EEH from vios
- check for the failover on the OS side to conclude if the eeh was successful ornot.

2024-03-13 12:39 UTC, vaishnavibhat commented
avocado run network_virtualization.py:NetworkVirtualization.test_vnic_eeh -m network_virtualization.yaml 
JOB ID     : 2d051d0a053822ae3020de908d25291ef8ebc04d
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-13T17.59-2d051d0/job.log
 (1/1) network_virtualization.py:NetworkVirtualization.test_vnic_eeh;run-e720: STARTED
 (1/1) network_virtualization.py:NetworkVirtualization.test_vnic_eeh;run-e720: PASS (74.70 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-03-13T17.59-2d051d0/results.html
JOB TIME   : 92.03 s

[debug.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/14587709/debug.log)

[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/14587723/job.log)

2024-03-14 04:08 UTC, PraveenPenguin commented on io/net/virt-net/network_virtualization.py
> +from pexpect import pxssh
can we have readme or class comment as this need to be installed before running test

2024-03-14 04:08 UTC, PraveenPenguin commented on io/net/virt-net/network_virtualization.py
> +        time.sleep(5)
why sleep?  we are not waiting any command right

2024-03-14 04:08 UTC, PraveenPenguin commented on io/net/virt-net/network_virtualization.py
> +        s = pxssh.pxssh()
please have meaningful variable name

2024-03-19 04:35 UTC, abdhaleegit requested changes
take care of 

1. eeh tool
2. non mellanox adapter `set scroll false` `lnc2ent setacs` `lnc2ent hw pollq 0` 
3. if no backing device

2024-03-19 04:35 UTC, abdhaleegit commented on io/net/virt-net/network_virtualization.py
> +        cmd = "./eeh_tool_64 %s 3 15 -w 64 -a %s -m 0xFFFFFFFFFFFFF000" % (vnic_bankingdevice, map_start_value)
make sure the eeh_tool is available in .py..data folder of this test.. and add a logic to copy every time to vios

2024-03-19 04:35 UTC, abdhaleegit commented on io/net/virt-net/network_virtualization.py
> +            self.fail("EEH unsuccessful as there is no failover triggered on the OS")
so what if the vnic has no backing device ?

2024-03-19 04:35 UTC, abdhaleegit commented on io/net/virt-net/network_virtualization.py
> +        s.sendline("mlxcent pollq 0")
all commands are specific to mellanox adapters, what if the backing adapter is non mellanox... please add those commands

2024-03-21 05:31 UTC, abdhaleegit commented
@vaishnavibhat also make sure the kernel debugger is enabled in VIOS.. else the KDB console will not work

2024-03-28 05:27 UTC, abdhaleegit requested changes
think of scp tool from lpar to vios .. but from inside vios

2024-03-28 05:27 UTC, abdhaleegit commented on io/net/virt-net/network_virtualization.py
> +        cmd = "./eeh_tool_64 %s 3 15 -w 64 -a %s -m 0xFFFFFFFFFFFFF000" % (vnic_bankingdevice, map_start_value)
can you create a scp command by getting the local lpar ip and path to binary  and run on vios

cmd = "scp lparuser@lparip:/path/to/data/file/binary ." % (lpar_user, lpar_ip, bin_path)
sendline(cmd)
expect(passwd:)
sendline(lpar_pass)

2024-03-28 05:27 UTC, abdhaleegit commented on io/net/virt-net/network_virtualization.py
> +        cmd = "mlxcent setacs %s" % vnic_bankingdevice
spell check

2024-04-16 05:25 UTC, abdhaleegit commented on io/net/virt-net/network_virtualization.py
> +import pexpect
remove the above line  pexpect is not explicitly used in the code .. this will resolve the travis fail

2024-04-19 10:45 UTC, abdhaleegit approved these changes
LGTM

2024-04-19 10:45 UTC, merged