perf_cpu_hotplug_enhancements
avocado-framework-tests/avocado-misc-tests pull request #2802
Opened 2024-04-23 06:56 UTC by akanksha216

Add two new test cases.
The first test case offlines n-1 cpus randomly and checks if hv_24X7 points to any offline cpu.
The second test case checks the cpu pointed to by hv_24X7 event and offlines it. It then checks if the new cpu pointed to by hv_24X7 event is an online cpu, else the test fails. This is repeated n-1 times in a loop

Logs:
avocado run perf_cpu_hotplug.py
JOB ID     : a128bdd0142561e3399d997d05a25f6c70fce192
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-04-23T10.20-a128bdd/job.log
 (2/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off: STARTED
 (1/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask: STARTED
 (3/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_random: STARTED
 (1/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask: PASS (1.22 s)
 (2/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off: PASS (1.81 s)
 (4/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_sequence: STARTED
 (3/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_random: PASS (3.97 s)
 (4/4) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_sequence: PASS (6.10 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-04-23T10.20-a128bdd/results.html
JOB TIME   : 44.81 s

[test1.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15072603/test1.log)
[test2.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15072604/test2.log)
[test3.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15072605/test3.log)
[test4.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15072606/test4.log)

2024-04-23 09:57 UTC, disgoel requested changes

2024-04-23 09:57 UTC, disgoel commented on perf/perf_cpu_hotplug.py
> +                self.fail("hv_24x7 points to an offline cpu")
@akanksha216 can you add more print statements like current cpumask for 24/7 and online cpu list after offlining.
from job log file its not clear if its working as expected or not.
```
[stdlog] 2024-04-23 15:10:22,242 avocado.test perf_cpu_hotplug L0102 INFO | Online CPU list: [0, 1, 2, 3, 4, 5, 6, 7]
[stdlog] 2024-04-23 15:10:22,488 avocado.test perf_cpu_hotplug L0115 INFO | Offline CPU: 3
[stdlog] 2024-04-23 15:10:22,608 avocado.test perf_cpu_hotplug L0115 INFO | Offline CPU: 5
[stdlog] 2024-04-23 15:10:22,608 avocado.test perf_cpu_hotplug L0115 INFO | Offline CPU: 5
[stdlog] 2024-04-23 15:10:22,726 avocado.test perf_cpu_hotplug L0115 INFO | Offline CPU: 0
[stdlog] 2024-04-23 15:10:22,726 avocado.test perf_cpu_hotplug L0115 INFO | Offline CPU: 3
[stdlog] 2024-04-23 15:10:22,727 avocado.test perf_cpu_hotplug L0115 INFO | Offline CPU: 5
[stdlog] 2024-04-23 15:10:22,828 avocado.test perf_cpu_hotplug L0115 INFO | Offline CPU: 2
[stdlog] 2024-04-23 15:10:22,829 avocado.utils.process process          L0655 INFO | Running 'dmesg'
```

2024-04-23 09:57 UTC, disgoel commented on perf/perf_cpu_hotplug.py
> +            self._check_cpumask()
same here also

2024-04-23 10:01 UTC, disgoel commented
Also you can remove this check as suggested by dev team both cpumask need not be same
>         if hv24x7_cpu != hvgpci_cpu:
>            self.fail("cpumask values of hv24x7 and hv_gpci are not same.")

2024-04-30 04:44 UTC, akanksha216 commented
# avocado run perf_cpu_hotplug.py
JOB ID     : e68d8c2852c624e6b4bb8cad0a0b8059a1f09edf
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-04-30T09.55-e68d8c2/job.log
 (2/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_sequence: STARTED
 (1/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_random: STARTED
 (2/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_sequence: PASS (2.98 s)
 (1/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_random: PASS (7.98 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-04-30T09.55-e68d8c2/results.html
JOB TIME   : 26.37 s

[test1.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15158360/test1.log)
[test2.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15158361/test2.log)

2024-04-30 07:13 UTC, disgoel approved these changes
LGTM

2024-05-06 06:48 UTC, abdhaleegit commented on perf/perf_cpu_hotplug.py
> +        events = ["hv_24x7", "hv_gpci"]
make it class variable to avoid duplicate initialization

2024-05-06 06:48 UTC, abdhaleegit commented on perf/perf_cpu_hotplug.py
> +        events = ["hv_24x7", "hv_gpci"]
like here

2024-05-08 02:30 UTC, PraveenPenguin commented on perf/perf_cpu_hotplug.py
> +#          Akanksha J N <akanksha@linux.ibm.com>
I  feel we  should consider modifying author name when have more update in this module

2024-05-14 09:06 UTC, akanksha216 commented
Latest logs

avocado run perf_cpu_hotplug.py
JOB ID     : eeadecd48b44bff326adf0a6d83b905300773017
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-05-14T14.31-eeadecd/job.log
 (2/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_sequence: STARTED
 (1/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_random: STARTED
 (2/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_sequence: PASS (9.26 s)
 (1/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_random: PASS (16.83 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-05-14T14.31-eeadecd/results.html
JOB TIME   : 33.17 s

[test1.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15305979/test1.log)
[test2.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15305981/test2.log)

2024-05-14 13:24 UTC, PraveenPenguin approved these changes
LGTM

2024-05-14 13:25 UTC, merged