[WIP] Added support for proc and mem to perform sequentially
avocado-framework-tests/avocado-misc-tests pull request #2810
Opened 2024-04-28 10:14 UTC by shirishaganta1

Proc: Added support which do add and remove procs
based on the availability of system resources
Mem: added support which add memory quantity as per the lmb based on the availability of system resources

2024-04-28 10:32 UTC, shirishaganta1 commented
JOB ID     : db8c1b0e45884ef0142412165d7ca25dffca669b
JOB LOG    : /home/geet/avocado-fvt-wrapper/results/job-2024-04-28T04.05-db8c1b0/job.log
 (1/3) dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-dedicated-39fa: STARTED
 (1/3) dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-dedicated-39fa:  PASS (248.49 s)
 (2/3) dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-dedicated-39fa: STARTED
 (2/3) dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-dedicated-39fa:  PASS (126.26 s)
 (3/3) dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-dedicated-39fa: STARTED
 (3/3) dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-dedicated-39fa:  PASS (564.89 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/geet/avocado-fvt-wrapper/results/job-2024-04-28T04.05-db8c1b0/results.html
JOB TIME   : 984.97 s
[cpu_add_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15141791/cpu_add_run-config-lpar_mode-dedicated.log)
[cpu_rm_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15141794/cpu_rm_run-config-lpar_mode-dedicated.log)
[mem_add_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15141797/mem_add_run-config-lpar_mode-dedicated.log)

2024-04-28 10:37 UTC, shirishaganta1 commented
JOB ID     : db8c1b0e45884ef0142412165d7ca25dffca669b
JOB LOG    : /home/geet/avocado-fvt-wrapper/results/job-2024-04-28T04.05-db8c1b0/job.log
 (1/3) dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-dedicated-39fa: STARTED
 (1/3) dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-dedicated-39fa:  PASS (248.49 s)
 (2/3) dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-dedicated-39fa: STARTED
 (2/3) dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-dedicated-39fa:  PASS (126.26 s)
 (3/3) dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-dedicated-39fa: STARTED
 (3/3) dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-dedicated-39fa:  PASS (564.89 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/geet/avocado-fvt-wrapper/results/job-2024-04-28T04.05-db8c1b0/results.html
JOB TIME   : 984.97 s
[cpu_add_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15141807/cpu_add_run-config-lpar_mode-dedicated.log)
[cpu_rm_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15141808/cpu_rm_run-config-lpar_mode-dedicated.log)
[mem_add_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15141809/mem_add_run-config-lpar_mode-dedicated.log)

2024-04-29 04:33 UTC, PraveenPenguin commented
@SamirMulani  can you please review this PR

2024-04-29 17:01 UTC, Naresh-ibm requested changes

2024-04-29 17:01 UTC, Naresh-ibm commented
Please add the doc string and remove the commented lines

2024-05-09 04:08 UTC, shirishaganta1 commented
JOB ID     : a477bac9653937c72544848871461c5f58d70f70
JOB LOG    : /home/siri/avocado-fvt-wrapper/results/job-2024-05-08T22.19-a477bac/job.log
 (1/6) dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-dedicated-9e77: STARTED
 (1/6) dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-dedicated-9e77:  PASS (675.36 s)
 (2/6) dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-dedicated-9e77: STARTED
 (2/6) dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-dedicated-9e77:  PASS (348.84 s)
 (3/6) dlpar_main.py:DlparTests.test_mix_cpu;run-config-lpar_mode-dedicated-9e77: STARTED
 (3/6) dlpar_main.py:DlparTests.test_mix_cpu;run-config-lpar_mode-dedicated-9e77:  PASS (781.38 s)
 (4/6) dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-dedicated-9e77: STARTED
 (4/6) dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-dedicated-9e77:  PASS (717.22 s)
 (5/6) dlpar_main.py:DlparTests.test_mem_rem;run-config-lpar_mode-dedicated-9e77: STARTED
 (5/6) dlpar_main.py:DlparTests.test_mem_rem;run-config-lpar_mode-dedicated-9e77:  PASS (597.37 s)
 (6/6) dlpar_main.py:DlparTests.test_mem_mix;run-config-lpar_mode-dedicated-9e77: STARTED
 (6/6) dlpar_main.py:DlparTests.test_mem_mix;run-config-lpar_mode-dedicated-9e77:  PASS (1186.37 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/siri/avocado-fvt-wrapper/results/job-2024-05-08T22.19-a477bac/results.html
JOB TIME   : 4334.11 s

2024-05-15 06:49 UTC, shirishaganta1 commented on dlpar/dlpar_api/api.py
> +        #              self.quant_to_test)
we need them for move tests.. will uncomment them

2024-05-15 06:49 UTC, shirishaganta1 commented on dlpar/dlpar_api/api.py
> +        # self.log.check_log(c_msg, c_condition)
we need them for move tests.. will uncomment them

2024-05-16 04:26 UTC, shirishaganta1 commented
shared:
JOB ID     : f749a165995fd831f8d7c5a4f08ba8dd56f85e22
JOB LOG    : /home/geet/avocado-fvt-wrapper/results/job-2024-05-14T23.47-f749a16/job.log
 (1/8) dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-shared-a2b8: STARTED
 (1/8) dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-shared-a2b8:  PASS (2073.67 s)
 (2/8) dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-shared-a2b8: STARTED
 (2/8) dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-shared-a2b8:  PASS (1956.62 s)
 (3/8) dlpar_main.py:DlparTests.test_mix_cpu;run-config-lpar_mode-shared-a2b8: STARTED
 (3/8) dlpar_main.py:DlparTests.test_mix_cpu;run-config-lpar_mode-shared-a2b8:  PASS (3769.27 s)
 (4/8) dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-shared-a2b8: STARTED
 (4/8) dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-shared-a2b8:  PASS (648.03 s)
 (5/8) dlpar_main.py:DlparTests.test_mem_rem;run-config-lpar_mode-shared-a2b8: STARTED
 (5/8) dlpar_main.py:DlparTests.test_mem_rem;run-config-lpar_mode-shared-a2b8:  PASS (774.30 s)
 (6/8) dlpar_main.py:DlparTests.test_mem_mix;run-config-lpar_mode-shared-a2b8: STARTED
 (6/8) dlpar_main.py:DlparTests.test_mem_mix;run-config-lpar_mode-shared-a2b8:  PASS (1657.82 s)
 (7/8) dlpar_main.py:DlparTests.test_cpu_move;run-config-lpar_mode-shared-a2b8: STARTED
 (7/8) dlpar_main.py:DlparTests.test_cpu_move;run-config-lpar_mode-shared-a2b8:  PASS (63.70 s)
 (8/8) dlpar_main.py:DlparTests.test_mem_mov;run-config-lpar_mode-shared-a2b8: STARTED
 (8/8) dlpar_main.py:DlparTests.test_mem_mov;run-config-lpar_mode-shared-a2b8:  PASS (73.09 s)
RESULTS    : PASS 8 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/geet/avocado-fvt-wrapper/results/job-2024-05-14T23.47-f749a16/results.html
JOB TIME   : 11062.70 s

2024-05-23 04:07 UTC, shirishaganta1 commented
JOB ID     : 37b86c37d7bd484d0118896cef628fdb9fc90d2b
JOB LOG    : /home/siri/avocado-fvt-wrapper/results/job-2024-05-22T08.54-37b86c3/job.log
 (1/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-dedicated-da08: STARTED
 (1/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_cpu_add;run-config-lpar_mode-dedicated-da08:  PASS (768.41 s)
 (2/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-dedicated-da08: STARTED
 (2/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_cpu_rm;run-config-lpar_mode-dedicated-da08:  PASS (412.76 s)
 (3/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_mix_cpu;run-config-lpar_mode-dedicated-da08: STARTED
 (3/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_mix_cpu;run-config-lpar_mode-dedicated-da08:  PASS (1863.02 s)
 (4/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-dedicated-da08: STARTED
 (4/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_mem_add;run-config-lpar_mode-dedicated-da08:  PASS (538.30 s)
 (5/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_mem_rem;run-config-lpar_mode-dedicated-da08: STARTED
 (5/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_mem_rem;run-config-lpar_mode-dedicated-da08:  PASS (561.08 s)
 (6/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_mem_mix;run-config-lpar_mode-dedicated-da08: STARTED
 (6/6) /home/siri/avocado-fvt-wrapper/tests/avocado-misc-tests/dlpar/dlpar_main.py:DlparTests.test_mem_mix;run-config-lpar_mode-dedicated-da08:  PASS (1260.88 s)
RESULTS    : PASS 6 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/siri/avocado-fvt-wrapper/results/job-2024-05-22T08.54-37b86c3/results.html
JOB TIME   : 5515.82 s
10:26:56 INFO    :

2024-05-23 04:36 UTC, shirishaganta1 commented
[test_cpu_add_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15411515/test_cpu_add_run-config-lpar_mode-dedicated.log)
[test_cpu_rm_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15411518/test_cpu_rm_run-config-lpar_mode-dedicated.log)
[test_mem_add_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15411519/test_mem_add_run-config-lpar_mode-dedicated.log)
[test_mem_mix_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15411523/test_mem_mix_run-config-lpar_mode-dedicated.log)
[test_mem_rem_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15411524/test_mem_rem_run-config-lpar_mode-dedicated.log)
[test_cpu_add_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15411528/test_cpu_add_run-config-lpar_mode-dedicated.log)
[test_mix_cpu_run-config-lpar_mode-dedicated.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/15411540/test_mix_cpu_run-config-lpar_mode-dedicated.log)

2024-05-27 06:06 UTC, Naresh-ibm commented on dlpar/dlpar_api/api.py
> +        return opt_value
@shirishaganta1 what is your thought on this?
@PraveenPenguin @abdhaleegit ^^

2024-06-04 04:29 UTC, PraveenPenguin commented on dlpar/dlpar_api/api.py
> +        return opt_value
@Naresh-ibm yes looks good idea, let us pursue this as enhancement as other API code can be considered , for now let go with current approach

2024-06-04 06:12 UTC, Naresh-ibm commented on dlpar/dlpar_api/api.py
> +        return opt_value
@PraveenPenguin ok. please approve if no more comments, will merge.

2024-06-06 12:43 UTC, PraveenPenguin approved these changes

2024-06-06 14:52 UTC, Naresh-ibm reviewed
@shirishaganta1 Thanks for PR

2024-06-06 14:53 UTC, Naresh-ibm approved these changes
LGTM

2024-06-06 14:53 UTC, merged