Using new parameter name in yaml and source script file
avocado-framework-tests/avocado-misc-tests pull request #2818
Opened 2024-05-09 05:27 UTC by PavamanSubramaniyam

To avoid conflict between peer ipaddr parameter being used in different network and ROCE tests with different values assigned

2024-05-09 06:30 UTC, Naresh-ibm requested changes

2024-05-09 06:30 UTC, Naresh-ibm commented on io/net/sriov_device_test.py
> +            'peer_ipaddr', default="").split(' ')
@PavamanSubramaniyam I think changing only `self.params.get(
            'peer_ipaddr', default="").split(' ')` is fine.
do not change the assigned variable name. just change the value in yaml and the one in the `self.params.get('peer_ip', default="").split(' ')`

let me know if you need any help here

2024-05-13 04:22 UTC, PavamanSubramaniyam commented
I have resent the patch after incorporating the review comments.

2024-05-27 06:22 UTC, abdhaleegit commented
@PavamanSubramaniyam @Naresh-ibm normally we do not allow to change the existing parameter names as it reflects in CI/CR  runs .. so can you elaborate the need of parameter change here

btw, a rule we follow is for single peer ip the param is `peer_ip` and if there are multiple peer ips the param is `peer_ips`

2024-05-28 05:09 UTC, PavamanSubramaniyam commented
The current code in sriov_device_test.py script and the corresponding sriov_device_test.yaml, sriov_roce_device_test.yaml files, we are using peer_ip parameter, even though we can pass multiple ip's to this parameter.
So, we need to change this parameter to peer_ips for passing multiple ip's in the script and also in the .yaml files respectively.
The functionalities provided in this sriov_device_test.py script are handling multiple IP's provided in the parameter files.

But the other network test scripts which only need single IP for execution, will also be referring to the same peer_ip parameter provided in the input txt file which causes failure.

2024-05-28 10:13 UTC, abdhaleegit commented
> @PavamanSubramaniyam @Naresh-ibm normally we do not allow to change the existing parameter names as it reflects in CI/CR runs .. so can you elaborate the need of parameter change here
> 
> btw, a rule we follow is for single peer ip the param is `peer_ip` and if there are multiple peer ips the param is `peer_ips`

As discussed, will follow the above format. Please resend the code

2024-06-03 06:24 UTC, abdhaleegit commented
@PavamanSubramaniyam Please remove the commit

2024-06-12 08:03 UTC, PavamanSubramaniyam commented
I have removed the commit and resent the changes as new commit

2024-06-24 12:43 UTC, abdhaleegit approved these changes
LGTM

2024-06-24 13:50 UTC, Naresh-ibm reviewed
LGTM

2024-06-24 13:51 UTC, Naresh-ibm approved these changes
@PavamanSubramaniyam Thanks for PR

2024-06-24 13:51 UTC, merged