Added code to execute Trextest binaries.
avocado-framework-tests/avocado-misc-tests pull request #2839
Opened 2024-06-10 09:13 UTC by Krishan-Saraswat

Added code to execute all binaries inside trextest, it will replace kh_safeside.py test.

[root@]# avocado run --max-parallel-tasks=1 trex.py
JOB ID     : 98bf46b1756eb5e624793ab8bb8bb4efb9c29f8a
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-06-10T03.53-98bf46b/job.log
 (1/1) trex.py:Trex.test_trex: STARTED
 (1/1) trex.py:Trex.test_trex: PASS (374.56 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-06-10T03.53-98bf46b/results.html
JOB TIME   : 405.78 s

2024-06-10 09:45 UTC, Naresh-ibm requested changes

2024-06-10 09:45 UTC, Naresh-ibm commented on security/trextest.py
> +        demos_exec = process.system_output("find . -maxdepth 1 -perm /u=x,g=x,o=x -type f", ignore_status=True, sudo=True, shell=True).decode().split("\n")
Please take care of pep8 standards. line should not be greater than 79 characters

2024-06-10 09:45 UTC, Naresh-ibm commented on security/trextest.py
> +        build_exec = process.system_output("find . -maxdepth 1 -perm /u=x,g=x,o=x -type f", ignore_status=True, sudo=True, shell=True).decode().split("\n")
pep8 errors

2024-06-10 09:45 UTC, Naresh-ibm commented on security/trextest.py
> +        demos_exec = process.system_output("find . -maxdepth 1 -perm /u=x,g=x,o=x -type f", ignore_status=True, sudo=True, shell=True).decode().split("\n")
please split in more lines to make it easy readable manner.

2024-06-10 09:45 UTC, Naresh-ibm commented
take care of Travis check.

2024-06-12 06:18 UTC, Naresh-ibm requested changes

2024-06-12 06:18 UTC, Naresh-ibm commented on security/trextest.py
> +            shell=True
@Krishan-Saraswat why cann't you try this

```
cmd = "find . -maxdepth 1 -perm /u=x,g=x,o=x -type f"
demos_exec = process.system_output(cmd, ignore_status=True, sudo=True,
            shell=True)
```


Very easy process.

2024-06-12 06:18 UTC, Naresh-ibm commented on security/trextest.py
> +            shell=True
Please make this changes where ever it is do-able

2024-06-12 10:53 UTC, Krishan-Saraswat commented
Run logs after addressing above changes
[root@]# avocado run --max-parallel-tasks=1 trextest.py
JOB ID     : 1e0184a2fd258738ab3f5dd65290b1b1a426b3e5
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-06-12T04.05-1e0184a/job.log
 (1/1) trextest.py:Trex.test_trex: STARTED
 (1/1) trextest.py:Trex.test_trex: PASS (335.83 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-06-12T04.05-1e0184a/results.html
JOB TIME   : 367.32 s

2024-06-12 14:19 UTC, Naresh-ibm approved these changes
@Krishan-Saraswat Thanks for addressing all comments.
LGTM

2024-06-12 14:19 UTC, merged