perf: enhance tests to support Power11
avocado-framework-tests/avocado-misc-tests pull request #2865
Opened 2024-08-02 13:14 UTC by disgoel

This commit enhances the perf tests to support Power11 processor.

2024-08-06 15:17 UTC, Naresh-ibm requested changes
@disgoel please attach the run logs.

2024-08-06 18:44 UTC, disgoel commented
```
12:43:29 INFO    : Running Host Tests Suite perf_sanity_perf_24x7_all_events
12:43:29 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_24x7_all_events.py --force-job-id c6fcab9b6a5e25608a7a213ee02d3ca3d640cddc  --job-results-dir /home/avocado-fvt-wrapper/results
JOB ID     : f0a035073611e4596a995aa8bd5871179796c08c
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-07-31T21.27-f0a0350/job.log
 (1/1) perf_24x7_all_events.py:hv_24x7_all_events.test_all_events: STARTED
 (1/1) perf_24x7_all_events.py:hv_24x7_all_events.test_all_events: PASS (4020.83 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-07-31T21.27-f0a0350/results.html
JOB TIME   : 4046.88 s
```
```
11:58:21 INFO    : Running Host Tests Suite perf_sanity_perf_24x7_hardware_counters
11:58:21 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_24x7_hardware_counters.py --force-job-id 03855b2f654024b44451612458ce7691c1df0cd0  --job-results-dir /home/avocado-fvt-wrapper/results
JOB ID     : a1e6d1e716a4379c67491d37d804d344db9740a9
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-07-31T21.17-a1e6d1e/job.log
 (01/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: STARTED
 (01/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_display_domain_indices_in_sysfs: PASS (1.43 s)
 (02/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_phys_core_param: STARTED
 (02/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_phys_core_param: CANCEL: HPM_0THRD_NON_IDLE_CCYC__PHYS_CORE not found (21.72 s)
 (03/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_domain_param: STARTED
 (03/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_domain_param: PASS (1.44 s)
 (04/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_all_domains: STARTED
 (04/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_all_domains: PASS (54.11 s)
 (05/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_invalid_domains: STARTED
 (05/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_invalid_domains: PASS (3.47 s)
 (06/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_invalid_core: STARTED
 (06/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_invalid_core: PASS (1.44 s)
 (07/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_w_chip_param: STARTED
 (07/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_w_chip_param: PASS (1.43 s)
 (08/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_chip_param: STARTED
 (08/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_wo_chip_param: PASS (1.44 s)
 (09/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_valid_chip: STARTED
 (09/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_valid_chip: PASS (1.48 s)
 (10/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_invalid_chip: STARTED
 (10/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_check_invalid_chip: PASS (1.45 s)
 (11/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_domain_chip_offset: STARTED
 (11/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_domain_chip_offset: PASS (101.68 s)
 (12/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_phys_core: STARTED
 (12/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_phys_core: PASS (1.44 s)
 (13/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_vcpu: STARTED
 (13/13) perf_24x7_hardware_counters.py:EliminateDomainSuffix.test_event_helper_vcpu: PASS (1.45 s)
RESULTS    : PASS 12 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-07-31T21.17-a1e6d1e/results.html
JOB TIME   : 295.50 s
```
```
12:40:14 INFO    : Running Host Tests Suite perf_sanity_perf_cpu_hotplug
12:40:14 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_cpu_hotplug.py --force-job-id 58926ef7c8a344a9512d587f232f1203d793d47c  --job-results-dir /home/avocado-fvt-wrapper/results
JOB ID     : 961d048cc01aec083c337916c70dff848343401b
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-08-01T00.48-961d048/job.log
 (1/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_random: STARTED
 (1/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_random: PASS (29.35 s)
 (2/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_sequence: STARTED
 (2/2) perf_cpu_hotplug.py:perf_cpu_hotplug.test_cpumask_cpu_off_sequence: PASS (27.04 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-08-01T00.48-961d048/results.html
JOB TIME   : 85.11 s
```
```
11:59:54 INFO    : Running Host Tests Suite perf_sanity_perf_genericevents
11:59:54 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_genericevents.py --force-job-id b7d80461e6e5bb3c82611d8869a1c9150d73342f  --job-results-dir /home/avocado-fvt-wrapper/results
JOB ID     : 9eff8da8e27e4ac8e74c3cf63a139582791720dd
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-08-01T14.59-9eff8da/job.log
 (1/1) perf_genericevents.py:test_generic_events.test: STARTED
 (1/1) perf_genericevents.py:test_generic_events.test: PASS (0.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-08-01T14.59-9eff8da/results.html
JOB TIME   : 26.45 s
```
```
17:15:50 INFO    : Running Host Tests Suite perf_sanity_perf_json
17:15:50 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_json.py --force-job-id ab56708e3185997a1dc7b5f8b8d51335c802b37f  --job-results-dir /home/avocado-fvt-wrapper/results
Fetching asset from perf_json.py:perf_json.test_pmu_events
Fetching asset from perf_json.py:perf_json.test_compare
JOB ID     : 7c969b53b3dce61f8240c6c439df292776b4640f
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-08-01T12.54-7c969b5/job.log
 (1/2) perf_json.py:perf_json.test_pmu_events: STARTED
 (1/2) perf_json.py:perf_json.test_pmu_events: PASS (2206.49 s)
 (2/2) perf_json.py:perf_json.test_compare: STARTED
 (2/2) perf_json.py:perf_json.test_compare: PASS (2210.28 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-08-01T12.54-7c969b5/results.html
JOB TIME   : 4503.40 s
```
```
12:48:39 INFO    : Running Host Tests Suite perf_sanity_perf_metric
12:48:39 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /home/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_metric.py --force-job-id a78f1f201727c0ca37708d208626973abc86ded9  --job-results-dir /home/avocado-fvt-wrapper/results
JOB ID     : b3c39ecd0c9aa1ddfa51a50a0be018dadbe96da8
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-08-07T00.05-b3c39ec/job.log
 (1/3) perf_metric.py:perf_metric.test_all_metric_events_with_M: STARTED
 (1/3) perf_metric.py:perf_metric.test_all_metric_events_with_M: PASS (252.87 s)
 (2/3) perf_metric.py:perf_metric.test_all_metric_events_with_metric: STARTED
 (2/3) perf_metric.py:perf_metric.test_all_metric_events_with_metric: PASS (252.78 s)
 (3/3) perf_metric.py:perf_metric.test_cpi_stall: STARTED
 (3/3) perf_metric.py:perf_metric.test_cpi_stall: PASS (0.64 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 [...]

2024-08-06 18:50 UTC, disgoel commented
> @disgoel please attach the run logs.

attached test results and log files

2024-09-03 04:36 UTC, PraveenPenguin approved these changes

2024-09-03 04:36 UTC, merged