Reset peer and host IP after HTX runs
avocado-framework-tests/avocado-misc-tests pull request #2904
Opened 2024-10-08 06:09 UTC by vaishnavibhat

The patch addresses the following:
- Reset host IP with original IP
- Reset peer IP with original IP
- Add yaml parameters like peer_ips, netmask, hbond check.

2024-10-08 07:57 UTC, vaishnavibhat commented
#nohup python avocado-setup.py --run-suite host_io_network_fvt --input-file input.txt & 

#tail -f nohup.out 
02:37:53 INFO    : Check for environment
02:37:53 INFO    : Creating temporary mux dir
02:37:54 INFO    : 
02:37:54 INFO    : Running Host Tests Suite io_network_fvt_htx_nic_devices_HtxNicTest_test_start_htx_nic_devices
02:37:54 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start$ -m /tmp/mux/io_network_fvt_htx_nic_devices_HtxNicTest_test_start_htx_nic_devices.yaml --force-job-id e37f81136b4056bcc6432a38cf7cdadd4d22467a  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : e37f81136b4056bcc6432a38cf7cdadd4d22467a
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-10-08T02.37-e37f811/job.log
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start;run-f3c6: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start;run-f3c6:  PASS (245.90 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-10-08T02.37-e37f811/results.html
JOB TIME   : 261.38 s
02:42:18 INFO    : 
02:42:18 INFO    : 
02:42:18 INFO    : Running Host Tests Suite io_network_fvt_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices
02:42:18 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check$ -m /tmp/mux/io_network_fvt_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.yaml --force-job-id 0f636fed025ffb23f4515d4446cdccd45b0e17cb  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 0f636fed025ffb23f4515d4446cdccd45b0e17cb
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-10-08T02.42-0f636fe/job.log
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-f3c6: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-f3c6:  PASS (122.93 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-10-08T02.42-0f636fe/results.html
JOB TIME   : 138.88 s
02:44:40 INFO    : 
02:44:40 INFO    : 
02:44:40 INFO    : Running Host Tests Suite io_network_fvt_htx_nic_devices_HtxNicTest_test_stop_htx_nic_devices
02:44:40 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_stop$ -m /tmp/mux/io_network_fvt_htx_nic_devices_HtxNicTest_test_stop_htx_nic_devices.yaml --force-job-id d1f35e216c73b6b341ae2b46536060c519fea9ca  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : d1f35e216c73b6b341ae2b46536060c519fea9ca
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-10-08T02.44-d1f35e2/job.log
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_stop;run-f3c6: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_stop;run-f3c6:  PASS (7.33 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-10-08T02.44-d1f35e2/results.html
JOB TIME   : 23.13 s
02:45:07 INFO    : 
02:45:07 INFO    : 
02:45:07 INFO    : Running Host Tests Suite io_network_fvt_network_test_network_test_virt_net
02:45:07 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py -m /tmp/mux/io_network_fvt_network_test_network_test_virt_net.yaml --force-job-id 2cd5c7ad0c14787be688a3542416e4d126f15ea7  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 2cd5c7ad0c14787be688a3542416e4d126f15ea7
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-10-08T02.45-2cd5c7a/job.log
 (01/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_gro;run-mtu-1500-79e7: STARTED
 (01/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_gro;run-mtu-1500-79e7:  PASS (6.04 s)
 (02/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_gro;run-mtu-9000-0392: STARTED
 (02/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_gro;run-mtu-9000-0392:  PASS (15.13 s)
 (03/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_gso;run-mtu-1500-79e7: STARTED
 (03/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_gso;run-mtu-1500-79e7:  PASS (5.67 s)
 (04/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_gso;run-mtu-9000-0392: STARTED
 (04/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_gso;run-mtu-9000-0392:  PASS (15.14 s)
 (05/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_lro;run-mtu-1500-79e7: STARTED
 (05/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_lro;run-mtu-1500-79e7:  CANCEL: Unsupported on vNIC (5.61 s)
 (06/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_lro;run-mtu-9000-0392: STARTED
 (06/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_lro;run-mtu-9000-0392:  CANCEL: Unsupported on vNIC (14.89 s)
 (07/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_tso;run-mtu-1500-79e7: STARTED
 (07/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_tso;run-mtu-1500-79e7:  PASS (5.66 s)
 (08/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_tso;run-mtu-9000-0392: STARTED
 (08/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_tso;run-mtu-9000-0392:  PASS (15.19 s)
 (09/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_ping;run-mtu-1500-79e7: STARTED
 (09/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_ping;run-mtu-1500-79e7:  PASS (14.99 s)
 (10/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_ping;run-mtu-9000-0392: STARTED
 (10/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_ping;run-mtu-9000-0392:  PASS (24.36 s)
 (11/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_floodping;run-mtu-1500-79e7: STARTED
 (11/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_floodping;run-mtu-1500-79e7:  PASS (5.68 s)
 (12/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_floodping;run-mtu-9000-0392: STARTED
 (12/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_floodping;run-mtu-9000-0392:  PASS (14.86 s)
 (13/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_ipv6_ping;run-mtu-1500-79e7: STARTED
 (13/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_ipv6_ping;run-mtu-1500-79e7:  CANCEL: Test failing while getting IPV6 address for peer interface (5.64 s)
 (14/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_ipv6_ping;run-mtu-9000-0392: STARTED
 (14/24) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py:NetworkTest.test_ [...]

2024-10-10 05:29 UTC, abdhaleegit commented
@vaishnavibhat is this PR related to this https://github.com/avocado-framework-tests/avocado-misc-tests/pull/2864

2024-10-22 09:11 UTC, abdhaleegit requested changes
Is network configuration needed here ? if htx can take care of ip configurations .. let it .. only flush before and after test ?

Also how will this impact ... htx_start.. htx_check and htx_stop calls in cfg files for scenario cfg ?

2024-10-22 09:11 UTC, abdhaleegit commented on io/net/htx_nic_devices.py
> +        self.ip_addr_remove()
if you want to flush the IP, why to configure in the first place ?... incase to take a backup of ip configuration.. than every test case does configure network before start...  so just flush and delete the ips and than let htx configure its own ips.... and at the end of htx again.. flush out the thxips  ? am I missing something here ?

2024-10-22 09:11 UTC, abdhaleegit commented on io/net/htx_nic_devices.py
> +        self.ip_addr_remove()
remove this as ip_restore already flushes ips

2024-11-07 05:18 UTC, closed without merging