Added test to run grub unit test cases.
avocado-framework-tests/avocado-misc-tests pull request #2906
Opened 2024-10-13 18:01 UTC by Krishan-Saraswat

Added test to run grub unit test cases.

Added test to compile, build and run all grub unit test cases.

[root@ grub]# cat nohup.out
JOB ID     : c0a134ed61d1ae843bbdd4a3a388587bf0bf79f2
JOB LOG    : /home/avocado-fvt-wrapper/results/job-2024-10-09T00.59-c0a134e/job.log
 (1/1) grub_unit_test.py:UnitTestCases.test_grub_unit_testcases: STARTED
 (1/1) grub_unit_test.py:UnitTestCases.test_grub_unit_testcases:  FAIL: Total test fail are 3, please check the logs (4206.35 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/avocado-fvt-wrapper/results/job-2024-10-09T00.59-c0a134e/results.html
JOB TIME   : 4221.00 s

Test summary:
1-grub_unit_test.py:UnitTestCases.test_grub_unit_testcases: FAIL

[stdout] Testsuite summary for GRUB 2.13
[stdlog] 2024-10-09 02:10:01,758 avocado.utils.process process          L0472 DEBUG| [stdout] ============================================================================
[stdlog] 2024-10-09 02:10:01,758 avocado.utils.process process          L0472 DEBUG| [stdout] # TOTAL: 86
[stdlog] 2024-10-09 02:10:01,758 avocado.utils.process process          L0472 DEBUG| [stdout] # PASS:  49
[stdlog] 2024-10-09 02:10:01,758 avocado.utils.process process          L0472 DEBUG| [stdout] # SKIP:  9
[stdlog] 2024-10-09 02:10:01,758 avocado.utils.process process          L0472 DEBUG| [stdout] # XFAIL: 0
[stdlog] 2024-10-09 02:10:01,758 avocado.utils.process process          L0472 DEBUG| [stdout] # FAIL:  3
[stdlog] 2024-10-09 02:10:01,758 avocado.utils.process process          L0472 DEBUG| [stdout] # XPASS: 0
[stdlog] 2024-10-09 02:10:01,758 avocado.utils.process process          L0472 DEBUG| [stdout] # ERROR: 25
[stdlog] 2024-10-09 02:10:01,758 avocado.utils.process process          L0472 DEBUG| [stdout] ============================================================================

2024-10-15 07:12 UTC, PraveenPenguin requested changes

2024-10-15 07:12 UTC, PraveenPenguin commented on grub/grub_unit_test.py
> +class UnitTestCases(Test):
Class name seems confusing, can you rename like GrubUnitTestCases

2024-10-15 07:12 UTC, PraveenPenguin commented on grub/grub_unit_test.py
> +        if qemu_version.exit_status != 0:
if qemu_version.exit_status:  has same effect  and other places as well

2024-10-15 07:12 UTC, PraveenPenguin commented on grub/grub_unit_test.py
> +            process.run("git clone %s" % qemu_url)
Please use avocado git API

2024-10-15 07:12 UTC, PraveenPenguin commented on grub/grub_unit_test.py
> +            self.sourcedir_qemu = os.path.join(cwd, "qemu")
What about just  

self.sourcedir_qemu = os.path.join(os.getcwd(), "qemu") it will help to eliminate extra variable  and other places as well

2024-10-15 07:12 UTC, PraveenPenguin commented on grub/grub_unit_test.py
> +                        "make", "make install"]
what about using avocado build utility for make and make install ?

2026-07-03 08:24 UTC, Krishan-Saraswat commented
Closing this PR as there has been some code changes, will send a new PR with latest changes.

2026-07-03 08:24 UTC, closed without merging